#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Pigeon

#include "Basic.hpp"

#include "ABP_Pigeon_classes.hpp"
#include "ABP_Pigeon_parameters.hpp"


SDK_NAMESPACE_START

// Function ABP_Pigeon.ABP_Pigeon_C.ExecuteUbergraph_ABP_Pigeon
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_Pigeon_C::ExecuteUbergraph_ABP_Pigeon(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Pigeon_C", "ExecuteUbergraph_ABP_Pigeon");

	Params::ABP_Pigeon_C_ExecuteUbergraph_ABP_Pigeon Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_Pigeon.ABP_Pigeon_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Pigeon_AnimGraphNode_TransitionResult_5D57109940722AA460AF3AA3055D95E6
// (BlueprintEvent)

void UABP_Pigeon_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Pigeon_AnimGraphNode_TransitionResult_5D57109940722AA460AF3AA3055D95E6()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Pigeon_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Pigeon_AnimGraphNode_TransitionResult_5D57109940722AA460AF3AA3055D95E6");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_Pigeon.ABP_Pigeon_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Pigeon_AnimGraphNode_TransitionResult_45AC8905456B97C7C80295972EF4B44E
// (BlueprintEvent)

void UABP_Pigeon_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Pigeon_AnimGraphNode_TransitionResult_45AC8905456B97C7C80295972EF4B44E()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Pigeon_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Pigeon_AnimGraphNode_TransitionResult_45AC8905456B97C7C80295972EF4B44E");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_Pigeon.ABP_Pigeon_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph                                              (Parm, OutParm, NoDestructor)

void UABP_Pigeon_C::AnimGraph(struct FPoseLink* AnimGraph)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Pigeon_C", "AnimGraph");

	Params::ABP_Pigeon_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph != nullptr)
		*AnimGraph = std::move(Parms.AnimGraph);
}


SDK_NAMESPACE_END
