#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Villager_Baby

#include "Basic.hpp"

#include "ABP_Villager_Baby_classes.hpp"
#include "ABP_Villager_Baby_parameters.hpp"


SDK_NAMESPACE_START

// Function ABP_Villager_Baby.ABP_Villager_Baby_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UABP_Villager_Baby_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Villager_Baby_C", "AnimGraph");

	Params::ABP_Villager_Baby_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function ABP_Villager_Baby.ABP_Villager_Baby_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Villager_Baby_AnimGraphNode_TransitionResult_2C6CFE654AF6E644752548B3D21E317F
// (BlueprintEvent)

void UABP_Villager_Baby_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Villager_Baby_AnimGraphNode_TransitionResult_2C6CFE654AF6E644752548B3D21E317F()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Villager_Baby_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Villager_Baby_AnimGraphNode_TransitionResult_2C6CFE654AF6E644752548B3D21E317F");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_Villager_Baby.ABP_Villager_Baby_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Villager_Baby_AnimGraphNode_TransitionResult_33276D87415E3F47C57CCFA0A160A5C9
// (BlueprintEvent)

void UABP_Villager_Baby_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Villager_Baby_AnimGraphNode_TransitionResult_33276D87415E3F47C57CCFA0A160A5C9()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Villager_Baby_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Villager_Baby_AnimGraphNode_TransitionResult_33276D87415E3F47C57CCFA0A160A5C9");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_Villager_Baby.ABP_Villager_Baby_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Villager_Baby_AnimGraphNode_TransitionResult_42188BEC43DE1F91251BE08F0431D3E7
// (BlueprintEvent)

void UABP_Villager_Baby_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Villager_Baby_AnimGraphNode_TransitionResult_42188BEC43DE1F91251BE08F0431D3E7()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Villager_Baby_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Villager_Baby_AnimGraphNode_TransitionResult_42188BEC43DE1F91251BE08F0431D3E7");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_Villager_Baby.ABP_Villager_Baby_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Villager_Baby_AnimGraphNode_TransitionResult_61A51FA340D78DC5532077B5CFFECD80
// (BlueprintEvent)

void UABP_Villager_Baby_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Villager_Baby_AnimGraphNode_TransitionResult_61A51FA340D78DC5532077B5CFFECD80()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Villager_Baby_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Villager_Baby_AnimGraphNode_TransitionResult_61A51FA340D78DC5532077B5CFFECD80");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_Villager_Baby.ABP_Villager_Baby_C.ExecuteUbergraph_ABP_Villager_Baby
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_Villager_Baby_C::ExecuteUbergraph_ABP_Villager_Baby(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Villager_Baby_C", "ExecuteUbergraph_ABP_Villager_Baby");

	Params::ABP_Villager_Baby_C_ExecuteUbergraph_ABP_Villager_Baby Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_Villager_Baby.ABP_Villager_Baby_C.OwnerTagStatusChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// const struct FGameplayTag&              Tag                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// const bool                              TagAdded                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_Villager_Baby_C::OwnerTagStatusChanged(const struct FGameplayTag& Tag, const bool TagAdded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Villager_Baby_C", "OwnerTagStatusChanged");

	Params::ABP_Villager_Baby_C_OwnerTagStatusChanged Parms{};

	Parms.Tag = std::move(Tag);
	Parms.TagAdded = TagAdded;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
