#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AlexCharacter

#include "Basic.hpp"

#include "BP_PlayerCharacter_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_AlexCharacter.BP_AlexCharacter_C
// 0x0040 (0x1010 - 0x0FD0)
class ABP_AlexCharacter_C final : public ABP_PlayerCharacter_C
{
public:
	class UPhysicsConstraintComponent*            PhysicsConstraint;                                 // 0x0FC8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   BP_PlayerLantern;                                  // 0x0FD0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Lantern;                                           // 0x0FD8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   LanternConstraint;                                 // 0x0FE0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDecalComponent*                        Decal;                                             // 0x0FE8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDungeonsChildActorComponent*           Backpack;                                          // 0x0FF0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDungeonsChildActorComponent*           Armor;                                             // 0x0FF8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDungeonsChildActorComponent*           RangedWeapon;                                      // 0x1000(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDungeonsChildActorComponent*           MeleeWeapon;                                       // 0x1008(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void SetPlayerNonAlphaComponentsVisible(bool Visible);
	void Enable_Charge();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_AlexCharacter_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_AlexCharacter_C")
	}
	static class ABP_AlexCharacter_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_AlexCharacter_C>();
	}
};
DUMPER7_ASSERTS_ABP_AlexCharacter_C;

SDK_NAMESPACE_END
