#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CA01_B_MerchantSupplies_Empty

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_CA01_B_MerchantSupplies_Empty.BP_CA01_B_MerchantSupplies_Empty_C.ExecuteUbergraph_BP_CA01_B_MerchantSupplies_Empty
// 0x0008 (0x0008 - 0x0000)
struct BP_CA01_B_MerchantSupplies_Empty_C_ExecuteUbergraph_BP_CA01_B_MerchantSupplies_Empty final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsVisible_ReturnValue;                    // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_CA01_B_MerchantSupplies_Empty_C_ExecuteUbergraph_BP_CA01_B_MerchantSupplies_Empty;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
