#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Depthfade

#include "Basic.hpp"

#include "Dungeons_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Depthfade.BP_Depthfade_C
// 0x0028 (0x0308 - 0x02E0)
class ABP_Depthfade_C : public APropActor
{
public:
	class UQualityLevelSwitch_C*                  QualityLevelSwitch;                                // 0x02E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_DepthPlaneLargeTessellated;                     // 0x02E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	bool                                          RadialFade_;                                       // 0x02F8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2F9[0x7];                                      // 0x02F9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstance*                      Material;                                          // 0x0300(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Depthfade_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Depthfade_C")
	}
	static class ABP_Depthfade_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Depthfade_C>();
	}
};
DUMPER7_ASSERTS_ABP_Depthfade_C;

SDK_NAMESPACE_END
