#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DD_Brazier

#include "Basic.hpp"

#include "BP_DD_Brazier_classes.hpp"
#include "BP_DD_Brazier_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_DD_Brazier.BP_DD_Brazier_C.ExecuteUbergraph_BP_DD_Brazier
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DD_Brazier_C::ExecuteUbergraph_BP_DD_Brazier(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DD_Brazier_C", "ExecuteUbergraph_BP_DD_Brazier");

	Params::BP_DD_Brazier_C_ExecuteUbergraph_BP_DD_Brazier Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DD_Brazier.BP_DD_Brazier_C.PlayerInVisibleRangeChanged
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    Visible                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DD_Brazier_C::PlayerInVisibleRangeChanged(bool Visible)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DD_Brazier_C", "PlayerInVisibleRangeChanged");

	Params::BP_DD_Brazier_C_PlayerInVisibleRangeChanged Parms{};

	Parms.Visible = Visible;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DD_Brazier.BP_DD_Brazier_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_DD_Brazier_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DD_Brazier_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DD_Brazier.BP_DD_Brazier_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_DD_Brazier_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DD_Brazier_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
