#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GameInstance_Interface

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_GameInstance_Interface.BP_GameInstance_Interface_C
// 0x0000 (0x0000 - 0x0000)
class IBP_GameInstance_Interface_C final
{
public:
	void AllowMenuKeyPress(bool* Allowed);
	void Get_EventDispatcher(class UBP_GameInstance_EventDispatcher_C** EventDispatcher);
	void IsPopupOpen(bool* Open);
	void LoginRequest(int32 incomingID, const struct FKey& incomingKey);
	void SetDisconnectPopupEnabled(bool Val, bool* Out);
	void SetupNextAchievement();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_GameInstance_Interface_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_GameInstance_Interface_C")
	}
	static class IBP_GameInstance_Interface_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBP_GameInstance_Interface_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
DUMPER7_ASSERTS_IBP_GameInstance_Interface_C;

SDK_NAMESPACE_END
