#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_JumpTrap

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "E_JumpTrapVisuals_structs.hpp"
#include "SWCoreGameplay_classes.hpp"
#include "MSAudioRuntime_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_JumpTrap.BP_JumpTrap_C
// 0x00A0 (0x0540 - 0x04A0)
class ABP_JumpTrap_C final : public AJumpTrap
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UMSAudioComponent*                      MSAudio;                                           // 0x04A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               PS_JumpTrapDust;                                   // 0x04B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   PistonLid1;                                        // 0x04B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   PistonBase1;                                       // 0x04C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        PistonBases;                                       // 0x04C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        PistonTops;                                        // 0x04D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         Launch_Position_5358658F4F24D42DCDF3A982DDABB158;  // 0x04D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Launch__Direction_5358658F4F24D42DCDF3A982DDABB158; // 0x04DC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4DD[0x3];                                      // 0x04DD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Launch;                                            // 0x04E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FVector                                Piston_Start_Position;                             // 0x04E8(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UStaticMesh*>                    PistonTopVariants;                                 // 0x0500(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class UStaticMesh*>                    PistonBaseVariants;                                // 0x0510(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	E_JumpTrapVisuals                             Visuals;                                           // 0x0520(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_521[0x7];                                      // 0x0521(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UAkAudioEvent*>                  PistonVariantAudioEvents;                          // 0x0528(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	class UAkAudioEvent*                          PistonAudioEventToUse;                             // 0x0538(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();
	void ReceiveBeginPlay();
	void Launch__UpdateFunc();
	void Launch__FinishedFunc();
	void ExecuteUbergraph_BP_JumpTrap(int32 EntryPoint);
	void BP_OnLaunch();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_JumpTrap_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_JumpTrap_C")
	}
	static class ABP_JumpTrap_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_JumpTrap_C>();
	}
};
DUMPER7_ASSERTS_ABP_JumpTrap_C;

SDK_NAMESPACE_END
