#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_KeyGolemSpawnerActorStateGimmick

#include "Basic.hpp"

#include "SpicewoodLevelGimmicks_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_KeyGolemSpawnerActorStateGimmick.BP_KeyGolemSpawnerActorStateGimmick_C
// 0x0008 (0x03D0 - 0x03C8)
class ABP_KeyGolemSpawnerActorStateGimmick_C final : public AKeySpawnActorStateGimmick
{
public:
	class UArrowComponent*                        Arrow;                                             // 0x03C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_KeyGolemSpawnerActorStateGimmick_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_KeyGolemSpawnerActorStateGimmick_C")
	}
	static class ABP_KeyGolemSpawnerActorStateGimmick_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_KeyGolemSpawnerActorStateGimmick_C>();
	}
};
DUMPER7_ASSERTS_ABP_KeyGolemSpawnerActorStateGimmick_C;

SDK_NAMESPACE_END
