#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Lighthouse

#include "Basic.hpp"

#include "BP_Lighthouse_classes.hpp"
#include "BP_Lighthouse_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_Lighthouse.BP_Lighthouse_C.ExecuteUbergraph_BP_Lighthouse
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Lighthouse_C::ExecuteUbergraph_BP_Lighthouse(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Lighthouse_C", "ExecuteUbergraph_BP_Lighthouse");

	Params::BP_Lighthouse_C_ExecuteUbergraph_BP_Lighthouse Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Lighthouse.BP_Lighthouse_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Lighthouse_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Lighthouse_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Lighthouse.BP_Lighthouse_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Lighthouse_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Lighthouse_C", "ReceiveTick");

	Params::BP_Lighthouse_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
