#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MinecartStationIconWidgetComponent

#include "Basic.hpp"

#include "Angelscript_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_MinecartStationIconWidgetComponent.BP_MinecartStationIconWidgetComponent_C
// 0x0000 (0x0370 - 0x0370)
class UBP_MinecartStationIconWidgetComponent_C final : public UAS_MinecartStationIconWidgetComponent
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_MinecartStationIconWidgetComponent_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_MinecartStationIconWidgetComponent_C")
	}
	static class UBP_MinecartStationIconWidgetComponent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_MinecartStationIconWidgetComponent_C>();
	}
};
DUMPER7_ASSERTS_UBP_MinecartStationIconWidgetComponent_C;

SDK_NAMESPACE_END
