#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PocketCapture

#include "Basic.hpp"

#include "PocketWorlds_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_PocketCapture.BP_PocketCapture_C
// 0x0000 (0x00A8 - 0x00A8)
class UBP_PocketCapture_C final : public UPocketCapture
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PocketCapture_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PocketCapture_C")
	}
	static class UBP_PocketCapture_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_PocketCapture_C>();
	}
};
DUMPER7_ASSERTS_UBP_PocketCapture_C;

SDK_NAMESPACE_END
