#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ProgressThroughDayRemapper

#include "Basic.hpp"

#include "BP_ProgressThroughDayRemapper_classes.hpp"
#include "BP_ProgressThroughDayRemapper_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_ProgressThroughDayRemapper.BP_ProgressThroughDayRemapper_C.Stop
// (BlueprintCallable, BlueprintEvent)

void ABP_ProgressThroughDayRemapper_C::Stop()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ProgressThroughDayRemapper_C", "Stop");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ProgressThroughDayRemapper.BP_ProgressThroughDayRemapper_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds_ReceiveTick                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ProgressThroughDayRemapper_C::ReceiveTick(float DeltaSeconds_ReceiveTick)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ProgressThroughDayRemapper_C", "ReceiveTick");

	Params::BP_ProgressThroughDayRemapper_C_ReceiveTick Parms{};

	Parms.DeltaSeconds_ReceiveTick = DeltaSeconds_ReceiveTick;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ProgressThroughDayRemapper.BP_ProgressThroughDayRemapper_C.ExecuteUbergraph_BP_ProgressThroughDayRemapper
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ProgressThroughDayRemapper_C::ExecuteUbergraph_BP_ProgressThroughDayRemapper(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ProgressThroughDayRemapper_C", "ExecuteUbergraph_BP_ProgressThroughDayRemapper");

	Params::BP_ProgressThroughDayRemapper_C_ExecuteUbergraph_BP_ProgressThroughDayRemapper Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ProgressThroughDayRemapper.BP_ProgressThroughDayRemapper_C.Catch Up__UpdateFunc
// (BlueprintEvent)

void ABP_ProgressThroughDayRemapper_C::Catch_Up__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ProgressThroughDayRemapper_C", "Catch Up__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ProgressThroughDayRemapper.BP_ProgressThroughDayRemapper_C.Catch Up__FinishedFunc
// (BlueprintEvent)

void ABP_ProgressThroughDayRemapper_C::Catch_Up__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ProgressThroughDayRemapper_C", "Catch Up__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
