#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_QuestCharacterBase

#include "Basic.hpp"

#include "SWCoreGameplay_structs.hpp"
#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_QuestCharacterBase.BP_QuestCharacterBase_C.BndEvt__BP_QuestASCActorBase_AbilitySystemComponent_K2Node_ComponentBoundEvent_0_OnActorHighlightStatusChanged__DelegateSignature
// 0x0020 (0x0020 - 0x0000)
struct BP_QuestCharacterBase_C_BndEvt__BP_QuestASCActorBase_AbilitySystemComponent_K2Node_ComponentBoundEvent_0_OnActorHighlightStatusChanged__DelegateSignature final
{
public:
	struct FActorHighlightMessage                 Message;                                           // 0x0000(0x0020)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
};
DUMPER7_ASSERTS_BP_QuestCharacterBase_C_BndEvt__BP_QuestASCActorBase_AbilitySystemComponent_K2Node_ComponentBoundEvent_0_OnActorHighlightStatusChanged__DelegateSignature;

// Function BP_QuestCharacterBase.BP_QuestCharacterBase_C.ExecuteUbergraph_BP_QuestCharacterBase
// 0x0048 (0x0048 - 0x0000)
struct BP_QuestCharacterBase_C_ExecuteUbergraph_BP_QuestCharacterBase final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FActorHighlightMessage                 K2Node_ComponentBoundEvent_Message;                // 0x0008(0x0020)(ConstParm, NoDestructor)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0028(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_PostEventAtLocation_ReturnValue;          // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_QuestCharacterBase_C_ExecuteUbergraph_BP_QuestCharacterBase;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
