#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_QuestCharacterBase

#include "Basic.hpp"

#include "Angelscript_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_QuestCharacterBase.BP_QuestCharacterBase_C
// 0x0040 (0x0B80 - 0x0B40)
class ABP_QuestCharacterBase_C : public AAS_QuestCharacter
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0B40(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UActorToggleComponent*                  ActorToggleComponent;                              // 0x0B48(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCameraComponent*                       DialogueCamera;                                    // 0x0B50(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USpringArmComponent*                    SpringArm;                                         // 0x0B58(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      NS_QuestIdleParticle;                              // 0x0B60(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UQuestActorBehaviourComponent*          QuestActorBehaviour;                               // 0x0B68(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UQuestEventReceiverComponent*           QuestEventReceiver;                                // 0x0B70(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAkAudioEvent*                          MouseHoverSound;                                   // 0x0B78(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__BP_QuestASCActorBase_AbilitySystemComponent_K2Node_ComponentBoundEvent_0_OnActorHighlightStatusChanged__DelegateSignature(const struct FActorHighlightMessage& Message);
	void ExecuteUbergraph_BP_QuestCharacterBase(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_QuestCharacterBase_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_QuestCharacterBase_C")
	}
	static class ABP_QuestCharacterBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_QuestCharacterBase_C>();
	}
};
DUMPER7_ASSERTS_ABP_QuestCharacterBase_C;

SDK_NAMESPACE_END
