#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RoadblockActorStateGimmick

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "SpicewoodLevelGimmicks_classes.hpp"
#include "MSAudioRuntime_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_RoadblockActorStateGimmick.BP_RoadblockActorStateGimmick_C
// 0x0048 (0x04A8 - 0x0460)
class ABP_RoadblockActorStateGimmick_C : public ARoadblockActorStateGimmick
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0460(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UMSAudioComponent*                      MSAudio;                                           // 0x0468(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBP_InWorldPromptInteractComponent_C*   BP_InWorldPromptInteractWidgetComponent;           // 0x0470(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAkAudioEvent*                          EventOnRoadblockStartedMoving;                     // 0x0478(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAkAudioEvent*                          EventOnRoadblockStoppedMoving;                     // 0x0480(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAkAudioEvent*                          EventHoverOn;                                      // 0x0488(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               BoulderMaterial;                                   // 0x0490(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          NewVar;                                            // 0x0498(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_499[0x7];                                      // 0x0499(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAkAudioEvent*                          EventClickHaptics;                                 // 0x04A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__BP_RoadblockActorStateGimmick_IdentifyAsTypeComponent_K2Node_ComponentBoundEvent_0_OnHighlightStatusChanged__DelegateSignature(const struct FActorHighlightMessage& Message);
	void ExecuteUbergraph_BP_RoadblockActorStateGimmick(int32 EntryPoint);
	void OnActorStateChanged(const struct FActorState& State, bool IsReplayingStateChange);
	void OnGimmickInteracted(const class AActor* InInstigator);
	void OnRoadblockMoved(float DistanceAlongSpline);
	void OnRoadblockStartedMoving();
	void OnRoadblockStoppedMoving();
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_RoadblockActorStateGimmick_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_RoadblockActorStateGimmick_C")
	}
	static class ABP_RoadblockActorStateGimmick_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_RoadblockActorStateGimmick_C>();
	}
};
DUMPER7_ASSERTS_ABP_RoadblockActorStateGimmick_C;

SDK_NAMESPACE_END
