#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TotemOfCastingActor

#include "Basic.hpp"

#include "BP_TotemOfCastingActor_classes.hpp"
#include "BP_TotemOfCastingActor_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_TotemOfCastingActor.BP_TotemOfCastingActor_C.BndEvt__BP_RegenerationTotemActor_AbilitySystemComponent_K2Node_ComponentBoundEvent_0_AttributeChangedDelegate_Dynamic__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// const struct FGameplayAttribute&        Attribute                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
// float                                   OldValue                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   NewValue                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_TotemOfCastingActor_C::BndEvt__BP_RegenerationTotemActor_AbilitySystemComponent_K2Node_ComponentBoundEvent_0_AttributeChangedDelegate_Dynamic__DelegateSignature(const struct FGameplayAttribute& Attribute, float OldValue, float NewValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TotemOfCastingActor_C", "BndEvt__BP_RegenerationTotemActor_AbilitySystemComponent_K2Node_ComponentBoundEvent_0_AttributeChangedDelegate_Dynamic__DelegateSignature");

	Params::BP_TotemOfCastingActor_C_BndEvt__BP_RegenerationTotemActor_AbilitySystemComponent_K2Node_ComponentBoundEvent_0_AttributeChangedDelegate_Dynamic__DelegateSignature Parms{};

	Parms.Attribute = std::move(Attribute);
	Parms.OldValue = OldValue;
	Parms.NewValue = NewValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TotemOfCastingActor.BP_TotemOfCastingActor_C.ExecuteUbergraph_BP_TotemOfCastingActor
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_TotemOfCastingActor_C::ExecuteUbergraph_BP_TotemOfCastingActor(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TotemOfCastingActor_C", "ExecuteUbergraph_BP_TotemOfCastingActor");

	Params::BP_TotemOfCastingActor_C_ExecuteUbergraph_BP_TotemOfCastingActor Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TotemOfCastingActor.BP_TotemOfCastingActor_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_TotemOfCastingActor_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TotemOfCastingActor_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TotemOfCastingActor.BP_TotemOfCastingActor_C.Timeline_0__FinishedFunc
// (BlueprintEvent)

void ABP_TotemOfCastingActor_C::Timeline_0__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TotemOfCastingActor_C", "Timeline_0__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TotemOfCastingActor.BP_TotemOfCastingActor_C.Timeline_0__UpdateFunc
// (BlueprintEvent)

void ABP_TotemOfCastingActor_C::Timeline_0__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TotemOfCastingActor_C", "Timeline_0__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TotemOfCastingActor.BP_TotemOfCastingActor_C.Timeline__FinishedFunc
// (BlueprintEvent)

void ABP_TotemOfCastingActor_C::Timeline__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TotemOfCastingActor_C", "Timeline__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TotemOfCastingActor.BP_TotemOfCastingActor_C.Timeline__UpdateFunc
// (BlueprintEvent)

void ABP_TotemOfCastingActor_C::Timeline__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TotemOfCastingActor_C", "Timeline__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
