#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Villager_Baby

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_MobCharacter_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Villager_Baby.BP_Villager_Baby_C
// 0x0010 (0x0B30 - 0x0B20)
class ABP_Villager_Baby_C : public ABP_MobCharacter_C
{
public:
	uint8                                         Pad_B19[0x7];                                      // 0x0B19(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0B20(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_Villager_Baby(int32 EntryPoint);
	void GetEffectScale(struct FVector* Size);
	void GetParticleSize(struct FVector* ParticleSize);
	void GetSpawn(double* Spawn);
	void GetSpread(double* Spread);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Villager_Baby_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Villager_Baby_C")
	}
	static class ABP_Villager_Baby_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Villager_Baby_C>();
	}
};
DUMPER7_ASSERTS_ABP_Villager_Baby_C;

SDK_NAMESPACE_END
