#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCN_PlayItemAudio

#include "Basic.hpp"

#include "InventorySystem_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GCN_PlayItemAudio.GCN_PlayItemAudio_C
// 0x0000 (0x0040 - 0x0040)
class UGCN_PlayItemAudio_C final : public UGCN_PlayAudioBasedOnItemSlot
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GCN_PlayItemAudio_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GCN_PlayItemAudio_C")
	}
	static class UGCN_PlayItemAudio_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGCN_PlayItemAudio_C>();
	}
};
DUMPER7_ASSERTS_UGCN_PlayItemAudio_C;

SDK_NAMESPACE_END
