#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LobbyMessageSubsystem

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"
#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// Class LobbyMessageSubsystem.LobbyMessageInbox
// 0x0010 (0x0038 - 0x0028)
class ULobbyMessageInbox final : public UObject
{
public:
	uint8                                         Pad_28[0x10];                                      // 0x0028(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void FetchMessages();

	void MarkRead(const class FString& MessageId) const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("LobbyMessageInbox")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"LobbyMessageInbox")
	}
	static class ULobbyMessageInbox* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULobbyMessageInbox>();
	}
};
DUMPER7_ASSERTS_ULobbyMessageInbox;

// Class LobbyMessageSubsystem.LobbyMessageSubsystem
// 0x0008 (0x0038 - 0x0030)
class ULobbyMessageSubsystem final : public ULocalPlayerSubsystem
{
public:
	class ULobbyMessageInbox*                     LobbyMessageInbox;                                 // 0x0030(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate, TObjectPtr)

public:
	class ULobbyMessageInbox* Get() const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("LobbyMessageSubsystem")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"LobbyMessageSubsystem")
	}
	static class ULobbyMessageSubsystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULobbyMessageSubsystem>();
	}
};
DUMPER7_ASSERTS_ULobbyMessageSubsystem;

SDK_NAMESPACE_END
