#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MapSystems

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "MapSystemTypes_structs.hpp"
#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function MapSystems.ClientMapsSubsystem.Get
// 0x0010 (0x0010 - 0x0000)
struct ClientMapsSubsystem_Get final
{
public:
	const class UWorld*                           World;                                             // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UClientMapsSubsystem*                   ReturnValue;                                       // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ClientMapsSubsystem_Get;

// Function MapSystems.ClientMapsSubsystem.GetFancyMapToAreaBoundsRatio
// 0x0018 (0x0018 - 0x0000)
struct ClientMapsSubsystem_GetFancyMapToAreaBoundsRatio final
{
public:
	struct FGameplayTag                           RegionTag;                                         // 0x0000(0x0008)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector2D                              ReturnValue;                                       // 0x0008(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ClientMapsSubsystem_GetFancyMapToAreaBoundsRatio;

// Function MapSystems.ClientMapsSubsystem.GetMinimapDisplayDetails
// 0x0020 (0x0020 - 0x0000)
struct ClientMapsSubsystem_GetMinimapDisplayDetails final
{
public:
	struct FVector2D                              OutLookAtTextureUV;                                // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         OutMapViewTextureWidth;                            // 0x0010(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         OutMapRotation;                                    // 0x0014(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         OutMapTilt;                                        // 0x0018(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x001C(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_ClientMapsSubsystem_GetMinimapDisplayDetails;

// Function MapSystems.ClientMapsSubsystem.GetPrimaryPlayerRegionContext
// 0x0014 (0x0014 - 0x0000)
struct ClientMapsSubsystem_GetPrimaryPlayerRegionContext final
{
public:
	struct FPlayerRegionContext                   ReturnValue;                                       // 0x0000(0x0014)(ConstParm, Parm, OutParm, ReturnParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ClientMapsSubsystem_GetPrimaryPlayerRegionContext;

// Function MapSystems.ClientMapsSubsystem.SetWorldMapDisplayRegion
// 0x0008 (0x0008 - 0x0000)
struct ClientMapsSubsystem_SetWorldMapDisplayRegion final
{
public:
	struct FGameplayTag                           InMapDisplayRegionTag;                             // 0x0000(0x0008)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ClientMapsSubsystem_SetWorldMapDisplayRegion;

// Function MapSystems.ClientMapsSubsystem.GetNormalizedPositionInRegion
// 0x0030 (0x0030 - 0x0000)
struct ClientMapsSubsystem_GetNormalizedPositionInRegion final
{
public:
	struct FGameplayTag                           RegionTag;                                         // 0x0000(0x0008)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                Location;                                          // 0x0008(0x0018)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector2D                              ReturnValue;                                       // 0x0020(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ClientMapsSubsystem_GetNormalizedPositionInRegion;

// Function MapSystems.MinimapRectangleRenderer.RenderFilledRectangle
// 0x0001 (0x0001 - 0x0000)
struct MinimapRectangleRenderer_RenderFilledRectangle final
{
public:
	EMinimapPixelId                               PixelId;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_MinimapRectangleRenderer_RenderFilledRectangle;

// Function MapSystems.MinimapRectangleRenderer.RenderRectangle
// 0x0002 (0x0002 - 0x0000)
struct MinimapRectangleRenderer_RenderRectangle final
{
public:
	EMinimapPixelId                               PixelTypeToRender;                                 // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bClearRect;                                        // 0x0001(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_MinimapRectangleRenderer_RenderRectangle;

// Function MapSystems.MinimapRectangleRenderer.RenderRectangleDelayed
// 0x0030 (0x0030 - 0x0000)
struct MinimapRectangleRenderer_RenderRectangleDelayed final
{
public:
	struct FGameplayTag                           AreaTag;                                           // 0x0000(0x0008)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSoftObjectPtr<class UTexture2D>              TexturePtr;                                        // 0x0008(0x0028)(Parm, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_MinimapRectangleRenderer_RenderRectangleDelayed;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
