#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MCCoreWorld

#include "Basic.hpp"


SDK_NAMESPACE_START

// Enum MCCoreWorld.EBlockRenderLayer
// NumValues: 0x0018
enum class EBlockRenderLayer : uint8
{
	Opaque                                   = 0,
	OpaqueAdditionalZeroAlphaGeometry        = 1,
	Water                                    = 2,
	OuchWater                                = 3,
	DoubleSided                              = 4,
	Blend                                    = 5,
	EndPortal                                = 6,
	OptionalAlphaTest                        = 7,
	AlphaTest                                = 8,
	AlphaTestFoliage                         = 9,
	SeasonsOpaque                            = 10,
	SeasonsOptionalAlphaTest                 = 11,
	AlphaTestSingleSide                      = 12,
	Lava                                     = 13,
	Torch                                    = 14,
	Fire                                     = 15,
	Leaves                                   = 16,
	OpaqueFill                               = 17,
	Void                                     = 18,
	Kill                                     = 19,
	Sculk                                    = 20,
	VoidFill                                 = 21,
	Count                                    = 22,
	EBlockRenderLayer_MAX                    = 23,
};

SDK_NAMESPACE_END
