#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SpicewoodGuidance

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "CoreUObject_structs.hpp"
#include "CoreUObject_classes.hpp"
#include "SpicewoodGuidance_structs.hpp"
#include "DeveloperSettings_classes.hpp"


SDK_NAMESPACE_START

// Class SpicewoodGuidance.PathDebugActor
// 0x0000 (0x02A8 - 0x02A8)
class APathDebugActor final : public AActor
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PathDebugActor")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PathDebugActor")
	}
	static class APathDebugActor* GetDefaultObj()
	{
		return GetDefaultObjImpl<APathDebugActor>();
	}
};
DUMPER7_ASSERTS_APathDebugActor;

// Class SpicewoodGuidance.SWGuidanceGenerationSubsystem
// 0x0078 (0x00A8 - 0x0030)
class USWGuidanceGenerationSubsystem final : public UEngineSubsystem
{
public:
	uint8                                         Pad_30[0x78];                                      // 0x0030(0x0078)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SWGuidanceGenerationSubsystem")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SWGuidanceGenerationSubsystem")
	}
	static class USWGuidanceGenerationSubsystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<USWGuidanceGenerationSubsystem>();
	}
};
DUMPER7_ASSERTS_USWGuidanceGenerationSubsystem;

// Class SpicewoodGuidance.SWGuidancePathCache
// 0x0068 (0x0090 - 0x0028)
class USWGuidancePathCache final : public UObject
{
public:
	uint8                                         Pad_28[0x68];                                      // 0x0028(0x0068)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SWGuidancePathCache")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SWGuidancePathCache")
	}
	static class USWGuidancePathCache* GetDefaultObj()
	{
		return GetDefaultObjImpl<USWGuidancePathCache>();
	}
};
DUMPER7_ASSERTS_USWGuidancePathCache;

// Class SpicewoodGuidance.SWGuidanceNetwork
// 0x0210 (0x0238 - 0x0028)
class USWGuidanceNetwork final : public UObject
{
public:
	uint8                                         Pad_28[0xF8];                                      // 0x0028(0x00F8)(Fixing Size After Last Property [ Dumper-7 ])
	class USWGuidancePathCache*                   PathCache;                                         // 0x0120(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate, TObjectPtr)
	uint8                                         Pad_128[0xA0];                                     // 0x0128(0x00A0)(Fixing Size After Last Property [ Dumper-7 ])
	class UWorld*                                 World;                                             // 0x01C8(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate, TObjectPtr)
	struct FSWGuidanceNetworkMetaData             MetaData;                                          // 0x01D0(0x0068)(NativeAccessSpecifierPrivate)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SWGuidanceNetwork")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SWGuidanceNetwork")
	}
	static class USWGuidanceNetwork* GetDefaultObj()
	{
		return GetDefaultObjImpl<USWGuidanceNetwork>();
	}
};
DUMPER7_ASSERTS_USWGuidanceNetwork;

// Class SpicewoodGuidance.SWGuidanceSettings
// 0x0080 (0x00B8 - 0x0038)
class USWGuidanceSettings final : public UDeveloperSettings
{
public:
	struct FFloatInterval                         NavPathRange;                                      // 0x0038(0x0008)(Edit, ZeroConstructor, Config, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SpatialGridCellSize;                               // 0x0040(0x0004)(Edit, ZeroConstructor, Config, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGuidanceGenerationSettings            GenerationSettings;                                // 0x0044(0x0010)(Edit, Config, DisableEditOnInstance, NoDestructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_54[0x4];                                       // 0x0054(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGuidanceValidationSettings            ValidationSettings;                                // 0x0058(0x0060)(Edit, Config, DisableEditOnInstance, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SWGuidanceSettings")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SWGuidanceSettings")
	}
	static class USWGuidanceSettings* GetDefaultObj()
	{
		return GetDefaultObjImpl<USWGuidanceSettings>();
	}
};
DUMPER7_ASSERTS_USWGuidanceSettings;

// Class SpicewoodGuidance.SWGuidancePathComponent
// 0x0010 (0x0250 - 0x0240)
class USWGuidancePathComponent final : public USceneComponent
{
public:
	int32                                         NodeWeight;                                        // 0x0240(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ForceNeighbours;                                   // 0x0244(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_245[0xB];                                      // 0x0245(0x000B)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SWGuidancePathComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SWGuidancePathComponent")
	}
	static class USWGuidancePathComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<USWGuidancePathComponent>();
	}
};
DUMPER7_ASSERTS_USWGuidancePathComponent;

// Class SpicewoodGuidance.SWGuidanceSubsystem
// 0x00C0 (0x0100 - 0x0040)
class alignas(0x10) USWGuidanceSubsystem final : public UTickableWorldSubsystem
{
public:
	uint8                                         Pad_40[0xB0];                                      // 0x0040(0x00B0)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class USWGuidanceNetwork*>             Networks;                                          // 0x00F0(0x0010)(ZeroConstructor, NativeAccessSpecifierPrivate)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SWGuidanceSubsystem")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SWGuidanceSubsystem")
	}
	static class USWGuidanceSubsystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<USWGuidanceSubsystem>();
	}
};
DUMPER7_ASSERTS_USWGuidanceSubsystem;

SDK_NAMESPACE_END
