#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Style_EnchantmentLevelIndicator

#include "Basic.hpp"

#include "SpicewoodUI_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Style_EnchantmentLevelIndicator.Style_EnchantmentLevelIndicator_C
// 0x0000 (0x01A0 - 0x01A0)
class UStyle_EnchantmentLevelIndicator_C final : public USpicewoodTextStyle
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Style_EnchantmentLevelIndicator_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Style_EnchantmentLevelIndicator_C")
	}
	static class UStyle_EnchantmentLevelIndicator_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UStyle_EnchantmentLevelIndicator_C>();
	}
};
DUMPER7_ASSERTS_UStyle_EnchantmentLevelIndicator_C;

SDK_NAMESPACE_END
