#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SubtleFlashCameraShake

#include "Basic.hpp"

#include "EngineCameras_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass SubtleFlashCameraShake.SubtleFlashCameraShake_C
// 0x0000 (0x01F0 - 0x01F0)
class USubtleFlashCameraShake_C final : public ULegacyCameraShake
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SubtleFlashCameraShake_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SubtleFlashCameraShake_C")
	}
	static class USubtleFlashCameraShake_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USubtleFlashCameraShake_C>();
	}
};
DUMPER7_ASSERTS_USubtleFlashCameraShake_C;

SDK_NAMESPACE_END
