#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SW_mini_inv_previous_item_button_ButtonSoundStyle2

#include "Basic.hpp"

#include "SpicewoodUI_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass SW_mini_inv_previous_item_button-ButtonSoundStyle2.SW_mini_inv_previous_item_button-ButtonSoundStyle2_C
// 0x0000 (0x00E8 - 0x00E8)
class USW_mini_inv_previous_item_button_ButtonSoundStyle2_C final : public USpicewoodButtonSoundStyle
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SW_mini_inv_previous_item_button-ButtonSoundStyle2_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SW_mini_inv_previous_item_button-ButtonSoundStyle2_C")
	}
	static class USW_mini_inv_previous_item_button_ButtonSoundStyle2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USW_mini_inv_previous_item_button_ButtonSoundStyle2_C>();
	}
};
DUMPER7_ASSERTS_USW_mini_inv_previous_item_button_ButtonSoundStyle2_C;

SDK_NAMESPACE_END
