#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SWCoreLocalCoop

#include "Basic.hpp"

#include "SWCoreLocalCoop_classes.hpp"
#include "SWCoreLocalCoop_parameters.hpp"


SDK_NAMESPACE_START

// Function SWCoreLocalCoop.AuthClientGameStatesSubsystem.OnLogin
// (Final, Native, Protected)
// Parameters:
// class AGameModeBase*                    GameMode                                               (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class APlayerController*                NewPlayer                                              (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UAuthClientGameStatesSubsystem::OnLogin(class AGameModeBase* GameMode, class APlayerController* NewPlayer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AuthClientGameStatesSubsystem", "OnLogin");

	Params::AuthClientGameStatesSubsystem_OnLogin Parms{};

	Parms.GameMode = GameMode;
	Parms.NewPlayer = NewPlayer;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function SWCoreLocalCoop.AuthClientGameStatesSubsystem.OnLogout
// (Final, Native, Protected)
// Parameters:
// class AGameModeBase*                    GameMode                                               (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class AController*                      LeavingPlayer                                          (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UAuthClientGameStatesSubsystem::OnLogout(class AGameModeBase* GameMode, class AController* LeavingPlayer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AuthClientGameStatesSubsystem", "OnLogout");

	Params::AuthClientGameStatesSubsystem_OnLogout Parms{};

	Parms.GameMode = GameMode;
	Parms.LeavingPlayer = LeavingPlayer;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


SDK_NAMESPACE_END
