#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SWCoreOnline

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START

// Enum SWCoreOnline.EErrorCode
// NumValues: 0x0032
enum class EErrorCode : uint8
{
	ORPHANED_GUEST                           = 100,
	NOT_MEMBER                               = 101,
	INVALID_MEMBER_TYPE                      = 102,
	TOO_MANY_PLAYERS                         = 103,
	PARTY_NOT_FOUND                          = 104,
	INVITE_CODE_NOT_FOUND                    = 105,
	HAS_PARTY_ALREADY                        = 106,
	PARTY_IS_FULL                            = 107,
	PARTY_WILL_BE_FULL                       = 108,
	NOT_OWNER_OF_PARTY                       = 109,
	MEMBER_CANNOT_BE_OWNER                   = 110,
	MEMBER_NOT_ANONYMOUS                     = 111,
	CANNOT_KICK_OWNER                        = 112,
	GAME_SESSION_ATTACHED                    = 113,
	NOT_ALLOWED_TO_JOIN                      = 114,
	WRONG_STATUS_IN_PARTY                    = 115,
	NOT_ALLOWED_TO_REMOVE_MEMBER             = 116,
	INTERNAL                                 = 117,
	INVALID_STATE                            = 118,
	HOST_MEMBER_NOT_FOUND                    = 119,
	PROFILE_NOT_FOUND                        = 120,
	NOT_HOST                                 = 121,
	ALREADY_MEMBER                           = 122,
	INVALID_PARTY_CODE                       = 123,
	BLOCKED                                  = 124,
	HAS_MATCH_MAKE_REQUEST_ALREADY           = 125,
	WRONG_NAMESPACE                          = 126,
	COULD_NOT_START_GAME_SERVER              = 127,
	WRONG_CLIENT_VERSION                     = 128,
	CHARACTER_LIMIT_REACHED                  = 129,
	CHARACTER_NOT_FOUND                      = 130,
	RESOURCE_ALREADY_EXISTS                  = 131,
	WRONG_CLIENT_BUILD_NUMBER                = 132,
	NOT_CHARACTER_OWNER                      = 133,
	CHARACTER_HAS_WRONG_PLAYER_TYPE          = 134,
	NOT_ALLOWED_ON_PLATFORM                  = 135,
	CHARACTER_HAS_WRONG_TYPE                 = 136,
	PARTY_CHARACTER_NOT_UNIQUE               = 137,
	MEMBER_NOT_FOUND                         = 138,
	CHARACTER_IS_NOT_PRIMARY                 = 139,
	WRONG_CLIENT_PROTOCOL_VERSION            = 140,
	FAILED_TO_CREATE_PARTY                   = 141,
	MISSING_REQUIRED_MULTIPLAYER_PRIVILEGES  = 142,
	PARTY_LOCKED                             = 143,
	CROSS_PLAY_PRIVILEGE_VIOLATED            = 144,
	MATCHMAKING_REQUEST_PARTIES_CHANGED      = 145,
	PARTY_MISSING_REQUIRED_MULTIPLAYER_PRIVILEGES = 146,
	PARTY_CROSS_PLAY_PRIVILEGE_VIOLATED      = 147,
	REQUEST_NOT_SENT_NO_INTERNET             = 148,
	EErrorCode_MAX                           = 149,
};

// Enum SWCoreOnline.EErrorCategory
// NumValues: 0x0006
enum class EErrorCategory : uint8
{
	INVALID_DATA                             = 1,
	INVALID_REQUEST                          = 2,
	FORBIDDEN                                = 3,
	INTERNAL                                 = 4,
	REQUEST_NOT_SENT                         = 5,
	EErrorCategory_MAX                       = 6,
};

// Enum SWCoreOnline.ESocialGraph
// NumValues: 0x0005
enum class ESocialGraph : uint8
{
	XBOX                                     = 0,
	PLAYSTATION                              = 1,
	SWITCH                                   = 2,
	STEAM                                    = 3,
	ESocialGraph_MAX                         = 4,
};

// Enum SWCoreOnline.EGameMode
// NumValues: 0x0003
enum class EGameMode : uint8
{
	Online                                   = 0,
	Offline                                  = 1,
	EGameMode_MAX                            = 2,
};

// Enum SWCoreOnline.ESpicewoodPartyType
// NumValues: 0x0005
enum class ESpicewoodPartyType : uint8
{
	PUBLIC                                   = 0,
	FRIENDS                                  = 1,
	PRIVATE                                  = 2,
	LOCKED                                   = 3,
	ESpicewoodPartyType_MAX                  = 4,
};

// Enum SWCoreOnline.EPartyMethod
// NumValues: 0x000A
enum class EPartyMethod : uint8
{
	PARTYCODE                                = 0,
	HOTJOIN                                  = 1,
	INVITE                                   = 2,
	MATCHMAKE                                = 3,
	LOCALCOOP                                = 4,
	LEAVE                                    = 5,
	KICKED                                   = 6,
	FAILED                                   = 7,
	INACTIVITY                               = 8,
	EPartyMethod_MAX                         = 9,
};

// Enum SWCoreOnline.ECharacterType
// NumValues: 0x0003
enum class ECharacterType : uint8
{
	ONLINE                                   = 0,
	OFFLINE                                  = 1,
	ECharacterType_MAX                       = 2,
};

// Enum SWCoreOnline.EPlayerType
// NumValues: 0x0003
enum class EPlayerType : uint8
{
	PLAYER                                   = 0,
	GUEST                                    = 1,
	EPlayerType_MAX                          = 2,
};

// ScriptStruct SWCoreOnline.NetId
// 0x0018 (0x0018 - 0x0000)
struct FNetId final
{
public:
	class FString                                 ID;                                                // 0x0000(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   Type;                                              // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FNetId;

// ScriptStruct SWCoreOnline.SWPartyMember
// 0x00B8 (0x00B8 - 0x0000)
struct FSWPartyMember final
{
public:
	struct FNetId                                 NetId;                                             // 0x0000(0x0018)(NativeAccessSpecifierPublic)
	class FString                                 PartyUserId;                                       // 0x0018(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         PartyPosition;                                     // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 GamerTag;                                          // 0x0030(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 PublisherGamerTag;                                 // 0x0040(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 MsaGamerTag;                                       // 0x0050(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FPlatformUserId                        PlatformUserId;                                    // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_64[0x14];                                      // 0x0064(0x0014)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CharacterId;                                       // 0x0078(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 SkinId;                                            // 0x0088(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsLeader;                                          // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsCouchCoopPlayer;                                 // 0x0099(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9A[0x6];                                       // 0x009A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 PlatformId;                                        // 0x00A0(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TOptional<ESocialGraph>                       PLATFORM;                                          // 0x00B0(0x0002)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_B2[0x6];                                       // 0x00B2(0x0006)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FSWPartyMember;

// ScriptStruct SWCoreOnline.PartyInfo
// 0x0038 (0x0038 - 0x0000)
struct FPartyInfo final
{
public:
	class FString                                 Code;                                              // 0x0000(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	ESpicewoodPartyType                           Type;                                              // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FSWPartyMember>                 Members;                                           // 0x0018(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
	TWeakObjectPtr<class UWorld>                  WorldContext;                                      // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          HasPlatformOnlinePrivileges;                       // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsCrossplay;                                       // 0x0031(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_32[0x6];                                       // 0x0032(0x0006)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FPartyInfo;

// ScriptStruct SWCoreOnline.LoadoutPayload
// 0x0020 (0x0020 - 0x0000)
struct alignas(0x08) FLoadoutPayload final
{
public:
	uint8                                         Pad_0[0x20];                                       // 0x0000(0x0020)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FLoadoutPayload;

// ScriptStruct SWCoreOnline.ServerLoadoutPayload
// 0x0018 (0x0018 - 0x0000)
struct FServerLoadoutPayload final
{
public:
	class APlayerController*                      PlayerController;                                  // 0x0000(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, TObjectPtr)
	uint8                                         Pad_8[0x10];                                       // 0x0008(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FServerLoadoutPayload;

// ScriptStruct SWCoreOnline.ClientLoadoutPayload
// 0x0020 (0x0020 - 0x0000)
struct FClientLoadoutPayload final
{
public:
	class FString                                 CharacterId;                                       // 0x0000(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FLoadoutPayload>                Loadout;                                           // 0x0010(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FClientLoadoutPayload;

SDK_NAMESPACE_END
