#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SWCoreCommon

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function SWCoreCommon.EnvironmentUtil.IsAccountLinkablePlatform
// 0x0001 (0x0001 - 0x0000)
struct EnvironmentUtil_IsAccountLinkablePlatform final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_EnvironmentUtil_IsAccountLinkablePlatform;

// Function SWCoreCommon.EnvironmentUtil.IsAutomationTestRunning
// 0x0001 (0x0001 - 0x0000)
struct EnvironmentUtil_IsAutomationTestRunning final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_EnvironmentUtil_IsAutomationTestRunning;

// Function SWCoreCommon.EnvironmentUtil.IsDedicatedServer
// 0x0010 (0x0010 - 0x0000)
struct EnvironmentUtil_IsDedicatedServer final
{
public:
	const class UObject*                          WorldContextObject;                                // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_EnvironmentUtil_IsDedicatedServer;

// Function SWCoreCommon.EnvironmentUtil.IsDedicatedServerNoWorld
// 0x0001 (0x0001 - 0x0000)
struct EnvironmentUtil_IsDedicatedServerNoWorld final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_EnvironmentUtil_IsDedicatedServerNoWorld;

// Function SWCoreCommon.EnvironmentUtil.IsRunningAutoCreateUser
// 0x0001 (0x0001 - 0x0000)
struct EnvironmentUtil_IsRunningAutoCreateUser final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_EnvironmentUtil_IsRunningAutoCreateUser;

// Function SWCoreCommon.SWGameplayTagsCore.GetGameplayTagChecked
// 0x0010 (0x0010 - 0x0000)
struct SWGameplayTagsCore_GetGameplayTagChecked final
{
public:
	struct FGameplayTag                           Value;                                             // 0x0000(0x0008)(Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           ReturnValue;                                       // 0x0008(0x0008)(Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SWGameplayTagsCore_GetGameplayTagChecked;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
