#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SWTargetController

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"


SDK_NAMESPACE_START

// Enum SWTargetController.EMouseCursorStates
// NumValues: 0x000B
enum class EMouseCursorStates : uint8
{
	UNSET                                    = 0,
	Move                                     = 1,
	MoveHeld                                 = 2,
	Attack                                   = 3,
	AttackHeld                               = 4,
	Interact                                 = 5,
	InteractHeld                             = 6,
	Drag                                     = 7,
	DragHeld                                 = 8,
	Invisible                                = 9,
	EMouseCursorStates_MAX                   = 10,
};

// ScriptStruct SWTargetController.HighlightPlayerData
// 0x0060 (0x0060 - 0x0000)
struct FHighlightPlayerData final
{
public:
	class APawn*                                  PlayerPawn;                                        // 0x0000(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, TObjectPtr)
	uint8                                         Pad_8[0x8];                                        // 0x0008(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<struct FGameplayTag, class AActor*>      Targets;                                           // 0x0010(0x0050)(UObjectWrapper, NativeAccessSpecifierPublic, TObjectPtr)
};
DUMPER7_ASSERTS_FHighlightPlayerData;

SDK_NAMESPACE_END
