#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TextToSpeech

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function TextToSpeech.TextToSpeechEngineSubsystem.ActivateChannel
// 0x0008 (0x0008 - 0x0000)
struct TextToSpeechEngineSubsystem_ActivateChannel final
{
public:
	class FName                                   InChannelId;                                       // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_TextToSpeechEngineSubsystem_ActivateChannel;

// Function TextToSpeech.TextToSpeechEngineSubsystem.AddCustomChannel
// 0x0008 (0x0008 - 0x0000)
struct TextToSpeechEngineSubsystem_AddCustomChannel final
{
public:
	class FName                                   InNewChannelId;                                    // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_TextToSpeechEngineSubsystem_AddCustomChannel;

// Function TextToSpeech.TextToSpeechEngineSubsystem.AddDefaultChannel
// 0x0008 (0x0008 - 0x0000)
struct TextToSpeechEngineSubsystem_AddDefaultChannel final
{
public:
	class FName                                   InNewChannelId;                                    // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_TextToSpeechEngineSubsystem_AddDefaultChannel;

// Function TextToSpeech.TextToSpeechEngineSubsystem.DeactivateChannel
// 0x0008 (0x0008 - 0x0000)
struct TextToSpeechEngineSubsystem_DeactivateChannel final
{
public:
	class FName                                   InChannelId;                                       // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_TextToSpeechEngineSubsystem_DeactivateChannel;

// Function TextToSpeech.TextToSpeechEngineSubsystem.GetVolumeOnChannel
// 0x000C (0x000C - 0x0000)
struct TextToSpeechEngineSubsystem_GetVolumeOnChannel final
{
public:
	class FName                                   InChannelId;                                       // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ReturnValue;                                       // 0x0008(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_TextToSpeechEngineSubsystem_GetVolumeOnChannel;

// Function TextToSpeech.TextToSpeechEngineSubsystem.MuteChannel
// 0x0008 (0x0008 - 0x0000)
struct TextToSpeechEngineSubsystem_MuteChannel final
{
public:
	class FName                                   InChannelId;                                       // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_TextToSpeechEngineSubsystem_MuteChannel;

// Function TextToSpeech.TextToSpeechEngineSubsystem.RemoveChannel
// 0x0008 (0x0008 - 0x0000)
struct TextToSpeechEngineSubsystem_RemoveChannel final
{
public:
	class FName                                   InChannelId;                                       // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_TextToSpeechEngineSubsystem_RemoveChannel;

// Function TextToSpeech.TextToSpeechEngineSubsystem.SetRateOnChannel
// 0x000C (0x000C - 0x0000)
struct TextToSpeechEngineSubsystem_SetRateOnChannel final
{
public:
	class FName                                   InChannelId;                                       // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         InRate;                                            // 0x0008(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_TextToSpeechEngineSubsystem_SetRateOnChannel;

// Function TextToSpeech.TextToSpeechEngineSubsystem.SetVolumeOnChannel
// 0x000C (0x000C - 0x0000)
struct TextToSpeechEngineSubsystem_SetVolumeOnChannel final
{
public:
	class FName                                   InChannelId;                                       // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         InVolume;                                          // 0x0008(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_TextToSpeechEngineSubsystem_SetVolumeOnChannel;

// Function TextToSpeech.TextToSpeechEngineSubsystem.SpeakOnChannel
// 0x0018 (0x0018 - 0x0000)
struct TextToSpeechEngineSubsystem_SpeakOnChannel final
{
public:
	class FName                                   InChannelId;                                       // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 InStringToSpeak;                                   // 0x0008(0x0010)(Parm, OutParm, ZeroConstructor, ReferenceParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_TextToSpeechEngineSubsystem_SpeakOnChannel;

// Function TextToSpeech.TextToSpeechEngineSubsystem.StopSpeakingOnChannel
// 0x0008 (0x0008 - 0x0000)
struct TextToSpeechEngineSubsystem_StopSpeakingOnChannel final
{
public:
	class FName                                   InChannelId;                                       // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_TextToSpeechEngineSubsystem_StopSpeakingOnChannel;

// Function TextToSpeech.TextToSpeechEngineSubsystem.UnmuteChannel
// 0x0008 (0x0008 - 0x0000)
struct TextToSpeechEngineSubsystem_UnmuteChannel final
{
public:
	class FName                                   InChannelId;                                       // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_TextToSpeechEngineSubsystem_UnmuteChannel;

// Function TextToSpeech.TextToSpeechEngineSubsystem.DoesChannelExist
// 0x000C (0x000C - 0x0000)
struct TextToSpeechEngineSubsystem_DoesChannelExist final
{
public:
	class FName                                   InChannelId;                                       // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_TextToSpeechEngineSubsystem_DoesChannelExist;

// Function TextToSpeech.TextToSpeechEngineSubsystem.GetNumChannels
// 0x0004 (0x0004 - 0x0000)
struct TextToSpeechEngineSubsystem_GetNumChannels final
{
public:
	int32                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_TextToSpeechEngineSubsystem_GetNumChannels;

// Function TextToSpeech.TextToSpeechEngineSubsystem.GetRateOnChannel
// 0x000C (0x000C - 0x0000)
struct TextToSpeechEngineSubsystem_GetRateOnChannel final
{
public:
	class FName                                   InChannelId;                                       // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ReturnValue;                                       // 0x0008(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_TextToSpeechEngineSubsystem_GetRateOnChannel;

// Function TextToSpeech.TextToSpeechEngineSubsystem.IsChannelActive
// 0x000C (0x000C - 0x0000)
struct TextToSpeechEngineSubsystem_IsChannelActive final
{
public:
	class FName                                   InChannelId;                                       // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_TextToSpeechEngineSubsystem_IsChannelActive;

// Function TextToSpeech.TextToSpeechEngineSubsystem.IsChannelMuted
// 0x000C (0x000C - 0x0000)
struct TextToSpeechEngineSubsystem_IsChannelMuted final
{
public:
	class FName                                   InChannelId;                                       // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_TextToSpeechEngineSubsystem_IsChannelMuted;

// Function TextToSpeech.TextToSpeechEngineSubsystem.IsSpeakingOnChannel
// 0x000C (0x000C - 0x0000)
struct TextToSpeechEngineSubsystem_IsSpeakingOnChannel final
{
public:
	class FName                                   InChannelId;                                       // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_TextToSpeechEngineSubsystem_IsSpeakingOnChannel;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
