#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UIExtension

#include "Basic.hpp"

#include "UIExtension_classes.hpp"
#include "UIExtension_parameters.hpp"


SDK_NAMESPACE_START

// Function UIExtension.UIExtensionSubsystem.K2_RegisterExtensionAsData
// (Final, RequiredAPI, BlueprintCosmetic, Native, Protected, BlueprintCallable)
// Parameters:
// const struct FGameplayTag&              ExtensionPointTag                                      (Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UObject*                          Data                                                   (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   Priority                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FUIExtensionHandle               ReturnValue                                            (Parm, OutParm, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

struct FUIExtensionHandle UUIExtensionSubsystem::K2_RegisterExtensionAsData(const struct FGameplayTag& ExtensionPointTag, class UObject* Data, int32 Priority)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIExtensionSubsystem", "K2_RegisterExtensionAsData");

	Params::UIExtensionSubsystem_K2_RegisterExtensionAsData Parms{};

	Parms.ExtensionPointTag = std::move(ExtensionPointTag);
	Parms.Data = Data;
	Parms.Priority = Priority;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UIExtension.UIExtensionSubsystem.K2_RegisterExtensionAsDataForContext
// (Final, RequiredAPI, BlueprintCosmetic, Native, Protected, BlueprintCallable)
// Parameters:
// const struct FGameplayTag&              ExtensionPointTag                                      (Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UObject*                          ContextObject                                          (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UObject*                          Data                                                   (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   Priority                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FUIExtensionHandle               ReturnValue                                            (Parm, OutParm, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

struct FUIExtensionHandle UUIExtensionSubsystem::K2_RegisterExtensionAsDataForContext(const struct FGameplayTag& ExtensionPointTag, class UObject* ContextObject, class UObject* Data, int32 Priority)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIExtensionSubsystem", "K2_RegisterExtensionAsDataForContext");

	Params::UIExtensionSubsystem_K2_RegisterExtensionAsDataForContext Parms{};

	Parms.ExtensionPointTag = std::move(ExtensionPointTag);
	Parms.ContextObject = ContextObject;
	Parms.Data = Data;
	Parms.Priority = Priority;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UIExtension.UIExtensionSubsystem.K2_RegisterExtensionAsWidget
// (Final, RequiredAPI, BlueprintCosmetic, Native, Protected, BlueprintCallable)
// Parameters:
// const struct FGameplayTag&              ExtensionPointTag                                      (Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// TSubclassOf<class UUserWidget>          WidgetClass                                            (Parm, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   Priority                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FUIExtensionHandle               ReturnValue                                            (Parm, OutParm, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

struct FUIExtensionHandle UUIExtensionSubsystem::K2_RegisterExtensionAsWidget(const struct FGameplayTag& ExtensionPointTag, TSubclassOf<class UUserWidget> WidgetClass, int32 Priority)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIExtensionSubsystem", "K2_RegisterExtensionAsWidget");

	Params::UIExtensionSubsystem_K2_RegisterExtensionAsWidget Parms{};

	Parms.ExtensionPointTag = std::move(ExtensionPointTag);
	Parms.WidgetClass = WidgetClass;
	Parms.Priority = Priority;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UIExtension.UIExtensionSubsystem.K2_RegisterExtensionAsWidgetForContext
// (Final, RequiredAPI, BlueprintCosmetic, Native, Protected, BlueprintCallable)
// Parameters:
// const struct FGameplayTag&              ExtensionPointTag                                      (Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// TSubclassOf<class UUserWidget>          WidgetClass                                            (Parm, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UObject*                          ContextObject                                          (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   Priority                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FUIExtensionHandle               ReturnValue                                            (Parm, OutParm, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

struct FUIExtensionHandle UUIExtensionSubsystem::K2_RegisterExtensionAsWidgetForContext(const struct FGameplayTag& ExtensionPointTag, TSubclassOf<class UUserWidget> WidgetClass, class UObject* ContextObject, int32 Priority)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIExtensionSubsystem", "K2_RegisterExtensionAsWidgetForContext");

	Params::UIExtensionSubsystem_K2_RegisterExtensionAsWidgetForContext Parms{};

	Parms.ExtensionPointTag = std::move(ExtensionPointTag);
	Parms.WidgetClass = WidgetClass;
	Parms.ContextObject = ContextObject;
	Parms.Priority = Priority;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UIExtension.UIExtensionSubsystem.K2_RegisterExtensionPoint
// (Final, RequiredAPI, BlueprintCosmetic, Native, Protected, HasOutParams, BlueprintCallable)
// Parameters:
// const struct FGameplayTag&              ExtensionPointTag                                      (Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// EUIExtensionPointMatch                  ExtensionPointTagMatchType                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const TArray<class UClass*>&            AllowedDataClasses                                     (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
// TDelegate<void(EUIExtensionAction Action, const struct FUIExtensionRequest& ExtensionRequest)>ExtensionCallback                                      (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FUIExtensionPointHandle          ReturnValue                                            (Parm, OutParm, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

struct FUIExtensionPointHandle UUIExtensionSubsystem::K2_RegisterExtensionPoint(const struct FGameplayTag& ExtensionPointTag, EUIExtensionPointMatch ExtensionPointTagMatchType, const TArray<class UClass*>& AllowedDataClasses, TDelegate<void(EUIExtensionAction Action, const struct FUIExtensionRequest& ExtensionRequest)> ExtensionCallback)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIExtensionSubsystem", "K2_RegisterExtensionPoint");

	Params::UIExtensionSubsystem_K2_RegisterExtensionPoint Parms{};

	Parms.ExtensionPointTag = std::move(ExtensionPointTag);
	Parms.ExtensionPointTagMatchType = ExtensionPointTagMatchType;
	Parms.AllowedDataClasses = std::move(AllowedDataClasses);
	Parms.ExtensionCallback = ExtensionCallback;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UIExtension.UIExtensionSubsystem.UnregisterExtension
// (Final, RequiredAPI, BlueprintCosmetic, Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// const struct FUIExtensionHandle&        ExtensionHandle                                        (ConstParm, Parm, OutParm, ReferenceParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUIExtensionSubsystem::UnregisterExtension(const struct FUIExtensionHandle& ExtensionHandle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIExtensionSubsystem", "UnregisterExtension");

	Params::UIExtensionSubsystem_UnregisterExtension Parms{};

	Parms.ExtensionHandle = std::move(ExtensionHandle);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function UIExtension.UIExtensionSubsystem.UnregisterExtensionPoint
// (Final, RequiredAPI, BlueprintCosmetic, Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// const struct FUIExtensionPointHandle&   ExtensionPointHandle                                   (ConstParm, Parm, OutParm, ReferenceParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUIExtensionSubsystem::UnregisterExtensionPoint(const struct FUIExtensionPointHandle& ExtensionPointHandle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIExtensionSubsystem", "UnregisterExtensionPoint");

	Params::UIExtensionSubsystem_UnregisterExtensionPoint Parms{};

	Parms.ExtensionPointHandle = std::move(ExtensionPointHandle);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function UIExtension.UIExtensionSubsystem.DEBUGONLY_GetExtensionPoints
// (Final, RequiredAPI, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// TArray<struct FGameplayTag>             ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)

TArray<struct FGameplayTag> UUIExtensionSubsystem::DEBUGONLY_GetExtensionPoints() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIExtensionSubsystem", "DEBUGONLY_GetExtensionPoints");

	Params::UIExtensionSubsystem_DEBUGONLY_GetExtensionPoints Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UIExtension.UIExtensionSubsystem.DEBUGONLY_GetExtensions
// (Final, RequiredAPI, Native, Public, HasOutParams, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// const struct FGameplayTag&              ExtensionPointTag                                      (ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// TArray<class UUserWidget*>              ReturnValue                                            (ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, ContainsInstancedReference, NativeAccessSpecifierPublic)

TArray<class UUserWidget*> UUIExtensionSubsystem::DEBUGONLY_GetExtensions(const struct FGameplayTag& ExtensionPointTag) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIExtensionSubsystem", "DEBUGONLY_GetExtensions");

	Params::UIExtensionSubsystem_DEBUGONLY_GetExtensions Parms{};

	Parms.ExtensionPointTag = std::move(ExtensionPointTag);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UIExtension.UIExtensionSubsystem.GetWidgetFromHandle
// (Final, RequiredAPI, Native, Public, HasOutParams, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// const struct FUIExtensionHandle&        Handle                                                 (ConstParm, Parm, OutParm, ReferenceParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UUserWidget*                      ReturnValue                                            (ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UUserWidget* UUIExtensionSubsystem::GetWidgetFromHandle(const struct FUIExtensionHandle& Handle) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIExtensionSubsystem", "GetWidgetFromHandle");

	Params::UIExtensionSubsystem_GetWidgetFromHandle Parms{};

	Parms.Handle = std::move(Handle);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UIExtension.UIExtensionHandleFunctions.IsValid
// (Final, RequiredAPI, BlueprintCosmetic, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct FUIExtensionHandle&              Handle                                                 (Parm, OutParm, ReferenceParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UUIExtensionHandleFunctions::IsValid(struct FUIExtensionHandle& Handle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("UIExtensionHandleFunctions", "IsValid");

	Params::UIExtensionHandleFunctions_IsValid Parms{};

	Parms.Handle = std::move(Handle);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	Handle = std::move(Parms.Handle);

	return Parms.ReturnValue;
}


// Function UIExtension.UIExtensionHandleFunctions.Unregister
// (Final, RequiredAPI, BlueprintCosmetic, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct FUIExtensionHandle&              Handle                                                 (Parm, OutParm, ReferenceParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUIExtensionHandleFunctions::Unregister(struct FUIExtensionHandle& Handle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("UIExtensionHandleFunctions", "Unregister");

	Params::UIExtensionHandleFunctions_Unregister Parms{};

	Parms.Handle = std::move(Handle);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	Handle = std::move(Parms.Handle);
}


// Function UIExtension.UIExtensionPointHandleFunctions.IsValid
// (Final, RequiredAPI, BlueprintCosmetic, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct FUIExtensionPointHandle&         Handle                                                 (Parm, OutParm, ReferenceParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UUIExtensionPointHandleFunctions::IsValid(struct FUIExtensionPointHandle& Handle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("UIExtensionPointHandleFunctions", "IsValid");

	Params::UIExtensionPointHandleFunctions_IsValid Parms{};

	Parms.Handle = std::move(Handle);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	Handle = std::move(Parms.Handle);

	return Parms.ReturnValue;
}


// Function UIExtension.UIExtensionPointHandleFunctions.Unregister
// (Final, RequiredAPI, BlueprintCosmetic, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct FUIExtensionPointHandle&         Handle                                                 (Parm, OutParm, ReferenceParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUIExtensionPointHandleFunctions::Unregister(struct FUIExtensionPointHandle& Handle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("UIExtensionPointHandleFunctions", "Unregister");

	Params::UIExtensionPointHandleFunctions_Unregister Parms{};

	Parms.Handle = std::move(Handle);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	Handle = std::move(Parms.Handle);
}


SDK_NAMESPACE_END
