#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_ComparedMiniTooltip

#include "Basic.hpp"

#include "Angelscript_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass W_ComparedMiniTooltip.W_ComparedMiniTooltip_C
// 0x0000 (0x0520 - 0x0520)
class UW_ComparedMiniTooltip_C final : public UAS_SpicewoodComparedItemTooltip
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_ComparedMiniTooltip_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_ComparedMiniTooltip_C")
	}
	static class UW_ComparedMiniTooltip_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_ComparedMiniTooltip_C>();
	}
};
DUMPER7_ASSERTS_UW_ComparedMiniTooltip_C;

SDK_NAMESPACE_END
