#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_DefaultTextScrollStyle

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass W_DefaultTextScrollStyle.W_DefaultTextScrollStyle_C
// 0x0000 (0x0040 - 0x0040)
class UW_DefaultTextScrollStyle_C final : public UCommonTextScrollStyle
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_DefaultTextScrollStyle_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_DefaultTextScrollStyle_C")
	}
	static class UW_DefaultTextScrollStyle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_DefaultTextScrollStyle_C>();
	}
};
DUMPER7_ASSERTS_UW_DefaultTextScrollStyle_C;

SDK_NAMESPACE_END
