#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_MultiEquipSlot

#include "Basic.hpp"

#include "Angelscript_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass W_MultiEquipSlot.W_MultiEquipSlot_C
// 0x0020 (0x1710 - 0x16F0)
class UW_MultiEquipSlot_C final : public UAS_MultiEquipSlot
{
public:
	class UW_SlotModule_Power_C*                  Module_Power;                                      // 0x16F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_SlotModule_Locked_C*                 Module_Locked;                                     // 0x16F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_SlotModule_Favourite_C*              Module_Favourite;                                  // 0x1700(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_SlotModule_Enchanted_C*              Module_Enchanted;                                  // 0x1708(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_MultiEquipSlot_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_MultiEquipSlot_C")
	}
	static class UW_MultiEquipSlot_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_MultiEquipSlot_C>();
	}
};
DUMPER7_ASSERTS_UW_MultiEquipSlot_C;

SDK_NAMESPACE_END
