#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_PartyInfoDowned

#include "Basic.hpp"

#include "Angelscript_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass W_PartyInfoDowned.W_PartyInfoDowned_C
// 0x0010 (0x0540 - 0x0530)
class UW_PartyInfoDowned_C final : public UAS_PartyInfoDowned
{
public:
	class UAS_SpicewoodLazyImage*                 Skull;                                             // 0x0530(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Particles;                                         // 0x0538(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_PartyInfoDowned_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_PartyInfoDowned_C")
	}
	static class UW_PartyInfoDowned_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_PartyInfoDowned_C>();
	}
};
DUMPER7_ASSERTS_UW_PartyInfoDowned_C;

SDK_NAMESPACE_END
