#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_QuestTrackerIdle

#include "Basic.hpp"

#include "Angelscript_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass W_QuestTrackerIdle.W_QuestTrackerIdle_C
// 0x0020 (0x0550 - 0x0530)
class UW_QuestTrackerIdle_C final : public UAS_QuestTrackerIdle
{
public:
	class UAS_SpicewoodActionWidget*              SlotAction;                                        // 0x0530(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UAS_SpicewoodSafeZone*                  AS_SpicewoodSafeZone_Top;                          // 0x0538(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UAS_SpicewoodSafeZone*                  AS_SpicewoodSafeZone_Local;                        // 0x0540(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_QuestTrackerIdle_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_QuestTrackerIdle_C")
	}
	static class UW_QuestTrackerIdle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_QuestTrackerIdle_C>();
	}
};
DUMPER7_ASSERTS_UW_QuestTrackerIdle_C;

SDK_NAMESPACE_END
