#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_SlotModule_IsActive

#include "Basic.hpp"

#include "Angelscript_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass W_SlotModule_IsActive.W_SlotModule_IsActive_C
// 0x0010 (0x04B0 - 0x04A0)
class UW_SlotModule_IsActive_C final : public UAS_SlotModule_IsActive
{
public:
	class UAS_SpicewoodLazyImage*                 Overlay;                                           // 0x04A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_SlotModule_IsActive_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_SlotModule_IsActive_C")
	}
	static class UW_SlotModule_IsActive_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_SlotModule_IsActive_C>();
	}
};
DUMPER7_ASSERTS_UW_SlotModule_IsActive_C;

SDK_NAMESPACE_END
