#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_PlayerBase

#include "Basic.hpp"

#include "Engine_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function ABP_PlayerBase.ABP_PlayerBase_C.AnimGraph
// 0x0010 (0x0010 - 0x0000)
struct ABP_PlayerBase_C_AnimGraph final
{
public:
	struct FPoseLink                              AnimGraph_0;                                       // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};
DUMPER7_ASSERTS_ABP_PlayerBase_C_AnimGraph;

// Function ABP_PlayerBase.ABP_PlayerBase_C.BlueprintThreadSafeUpdateAnimation
// 0x0004 (0x0004 - 0x0000)
struct ABP_PlayerBase_C_BlueprintThreadSafeUpdateAnimation final
{
public:
	float                                         DeltaTime;                                         // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_ABP_PlayerBase_C_BlueprintThreadSafeUpdateAnimation;

// Function ABP_PlayerBase.ABP_PlayerBase_C.ExecuteUbergraph_ABP_PlayerBase
// 0x0028 (0x0028 - 0x0000)
struct ABP_PlayerBase_C_ExecuteUbergraph_ABP_PlayerBase final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue_1;                // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_ShouldTransitionToRun_ReturnValue;        // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0007(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_ShouldTransitionToRun_ReturnValue_1;      // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_DoubleDouble_ReturnValue;         // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue_1;                  // 0x000A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_ShouldTransitionToRun_ReturnValue_2;      // 0x000B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetRelevantAnimTime_ReturnValue;          // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_DoubleDouble_ReturnValue_1;       // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Greater_DoubleDouble_A_ImplicitCast;      // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Greater_DoubleDouble_A_ImplicitCast_1;    // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_ABP_PlayerBase_C_ExecuteUbergraph_ABP_PlayerBase;

// Function ABP_PlayerBase.ABP_PlayerBase_C.FullBody_FallLandState
// 0x0010 (0x0010 - 0x0000)
struct ABP_PlayerBase_C_FullBody_FallLandState final
{
public:
	struct FPoseLink                              FullBody_FallLandState_0;                          // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};
DUMPER7_ASSERTS_ABP_PlayerBase_C_FullBody_FallLandState;

// Function ABP_PlayerBase.ABP_PlayerBase_C.FullBody_FallLoopState
// 0x0010 (0x0010 - 0x0000)
struct ABP_PlayerBase_C_FullBody_FallLoopState final
{
public:
	struct FPoseLink                              FullBody_FallLoopState_0;                          // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};
DUMPER7_ASSERTS_ABP_PlayerBase_C_FullBody_FallLoopState;

// Function ABP_PlayerBase.ABP_PlayerBase_C.FullBody_IdleBreakState
// 0x0010 (0x0010 - 0x0000)
struct ABP_PlayerBase_C_FullBody_IdleBreakState final
{
public:
	struct FPoseLink                              FullBody_IdleBreakState_0;                         // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};
DUMPER7_ASSERTS_ABP_PlayerBase_C_FullBody_IdleBreakState;

// Function ABP_PlayerBase.ABP_PlayerBase_C.FullBody_IdleState
// 0x0010 (0x0010 - 0x0000)
struct ABP_PlayerBase_C_FullBody_IdleState final
{
public:
	struct FPoseLink                              FullBody_IdleState_0;                              // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};
DUMPER7_ASSERTS_ABP_PlayerBase_C_FullBody_IdleState;

// Function ABP_PlayerBase.ABP_PlayerBase_C.FullBody_JumpLandState
// 0x0010 (0x0010 - 0x0000)
struct ABP_PlayerBase_C_FullBody_JumpLandState final
{
public:
	struct FPoseLink                              FullBody_JumpLandState_0;                          // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};
DUMPER7_ASSERTS_ABP_PlayerBase_C_FullBody_JumpLandState;

// Function ABP_PlayerBase.ABP_PlayerBase_C.FullBody_JumpLoopState
// 0x0010 (0x0010 - 0x0000)
struct ABP_PlayerBase_C_FullBody_JumpLoopState final
{
public:
	struct FPoseLink                              FullBody_JumpLoopState_0;                          // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};
DUMPER7_ASSERTS_ABP_PlayerBase_C_FullBody_JumpLoopState;

// Function ABP_PlayerBase.ABP_PlayerBase_C.FullBody_JumpStartState
// 0x0010 (0x0010 - 0x0000)
struct ABP_PlayerBase_C_FullBody_JumpStartState final
{
public:
	struct FPoseLink                              FullBody_JumpStartState_0;                         // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};
DUMPER7_ASSERTS_ABP_PlayerBase_C_FullBody_JumpStartState;

// Function ABP_PlayerBase.ABP_PlayerBase_C.FullBody_RespawnState
// 0x0010 (0x0010 - 0x0000)
struct ABP_PlayerBase_C_FullBody_RespawnState final
{
public:
	struct FPoseLink                              FullBody_RespawnState_0;                           // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};
DUMPER7_ASSERTS_ABP_PlayerBase_C_FullBody_RespawnState;

// Function ABP_PlayerBase.ABP_PlayerBase_C.FullBody_RunState
// 0x0010 (0x0010 - 0x0000)
struct ABP_PlayerBase_C_FullBody_RunState final
{
public:
	struct FPoseLink                              FullBody_RunState_0;                               // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};
DUMPER7_ASSERTS_ABP_PlayerBase_C_FullBody_RunState;

// Function ABP_PlayerBase.ABP_PlayerBase_C.ShouldTransitionToRun
// 0x0004 (0x0004 - 0x0000)
struct ABP_PlayerBase_C_ShouldTransitionToRun final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_ABP_PlayerBase_C_ShouldTransitionToRun;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
