#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_InteractiveGrassHandler

#include "Basic.hpp"

#include "BP_InteractiveGrassHandler_classes.hpp"
#include "BP_InteractiveGrassHandler_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_InteractiveGrassHandler.BP_InteractiveGrassHandler_C.Add to Render
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           TargetActor                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_InteractiveGrassHandler_C::Add_to_Render(class AActor* TargetActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InteractiveGrassHandler_C", "Add to Render");

	Params::BP_InteractiveGrassHandler_C_Add_to_Render Parms{};

	Parms.TargetActor = TargetActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_InteractiveGrassHandler.BP_InteractiveGrassHandler_C.ExecuteUbergraph_BP_InteractiveGrassHandler
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_InteractiveGrassHandler_C::ExecuteUbergraph_BP_InteractiveGrassHandler(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InteractiveGrassHandler_C", "ExecuteUbergraph_BP_InteractiveGrassHandler");

	Params::BP_InteractiveGrassHandler_C_ExecuteUbergraph_BP_InteractiveGrassHandler Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_InteractiveGrassHandler.BP_InteractiveGrassHandler_C.OnPlayerAddedOrRemoved_Event
// (BlueprintCallable, BlueprintEvent)

void ABP_InteractiveGrassHandler_C::OnPlayerAddedOrRemoved_Event()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InteractiveGrassHandler_C", "OnPlayerAddedOrRemoved_Event");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_InteractiveGrassHandler.BP_InteractiveGrassHandler_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_InteractiveGrassHandler_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InteractiveGrassHandler_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_InteractiveGrassHandler.BP_InteractiveGrassHandler_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_InteractiveGrassHandler_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InteractiveGrassHandler_C", "ReceiveTick");

	Params::BP_InteractiveGrassHandler_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_InteractiveGrassHandler.BP_InteractiveGrassHandler_C.UpdateArea
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_InteractiveGrassHandler_C::UpdateArea()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InteractiveGrassHandler_C", "UpdateArea");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_InteractiveGrassHandler.BP_InteractiveGrassHandler_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_InteractiveGrassHandler_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InteractiveGrassHandler_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
