#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Monstrosity_Sculk

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "MSAudioRuntime_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_Monstrosity_Sculk.BP_Monstrosity_Sculk_C.ExecuteUbergraph_BP_Monstrosity_Sculk
// 0x0090 (0x0090 - 0x0000)
struct BP_Monstrosity_Sculk_C_ExecuteUbergraph_BP_Monstrosity_Sculk final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(int32 PlayingID, EMSAudioCallbackType CallbackType)> Temp_delegate_Variable;      // 0x0004(0x0010)(ConstParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_PostEvent_ReturnValue;                    // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_18[0x8];                                       // 0x0018(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_GetTransform_ReturnValue;                 // 0x0020(0x0060)(ConstParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue; // 0x0080(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ABP_Monstrosity_Sculk_Death_C*          CallFunc_FinishSpawningActor_ReturnValue;          // 0x0088(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Monstrosity_Sculk_C_ExecuteUbergraph_BP_Monstrosity_Sculk;

// Function BP_Monstrosity_Sculk.BP_Monstrosity_Sculk_C.GetEffectScale
// 0x0018 (0x0018 - 0x0000)
struct BP_Monstrosity_Sculk_C_GetEffectScale final
{
public:
	struct FVector                                Size;                                              // 0x0000(0x0018)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Monstrosity_Sculk_C_GetEffectScale;

// Function BP_Monstrosity_Sculk.BP_Monstrosity_Sculk_C.GetParticleSize
// 0x0018 (0x0018 - 0x0000)
struct BP_Monstrosity_Sculk_C_GetParticleSize final
{
public:
	struct FVector                                ParticleSize;                                      // 0x0000(0x0018)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Monstrosity_Sculk_C_GetParticleSize;

// Function BP_Monstrosity_Sculk.BP_Monstrosity_Sculk_C.GetSpawn
// 0x0008 (0x0008 - 0x0000)
struct BP_Monstrosity_Sculk_C_GetSpawn final
{
public:
	double                                        Spawn;                                             // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Monstrosity_Sculk_C_GetSpawn;

// Function BP_Monstrosity_Sculk.BP_Monstrosity_Sculk_C.GetSpread
// 0x0008 (0x0008 - 0x0000)
struct BP_Monstrosity_Sculk_C_GetSpread final
{
public:
	double                                        Spread;                                            // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Monstrosity_Sculk_C_GetSpread;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
