#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Witch_Death

#include "Basic.hpp"

#include "BP_Witch_Death_classes.hpp"
#include "BP_Witch_Death_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_Witch_Death.BP_Witch_Death_C.ExecuteUbergraph_BP_Witch_Death
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Witch_Death_C::ExecuteUbergraph_BP_Witch_Death(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Witch_Death_C", "ExecuteUbergraph_BP_Witch_Death");

	Params::BP_Witch_Death_C_ExecuteUbergraph_BP_Witch_Death Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Witch_Death.BP_Witch_Death_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Witch_Death_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Witch_Death_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
