#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CameraOcclusion

#include "Basic.hpp"

#include "CameraOcclusion_classes.hpp"
#include "CameraOcclusion_parameters.hpp"


SDK_NAMESPACE_START

// Function CameraOcclusion.CameraOcclusionHandler.OnLocalPlayerAdded
// (Final, Native, Protected)
// Parameters:
// class ULocalPlayer*                     Player                                                 (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UCameraOcclusionHandler::OnLocalPlayerAdded(class ULocalPlayer* Player)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CameraOcclusionHandler", "OnLocalPlayerAdded");

	Params::CameraOcclusionHandler_OnLocalPlayerAdded Parms{};

	Parms.Player = Player;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function CameraOcclusion.CameraOcclusionHandler.OnLocalPlayerRemoved
// (Final, Native, Protected)
// Parameters:
// class ULocalPlayer*                     Player                                                 (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UCameraOcclusionHandler::OnLocalPlayerRemoved(class ULocalPlayer* Player)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CameraOcclusionHandler", "OnLocalPlayerRemoved");

	Params::CameraOcclusionHandler_OnLocalPlayerRemoved Parms{};

	Parms.Player = Player;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


SDK_NAMESPACE_END
