#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CollectionsStats

#include "Basic.hpp"

#include "NetCore_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "SWCoreGameplay_structs.hpp"


SDK_NAMESPACE_START

// ScriptStruct CollectionsStats.ShownHint
// 0x000C (0x000C - 0x0000)
struct FShownHint final
{
public:
	struct FGameplayTag                           Tag;                                               // 0x0000(0x0008)(NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Count;                                             // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FShownHint;

// ScriptStruct CollectionsStats.OnboardingData
// 0x0028 (0x0028 - 0x0000)
struct FOnboardingData final
{
public:
	TArray<struct FShownHint>                     ShownHints;                                        // 0x0000(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<struct FGameplayTag>                   SeenExpandableInfo;                                // 0x0010(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
	bool                                          IsOnboardingloaded;                                // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FOnboardingData;

// ScriptStruct CollectionsStats.CollectionsStatsEntry
// 0x00C4 (0x00D0 - 0x000C)
struct alignas(0x08) FCollectionsStatsEntry final : public FFastArraySerializerItem
{
public:
	struct FGameplayTag                           Category;                                          // 0x000C(0x0008)(BlueprintVisible, BlueprintReadOnly, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           SubCategory;                                       // 0x0014(0x0008)(BlueprintVisible, BlueprintReadOnly, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         MaxAvailable;                                      // 0x001C(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         collected;                                         // 0x0020(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_24[0xAC];                                      // 0x0024(0x00AC)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FCollectionsStatsEntry;

// ScriptStruct CollectionsStats.CollectionsStatsFastArray
// 0x0068 (0x0170 - 0x0108)
struct FCollectionsStatsFastArray final : public FFastArraySerializer
{
public:
	uint8                                         Pad_108[0x50];                                     // 0x0108(0x0050)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FCollectionsStatsEntry>         Entries;                                           // 0x0158(0x0010)(ZeroConstructor, NativeAccessSpecifierPrivate)
	uint8                                         Pad_168[0x8];                                      // 0x0168(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FCollectionsStatsFastArray;

// ScriptStruct CollectionsStats.ItemCollectionDefinition
// 0x0028 (0x0028 - 0x0000)
struct FItemCollectionDefinition final
{
public:
	struct FGameplayTagContainer                  ItemsInCollection;                                 // 0x0000(0x0020)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	struct FGameplayTag                           PanelToShow;                                       // 0x0020(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FItemCollectionDefinition;

// ScriptStruct CollectionsStats.ItemCollectionTableRow
// 0x00A0 (0x00A8 - 0x0008)
struct FItemCollectionTableRow final : public FSanitisedTableRow
{
public:
	struct FGameplayTag                           TypeTag;                                           // 0x0008(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTagContainer                  Traits;                                            // 0x0010(0x0020)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	struct FItemCollectionDefinition              CollectionDefinition;                              // 0x0030(0x0028)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	struct FTypeTextContainer                     TypeTextData;                                      // 0x0058(0x0050)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FItemCollectionTableRow;

SDK_NAMESPACE_END
