#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CutsceneSubsystem

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"


SDK_NAMESPACE_START

// Enum CutsceneSubsystem.ECutsceneEndReason
// NumValues: 0x0005
enum class ECutsceneEndReason : uint8
{
	Skipped                                  = 0,
	Finished                                 = 1,
	Failed                                   = 2,
	INVALID                                  = 3,
	ECutsceneEndReason_MAX                   = 4,
};

// ScriptStruct CutsceneSubsystem.CutsceneActionPlay
// 0x0030 (0x0030 - 0x0000)
struct FCutsceneActionPlay final
{
public:
	TSoftObjectPtr<class ULocalPlayer>            LocalPlayer;                                       // 0x0000(0x0028)(Edit, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           CutsceneTag;                                       // 0x0028(0x0008)(Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FCutsceneActionPlay;

// ScriptStruct CutsceneSubsystem.CutsceneEventConfig
// 0x000C (0x000C - 0x0000)
struct FCutsceneEventConfig final
{
public:
	struct FGameplayTag                           CutsceneTag;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	ECutsceneEndReason                            Reason;                                            // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FCutsceneEventConfig;

SDK_NAMESPACE_END
