#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Entitlements

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// Class Entitlements.DynamicEntitlementsHandlerSubsystem
// 0x0130 (0x0160 - 0x0030)
class UDynamicEntitlementsHandlerSubsystem final : public ULocalPlayerSubsystem
{
public:
	uint8                                         Pad_30[0x130];                                     // 0x0030(0x0130)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void SubmitCode(const class FString& Code);

	bool HasEntitlement(const class FString& EntitlementName) const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("DynamicEntitlementsHandlerSubsystem")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DynamicEntitlementsHandlerSubsystem")
	}
	static class UDynamicEntitlementsHandlerSubsystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDynamicEntitlementsHandlerSubsystem>();
	}
};
DUMPER7_ASSERTS_UDynamicEntitlementsHandlerSubsystem;

// Class Entitlements.EntitledCosmeticsFunctionLibrary
// 0x0000 (0x0028 - 0x0028)
class UEntitledCosmeticsFunctionLibrary final : public UBlueprintFunctionLibrary
{
public:
	static void GetAvailableCosmeticOfType(const class ULocalPlayer* LocalPlayer, const struct FGameplayTag& CosmeticType, TSet<struct FGameplayTag>* OutAvailableCosmeticTags);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("EntitledCosmeticsFunctionLibrary")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EntitledCosmeticsFunctionLibrary")
	}
	static class UEntitledCosmeticsFunctionLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEntitledCosmeticsFunctionLibrary>();
	}
};
DUMPER7_ASSERTS_UEntitledCosmeticsFunctionLibrary;

// Class Entitlements.EntitlementsTokenSaveGame
// 0x0010 (0x0038 - 0x0028)
class UEntitlementsTokenSaveGame final : public USaveGame
{
public:
	TArray<uint8>                                 ProtectedTokenBytes;                               // 0x0028(0x0010)(ZeroConstructor, SaveGame, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("EntitlementsTokenSaveGame")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EntitlementsTokenSaveGame")
	}
	static class UEntitlementsTokenSaveGame* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEntitlementsTokenSaveGame>();
	}
};
DUMPER7_ASSERTS_UEntitlementsTokenSaveGame;

// Class Entitlements.UpsellManagerSubsystem
// 0x0000 (0x0030 - 0x0030)
class UUpsellManagerSubsystem final : public ULocalPlayerSubsystem
{
public:
	bool ShowNativeUpsellUI(const class FString& StoreItem);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("UpsellManagerSubsystem")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UpsellManagerSubsystem")
	}
	static class UUpsellManagerSubsystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUpsellManagerSubsystem>();
	}
};
DUMPER7_ASSERTS_UUpsellManagerSubsystem;

SDK_NAMESPACE_END
