#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FriendSystem

#include "Basic.hpp"

#include "FriendSystem_classes.hpp"
#include "FriendSystem_parameters.hpp"


SDK_NAMESPACE_START

// Function FriendSystem.FriendsSubsystem.AddFriendByName
// (Final, Native, Public)
// Parameters:
// const class FString&                    Name_0                                                 (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// EFriendsAddResponse                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

EFriendsAddResponse UFriendsSubsystem::AddFriendByName(const class FString& Name_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FriendsSubsystem", "AddFriendByName");

	Params::FriendsSubsystem_AddFriendByName Parms{};

	Parms.Name_0 = std::move(Name_0);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function FriendSystem.FriendsSubsystem.BlockPlayer
// (Final, Native, Public, HasOutParams)
// Parameters:
// const struct FFriend&                   Player                                                 (ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)

void UFriendsSubsystem::BlockPlayer(const struct FFriend& Player)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FriendsSubsystem", "BlockPlayer");

	Params::FriendsSubsystem_BlockPlayer Parms{};

	Parms.Player = std::move(Player);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function FriendSystem.FriendsSubsystem.FetchFriends
// (Final, Native, Public)

void UFriendsSubsystem::FetchFriends()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FriendsSubsystem", "FetchFriends");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function FriendSystem.FriendsSubsystem.GetBlockedPlayers
// (Final, Native, Public)
// Parameters:
// TArray<struct FBlockedUser>             ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)

TArray<struct FBlockedUser> UFriendsSubsystem::GetBlockedPlayers()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FriendsSubsystem", "GetBlockedPlayers");

	Params::FriendsSubsystem_GetBlockedPlayers Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function FriendSystem.FriendsSubsystem.RemoveFriend
// (Final, Native, Public, HasOutParams)
// Parameters:
// const struct FFriend&                   Player                                                 (ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)

void UFriendsSubsystem::RemoveFriend(const struct FFriend& Player)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FriendsSubsystem", "RemoveFriend");

	Params::FriendsSubsystem_RemoveFriend Parms{};

	Parms.Player = std::move(Player);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function FriendSystem.FriendsSubsystem.FetchBlockedPlayers
// (Final, Native, Public, Const)

void UFriendsSubsystem::FetchBlockedPlayers() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FriendsSubsystem", "FetchBlockedPlayers");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function FriendSystem.FriendsSubsystem.GetFriends
// (Final, Native, Public, Const)
// Parameters:
// TArray<struct FFriend>                  ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)

TArray<struct FFriend> UFriendsSubsystem::GetFriends() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FriendsSubsystem", "GetFriends");

	Params::FriendsSubsystem_GetFriends Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function FriendSystem.FriendsSubsystem.UnblockPlayer
// (Final, Native, Public, Const)
// Parameters:
// const class FString&                    PlayerId                                               (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UFriendsSubsystem::UnblockPlayer(const class FString& PlayerId) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FriendsSubsystem", "UnblockPlayer");

	Params::FriendsSubsystem_UnblockPlayer Parms{};

	Parms.PlayerId = std::move(PlayerId);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


SDK_NAMESPACE_END
