#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCN_Satchel_Fire

#include "Basic.hpp"

#include "SpicewoodGAS_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GCN_Satchel_Fire.GCN_Satchel_Fire_C
// 0x0008 (0x0380 - 0x0378)
class AGCN_Satchel_Fire_C final : public AGCN_SpawnEffect
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0378(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GCN_Satchel_Fire_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GCN_Satchel_Fire_C")
	}
	static class AGCN_Satchel_Fire_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGCN_Satchel_Fire_C>();
	}
};
DUMPER7_ASSERTS_AGCN_Satchel_Fire_C;

SDK_NAMESPACE_END
