#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCN_Mob_Shield

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "GameplayAbilities_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GCN_Mob_Shield.GCN_Mob_Shield_C
// 0x0050 (0x0368 - 0x0318)
class AGCN_Mob_Shield_C : public AGameplayCueNotify_Actor
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0318(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class FName                                   ShieldSocket;                                      // 0x0320(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 Shield;                                            // 0x0328(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FVector                                Relative_Socket_Location;                          // 0x0330(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               Relative_Rotation;                                 // 0x0348(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	class UClass*                                 ShieldClass;                                       // 0x0360(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	bool OnActive(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	bool OnRemove(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GCN_Mob_Shield_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GCN_Mob_Shield_C")
	}
	static class AGCN_Mob_Shield_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGCN_Mob_Shield_C>();
	}
};
DUMPER7_ASSERTS_AGCN_Mob_Shield_C;

SDK_NAMESPACE_END
