#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCN_Mosstrosity_FlowerPuddle_Large

#include "Basic.hpp"

#include "GCN_Mosstrosity_FlowerPuddle_Large_classes.hpp"
#include "GCN_Mosstrosity_FlowerPuddle_Large_parameters.hpp"


SDK_NAMESPACE_START

// Function GCN_Mosstrosity_FlowerPuddle_Large.GCN_Mosstrosity_FlowerPuddle_Large_C.Execute Intro
// (BlueprintCallable, BlueprintEvent)

void AGCN_Mosstrosity_FlowerPuddle_Large_C::Execute_Intro()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GCN_Mosstrosity_FlowerPuddle_Large_C", "Execute Intro");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GCN_Mosstrosity_FlowerPuddle_Large.GCN_Mosstrosity_FlowerPuddle_Large_C.Execute Outro
// (BlueprintCallable, BlueprintEvent)

void AGCN_Mosstrosity_FlowerPuddle_Large_C::Execute_Outro()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GCN_Mosstrosity_FlowerPuddle_Large_C", "Execute Outro");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GCN_Mosstrosity_FlowerPuddle_Large.GCN_Mosstrosity_FlowerPuddle_Large_C.ExecuteUbergraph_GCN_Mosstrosity_FlowerPuddle_Large
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AGCN_Mosstrosity_FlowerPuddle_Large_C::ExecuteUbergraph_GCN_Mosstrosity_FlowerPuddle_Large(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GCN_Mosstrosity_FlowerPuddle_Large_C", "ExecuteUbergraph_GCN_Mosstrosity_FlowerPuddle_Large");

	Params::GCN_Mosstrosity_FlowerPuddle_Large_C_ExecuteUbergraph_GCN_Mosstrosity_FlowerPuddle_Large Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GCN_Mosstrosity_FlowerPuddle_Large.GCN_Mosstrosity_FlowerPuddle_Large_C.Intro__FinishedFunc
// (BlueprintEvent)

void AGCN_Mosstrosity_FlowerPuddle_Large_C::Intro__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GCN_Mosstrosity_FlowerPuddle_Large_C", "Intro__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GCN_Mosstrosity_FlowerPuddle_Large.GCN_Mosstrosity_FlowerPuddle_Large_C.Intro__UpdateFunc
// (BlueprintEvent)

void AGCN_Mosstrosity_FlowerPuddle_Large_C::Intro__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GCN_Mosstrosity_FlowerPuddle_Large_C", "Intro__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GCN_Mosstrosity_FlowerPuddle_Large.GCN_Mosstrosity_FlowerPuddle_Large_C.OnExecute
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           MyTarget                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayCueParameters&    Parameters                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool AGCN_Mosstrosity_FlowerPuddle_Large_C::OnExecute(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GCN_Mosstrosity_FlowerPuddle_Large_C", "OnExecute");

	Params::GCN_Mosstrosity_FlowerPuddle_Large_C_OnExecute Parms{};

	Parms.MyTarget = MyTarget;
	Parms.Parameters = std::move(Parameters);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function GCN_Mosstrosity_FlowerPuddle_Large.GCN_Mosstrosity_FlowerPuddle_Large_C.OnRemove
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           MyTarget                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayCueParameters&    Parameters                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool AGCN_Mosstrosity_FlowerPuddle_Large_C::OnRemove(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GCN_Mosstrosity_FlowerPuddle_Large_C", "OnRemove");

	Params::GCN_Mosstrosity_FlowerPuddle_Large_C_OnRemove Parms{};

	Parms.MyTarget = MyTarget;
	Parms.Parameters = std::move(Parameters);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function GCN_Mosstrosity_FlowerPuddle_Large.GCN_Mosstrosity_FlowerPuddle_Large_C.Outro__FinishedFunc
// (BlueprintEvent)

void AGCN_Mosstrosity_FlowerPuddle_Large_C::Outro__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GCN_Mosstrosity_FlowerPuddle_Large_C", "Outro__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GCN_Mosstrosity_FlowerPuddle_Large.GCN_Mosstrosity_FlowerPuddle_Large_C.Outro__UpdateFunc
// (BlueprintEvent)

void AGCN_Mosstrosity_FlowerPuddle_Large_C::Outro__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GCN_Mosstrosity_FlowerPuddle_Large_C", "Outro__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GCN_Mosstrosity_FlowerPuddle_Large.GCN_Mosstrosity_FlowerPuddle_Large_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AGCN_Mosstrosity_FlowerPuddle_Large_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GCN_Mosstrosity_FlowerPuddle_Large_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GCN_Mosstrosity_FlowerPuddle_Large.GCN_Mosstrosity_FlowerPuddle_Large_C.WhileActive
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           MyTarget                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayCueParameters&    Parameters                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool AGCN_Mosstrosity_FlowerPuddle_Large_C::WhileActive(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GCN_Mosstrosity_FlowerPuddle_Large_C", "WhileActive");

	Params::GCN_Mosstrosity_FlowerPuddle_Large_C_WhileActive Parms{};

	Parms.MyTarget = MyTarget;
	Parms.Parameters = std::move(Parameters);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
