#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCN_PotBreakBase

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GCN_PotBreakBase.GCN_PotBreakBase_C
// 0x0010 (0x0050 - 0x0040)
class UGCN_PotBreakBase_C : public UGameplayCueNotify_Static
{
public:
	class UAkAudioEvent*                          PotBreakSFX;                                       // 0x0040(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UNiagaraSystem*                         PotBreakVFX;                                       // 0x0048(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	bool OnExecute(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GCN_PotBreakBase_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GCN_PotBreakBase_C")
	}
	static class UGCN_PotBreakBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGCN_PotBreakBase_C>();
	}
};
DUMPER7_ASSERTS_UGCN_PotBreakBase_C;

SDK_NAMESPACE_END
