#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCN_SentinelEnrage

#include "Basic.hpp"

#include "SWCoreGAS_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GCN_SentinelEnrage.GCN_SentinelEnrage_C
// 0x0008 (0x0348 - 0x0340)
class AGCN_SentinelEnrage_C final : public ASWGameplayCueNotify_Actor
{
public:
	class UNiagaraComponent*                      NS_Enrage;                                         // 0x0340(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	bool OnExecute(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GCN_SentinelEnrage_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GCN_SentinelEnrage_C")
	}
	static class AGCN_SentinelEnrage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGCN_SentinelEnrage_C>();
	}
};
DUMPER7_ASSERTS_AGCN_SentinelEnrage_C;

SDK_NAMESPACE_END
