#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCN_WarriorsDrums

#include "Basic.hpp"

#include "SpicewoodGAS_classes.hpp"
#include "MSAudioRuntime_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GCN_WarriorsDrums.GCN_WarriorsDrums_C
// 0x0018 (0x0390 - 0x0378)
class AGCN_WarriorsDrums_C final : public AGCN_SpawnEffect
{
public:
	class UNiagaraComponent*                      NS_WarriorDrums;                                   // 0x0378(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0380(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	int32                                         Playing_ID;                                        // 0x0388(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	bool OnRemove(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	bool WhileActive(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GCN_WarriorsDrums_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GCN_WarriorsDrums_C")
	}
	static class AGCN_WarriorsDrums_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGCN_WarriorsDrums_C>();
	}
};
DUMPER7_ASSERTS_AGCN_WarriorsDrums_C;

SDK_NAMESPACE_END
