#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCN_Telegraph_LightningShockwave

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "SWCoreGAS_classes.hpp"
#include "MSAudioRuntime_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GCN_Telegraph_LightningShockwave.GCN_Telegraph_LightningShockwave_C
// 0x0018 (0x0358 - 0x0340)
class AGCN_Telegraph_LightningShockwave_C final : public ASWGameplayCueNotify_Actor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0340(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UNiagaraComponent*                      Niagara;                                           // 0x0348(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        Scene;                                             // 0x0350(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_GCN_Telegraph_LightningShockwave(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GCN_Telegraph_LightningShockwave_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GCN_Telegraph_LightningShockwave_C")
	}
	static class AGCN_Telegraph_LightningShockwave_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGCN_Telegraph_LightningShockwave_C>();
	}
};
DUMPER7_ASSERTS_AGCN_Telegraph_LightningShockwave_C;

SDK_NAMESPACE_END
