#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCN_HoneyPuddle

#include "Basic.hpp"

#include "GCN_HoneyPuddle_classes.hpp"
#include "GCN_HoneyPuddle_parameters.hpp"


SDK_NAMESPACE_START

// Function GCN_HoneyPuddle.GCN_HoneyPuddle_C.Execute Intro
// (BlueprintCallable, BlueprintEvent)

void AGCN_HoneyPuddle_C::Execute_Intro()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GCN_HoneyPuddle_C", "Execute Intro");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GCN_HoneyPuddle.GCN_HoneyPuddle_C.Execute Outro
// (BlueprintCallable, BlueprintEvent)

void AGCN_HoneyPuddle_C::Execute_Outro()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GCN_HoneyPuddle_C", "Execute Outro");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GCN_HoneyPuddle.GCN_HoneyPuddle_C.ExecuteUbergraph_GCN_HoneyPuddle
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AGCN_HoneyPuddle_C::ExecuteUbergraph_GCN_HoneyPuddle(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GCN_HoneyPuddle_C", "ExecuteUbergraph_GCN_HoneyPuddle");

	Params::GCN_HoneyPuddle_C_ExecuteUbergraph_GCN_HoneyPuddle Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GCN_HoneyPuddle.GCN_HoneyPuddle_C.OnExecute
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           MyTarget                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayCueParameters&    Parameters                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool AGCN_HoneyPuddle_C::OnExecute(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GCN_HoneyPuddle_C", "OnExecute");

	Params::GCN_HoneyPuddle_C_OnExecute Parms{};

	Parms.MyTarget = MyTarget;
	Parms.Parameters = std::move(Parameters);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function GCN_HoneyPuddle.GCN_HoneyPuddle_C.OnRemove
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           MyTarget                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayCueParameters&    Parameters                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool AGCN_HoneyPuddle_C::OnRemove(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GCN_HoneyPuddle_C", "OnRemove");

	Params::GCN_HoneyPuddle_C_OnRemove Parms{};

	Parms.MyTarget = MyTarget;
	Parms.Parameters = std::move(Parameters);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function GCN_HoneyPuddle.GCN_HoneyPuddle_C.Timeline_0__FinishedFunc
// (BlueprintEvent)

void AGCN_HoneyPuddle_C::Timeline_0__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GCN_HoneyPuddle_C", "Timeline_0__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GCN_HoneyPuddle.GCN_HoneyPuddle_C.Timeline_0__UpdateFunc
// (BlueprintEvent)

void AGCN_HoneyPuddle_C::Timeline_0__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GCN_HoneyPuddle_C", "Timeline_0__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GCN_HoneyPuddle.GCN_HoneyPuddle_C.Timeline_1__FinishedFunc
// (BlueprintEvent)

void AGCN_HoneyPuddle_C::Timeline_1__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GCN_HoneyPuddle_C", "Timeline_1__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GCN_HoneyPuddle.GCN_HoneyPuddle_C.Timeline_1__UpdateFunc
// (BlueprintEvent)

void AGCN_HoneyPuddle_C::Timeline_1__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GCN_HoneyPuddle_C", "Timeline_1__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GCN_HoneyPuddle.GCN_HoneyPuddle_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AGCN_HoneyPuddle_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GCN_HoneyPuddle_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GCN_HoneyPuddle.GCN_HoneyPuddle_C.WhileActive
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           MyTarget                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayCueParameters&    Parameters                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool AGCN_HoneyPuddle_C::WhileActive(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GCN_HoneyPuddle_C", "WhileActive");

	Params::GCN_HoneyPuddle_C_WhileActive Parms{};

	Parms.MyTarget = MyTarget;
	Parms.Parameters = std::move(Parameters);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
