#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCN_PropActorDeath

#include "Basic.hpp"

#include "SpicewoodGAS_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GCN_PropActorDeath.GCN_PropActorDeath_C
// 0x0008 (0x0348 - 0x0340)
class AGCN_PropActorDeath_C final : public AGCN_PropActorDeath
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0340(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GCN_PropActorDeath_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GCN_PropActorDeath_C")
	}
	static class AGCN_PropActorDeath_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGCN_PropActorDeath_C>();
	}
};
DUMPER7_ASSERTS_AGCN_PropActorDeath_C;

SDK_NAMESPACE_END
