#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCN_RedstoneMineLauncher

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "SpicewoodGAS_classes.hpp"
#include "MSAudioRuntime_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GCN_RedstoneMineLauncher.GCN_RedstoneMineLauncher_C
// 0x0038 (0x03B0 - 0x0378)
class AGCN_RedstoneMineLauncher_C final : public AGCN_SpawnEffect
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0378(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UArrowComponent*                        Arrow;                                             // 0x0380(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      NS_SmokeParticles;                                 // 0x0388(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      NS_MonstrosityHead;                                // 0x0390(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0398(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            EffectsTimeline__Direction_CEF54F9D44190CFA26FB3D8FA40A4C12; // 0x03A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3A1[0x7];                                      // 0x03A1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     EffectsTimeline;                                   // 0x03A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

public:
	void ActivateTimeline();
	void EffectsTimeline__ActivateMonstrosityHead__EventFunc();
	void EffectsTimeline__ActivateSmoke__EventFunc();
	void EffectsTimeline__FinishedFunc();
	void EffectsTimeline__UpdateFunc();
	void ExecuteUbergraph_GCN_RedstoneMineLauncher(int32 EntryPoint);
	bool OnExecute(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GCN_RedstoneMineLauncher_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GCN_RedstoneMineLauncher_C")
	}
	static class AGCN_RedstoneMineLauncher_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGCN_RedstoneMineLauncher_C>();
	}
};
DUMPER7_ASSERTS_AGCN_RedstoneMineLauncher_C;

SDK_NAMESPACE_END
