#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCN__EnchantedGreaterLifelink

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Dungeons_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GCN__EnchantedGreaterLifelink.GCN__EnchantedGreaterLifelink_C
// 0x0030 (0x0358 - 0x0328)
class AGCN__EnchantedGreaterLifelink_C final : public ADungeonsGameplayCueNotify_Actor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0328(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UNiagaraComponent*                      NS_GreaterLifelink_Beam;                           // 0x0330(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0338(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      LoopParticles;                                     // 0x0340(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 Source;                                            // 0x0348(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 Target;                                            // 0x0350(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_GCN__EnchantedGreaterLifelink(int32 EntryPoint);
	void OnCueEnd();
	bool OnRemove(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	void ReceiveTick(float DeltaSeconds);
	bool WhileActive(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GCN__EnchantedGreaterLifelink_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GCN__EnchantedGreaterLifelink_C")
	}
	static class AGCN__EnchantedGreaterLifelink_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGCN__EnchantedGreaterLifelink_C>();
	}
};
DUMPER7_ASSERTS_AGCN__EnchantedGreaterLifelink_C;

SDK_NAMESPACE_END
