#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCN_SoulDropped

#include "Basic.hpp"

#include "SpicewoodGAS_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GCN_SoulDropped.GCN_SoulDropped_C
// 0x0000 (0x0050 - 0x0050)
class UGCN_SoulDropped_C final : public UGCN_SoulDropped
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GCN_SoulDropped_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GCN_SoulDropped_C")
	}
	static class UGCN_SoulDropped_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGCN_SoulDropped_C>();
	}
};
DUMPER7_ASSERTS_UGCN_SoulDropped_C;

SDK_NAMESPACE_END
