#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCN_SoulEruption

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "SWCoreGAS_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GCN_SoulEruption.GCN_SoulEruption_C
// 0x0038 (0x0378 - 0x0340)
class AGCN_SoulEruption_C final : public ASWGameplayCueNotify_Actor
{
public:
	class UProceduralMeshComponent*               PukeMesh;                                          // 0x0340(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0348(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               Puddle_Material;                                   // 0x0350(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	TArray<class UGameplayImage*>                 GameplayImage;                                     // 0x0358(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<struct FVector>                        Locations;                                         // 0x0368(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	bool OnExecute(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GCN_SoulEruption_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GCN_SoulEruption_C")
	}
	static class AGCN_SoulEruption_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGCN_SoulEruption_C>();
	}
};
DUMPER7_ASSERTS_AGCN_SoulEruption_C;

SDK_NAMESPACE_END
