#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MediumFlashCameraShake

#include "Basic.hpp"

#include "EngineCameras_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass MediumFlashCameraShake.MediumFlashCameraShake_C
// 0x0000 (0x01F0 - 0x01F0)
class UMediumFlashCameraShake_C final : public ULegacyCameraShake
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("MediumFlashCameraShake_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MediumFlashCameraShake_C")
	}
	static class UMediumFlashCameraShake_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMediumFlashCameraShake_C>();
	}
};
DUMPER7_ASSERTS_UMediumFlashCameraShake_C;

SDK_NAMESPACE_END
