#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PlayerCharacterManager

#include "Basic.hpp"

#include "PlayerCharacterManager_classes.hpp"
#include "PlayerCharacterManager_parameters.hpp"


SDK_NAMESPACE_START

// Function PlayerCharacterManager.PlayerCharacterManager.CloneAndSelectCharacter
// (Final, Native, Public)
// Parameters:
// const class FString&                    CharacterId                                            (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPlayerCharacterManager::CloneAndSelectCharacter(const class FString& CharacterId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerCharacterManager", "CloneAndSelectCharacter");

	Params::PlayerCharacterManager_CloneAndSelectCharacter Parms{};

	Parms.CharacterId = std::move(CharacterId);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PlayerCharacterManager.PlayerCharacterManager.CreateAndSelectCharacter
// (Final, Native, Public, HasOutParams)
// Parameters:
// ECharacterType                          CharacterType                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FGameplayTag&              Skin                                                   (ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPlayerCharacterManager::CreateAndSelectCharacter(ECharacterType CharacterType, const struct FGameplayTag& Skin)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerCharacterManager", "CreateAndSelectCharacter");

	Params::PlayerCharacterManager_CreateAndSelectCharacter Parms{};

	Parms.CharacterType = CharacterType;
	Parms.Skin = std::move(Skin);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PlayerCharacterManager.PlayerCharacterManager.DeleteCharacter
// (Final, Native, Public)
// Parameters:
// const class FString&                    CharacterId                                            (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UPlayerCharacterManager::DeleteCharacter(const class FString& CharacterId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerCharacterManager", "DeleteCharacter");

	Params::PlayerCharacterManager_DeleteCharacter Parms{};

	Parms.CharacterId = std::move(CharacterId);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PlayerCharacterManager.PlayerCharacterManager.SelectActiveCharacter
// (Final, Native, Public)
// Parameters:
// const class FString&                    CharacterId                                            (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPlayerCharacterManager::SelectActiveCharacter(const class FString& CharacterId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerCharacterManager", "SelectActiveCharacter");

	Params::PlayerCharacterManager_SelectActiveCharacter Parms{};

	Parms.CharacterId = std::move(CharacterId);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PlayerCharacterManager.PlayerCharacterManager.CanCreateCharacter
// (Final, Native, Public, Const)
// Parameters:
// const ECharacterType                    CharacterType                                          (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UPlayerCharacterManager::CanCreateCharacter(const ECharacterType CharacterType) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerCharacterManager", "CanCreateCharacter");

	Params::PlayerCharacterManager_CanCreateCharacter Parms{};

	Parms.CharacterType = CharacterType;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PlayerCharacterManager.PlayerCharacterManager.GetActiveCharacterIdString
// (Final, Native, Public, Const)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class FString UPlayerCharacterManager::GetActiveCharacterIdString() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerCharacterManager", "GetActiveCharacterIdString");

	Params::PlayerCharacterManager_GetActiveCharacterIdString Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PlayerCharacterManager.PlayerCharacterManager.GetAvailableCharacterIDs
// (Final, Native, Public, Const)
// Parameters:
// TArray<class FString>                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)

TArray<class FString> UPlayerCharacterManager::GetAvailableCharacterIDs() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerCharacterManager", "GetAvailableCharacterIDs");

	Params::PlayerCharacterManager_GetAvailableCharacterIDs Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PlayerCharacterManager.PlayerCharacterManager.GetAvailableCharacters
// (Final, Native, Public, Const)
// Parameters:
// TArray<struct FPlayerCharacterInfo>     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)

TArray<struct FPlayerCharacterInfo> UPlayerCharacterManager::GetAvailableCharacters() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerCharacterManager", "GetAvailableCharacters");

	Params::PlayerCharacterManager_GetAvailableCharacters Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PlayerCharacterManager.PlayerCharacterManager.GetCharacterSkinTag
// (Final, Native, Public, Const)
// Parameters:
// const class FString&                    CharacterId                                            (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// TOptional<struct FGameplayTag>          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

TOptional<struct FGameplayTag> UPlayerCharacterManager::GetCharacterSkinTag(const class FString& CharacterId) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerCharacterManager", "GetCharacterSkinTag");

	Params::PlayerCharacterManager_GetCharacterSkinTag Parms{};

	Parms.CharacterId = std::move(CharacterId);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PlayerCharacterManager.PlayerCharacterManager.GetIsOnlineCharacter
// (Final, Native, Public, HasOutParams, Const)
// Parameters:
// const class FString&                    CharacterId                                            (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool*                                   OutIsOnlineCharacter                                   (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UPlayerCharacterManager::GetIsOnlineCharacter(const class FString& CharacterId, bool* OutIsOnlineCharacter) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerCharacterManager", "GetIsOnlineCharacter");

	Params::PlayerCharacterManager_GetIsOnlineCharacter Parms{};

	Parms.CharacterId = std::move(CharacterId);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (OutIsOnlineCharacter != nullptr)
		*OutIsOnlineCharacter = Parms.OutIsOnlineCharacter;

	return Parms.ReturnValue;
}


// Function PlayerCharacterManager.PlayerCharacterManager.HasOfflineCharacters
// (Final, Native, Public, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UPlayerCharacterManager::HasOfflineCharacters() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerCharacterManager", "HasOfflineCharacters");

	Params::PlayerCharacterManager_HasOfflineCharacters Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PlayerCharacterManager.PlayerCharacterManager.HasOnlineCharacters
// (Final, Native, Public, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UPlayerCharacterManager::HasOnlineCharacters() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerCharacterManager", "HasOnlineCharacters");

	Params::PlayerCharacterManager_HasOnlineCharacters Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PlayerCharacterManager.PlayerCharacterManager.UpdateCharacterLoadout
// (Final, Native, Public, HasOutParams, Const)
// Parameters:
// const class FString&                    CharacterId                                            (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FGameplayTag&              Key                                                    (ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FGameplayTag&              Value                                                  (ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    SuppressErrorDialog                                    (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPlayerCharacterManager::UpdateCharacterLoadout(const class FString& CharacterId, const struct FGameplayTag& Key, const struct FGameplayTag& Value, bool SuppressErrorDialog) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerCharacterManager", "UpdateCharacterLoadout");

	Params::PlayerCharacterManager_UpdateCharacterLoadout Parms{};

	Parms.CharacterId = std::move(CharacterId);
	Parms.Key = std::move(Key);
	Parms.Value = std::move(Value);
	Parms.SuppressErrorDialog = SuppressErrorDialog;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PlayerCharacterManager.PlayerCharacterManagerSubsystem.Get
// (Final, Native, Public, Const)
// Parameters:
// class UPlayerCharacterManager*          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UPlayerCharacterManager* UPlayerCharacterManagerSubsystem::Get() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerCharacterManagerSubsystem", "Get");

	Params::PlayerCharacterManagerSubsystem_Get Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
