#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SpicewoodPlayerPing

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function SpicewoodPlayerPing.SWPingActor.OnOwnerDestroyed
// 0x0008 (0x0008 - 0x0000)
struct SWPingActor_OnOwnerDestroyed final
{
public:
	class AActor*                                 DestroyedActor;                                    // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SWPingActor_OnOwnerDestroyed;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
