#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SpicewoodTelemetry

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// Class SpicewoodTelemetry.SWTelemetrySubsystem
// 0x0000 (0x0030 - 0x0030)
class USWTelemetrySubsystem final : public UGameInstanceSubsystem
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SWTelemetrySubsystem")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SWTelemetrySubsystem")
	}
	static class USWTelemetrySubsystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<USWTelemetrySubsystem>();
	}
};
DUMPER7_ASSERTS_USWTelemetrySubsystem;

SDK_NAMESPACE_END
