#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SpicewoodReplicationGraph

#include "Basic.hpp"

#include "SpicewoodReplicationGraph_classes.hpp"
#include "SpicewoodReplicationGraph_parameters.hpp"


SDK_NAMESPACE_START

// Function SpicewoodReplicationGraph.SpicewoodReplicationGraphDebugActor.ClientReceiveNonRoutedActorData
// (Net, NetReliable, Native, Event, Public, NetClient)
// Parameters:
// const TArray<struct FNonRoutedActorData>&ActorData                                              (ConstParm, Parm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)

void ASpicewoodReplicationGraphDebugActor::ClientReceiveNonRoutedActorData(const TArray<struct FNonRoutedActorData>& ActorData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SpicewoodReplicationGraphDebugActor", "ClientReceiveNonRoutedActorData");

	Params::SpicewoodReplicationGraphDebugActor_ClientReceiveNonRoutedActorData Parms{};

	Parms.ActorData = std::move(ActorData);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function SpicewoodReplicationGraph.SpicewoodReplicationGraphDebugActor.FetchNonRoutedActorData
// (Net, NetReliable, Native, Event, Public, NetServer)

void ASpicewoodReplicationGraphDebugActor::FetchNonRoutedActorData()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SpicewoodReplicationGraphDebugActor", "FetchNonRoutedActorData");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function SpicewoodReplicationGraph.SpicewoodReplicationGraphDebugActor.FetchReplicationGraphStatistics
// (Net, NetReliable, Native, Event, Public, NetServer)

void ASpicewoodReplicationGraphDebugActor::FetchReplicationGraphStatistics()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SpicewoodReplicationGraphDebugActor", "FetchReplicationGraphStatistics");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function SpicewoodReplicationGraph.SpicewoodReplicationGraphDebugActor.OnRep_PendingReplicationData
// (Final, Native, Public)

void ASpicewoodReplicationGraphDebugActor::OnRep_PendingReplicationData()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SpicewoodReplicationGraphDebugActor", "OnRep_PendingReplicationData");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function SpicewoodReplicationGraph.SpicewoodReplicationGraphDebugActor.SendMorePendingReplicatedData
// (Net, NetReliable, Native, Event, Public, NetServer)

void ASpicewoodReplicationGraphDebugActor::SendMorePendingReplicatedData()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SpicewoodReplicationGraphDebugActor", "SendMorePendingReplicatedData");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


SDK_NAMESPACE_END
