#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SpicewoodAudioRuntime

#include "Basic.hpp"

#include "SpicewoodAudioRuntime_structs.hpp"
#include "SWCoreTypes_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "Engine_classes.hpp"
#include "GameplayMessageRuntime_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "CoreUObject_classes.hpp"
#include "DeveloperSettings_classes.hpp"


SDK_NAMESPACE_START

// Class SpicewoodAudioRuntime.SWAudioEncounterSubsystem
// 0x0930 (0x0970 - 0x0040)
class alignas(0x10) USWAudioEncounterSubsystem final : public UTickableWorldSubsystem
{
public:
	uint8                                         Pad_40[0x3CB];                                     // 0x0040(0x03CB)(Fixing Size After Last Property [ Dumper-7 ])
	ECutsceneState                                CurrentCutsceneState;                              // 0x040B(0x0001)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	bool                                          bIsPartyWiped;                                     // 0x040C(0x0001)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_40D[0x52B];                                    // 0x040D(0x052B)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CombatIntensity;                                   // 0x0938(0x0004)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         MobMaxDistanceSq;                                  // 0x093C(0x0004)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         MobActiveMaxDistanceSq;                            // 0x0940(0x0004)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         StorminatorMaxDistanceSq;                          // 0x0944(0x0004)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         StorminatorActiveMaxDistanceSq;                    // 0x0948(0x0004)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_94C[0x14];                                     // 0x094C(0x0014)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<TWeakObjectPtr<class UObject>>         GamePersistentReferences;                          // 0x0960(0x0010)(ZeroConstructor, Transient, UObjectWrapper, NativeAccessSpecifierPrivate)

public:
	void OnQuestTaskStateChanged(class UQuestTask* Task);
	void OnSoulImbalanceStateChange(const struct FGameplayTag& EventTag, const struct FSWTagData& Payload);
	void OnSoulStormDurationUpdate(const struct FGameplayTag& EventTag, const struct FSoulstormDurationAudioUpdateEvent& Payload);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SWAudioEncounterSubsystem")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SWAudioEncounterSubsystem")
	}
	static class USWAudioEncounterSubsystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<USWAudioEncounterSubsystem>();
	}
};
DUMPER7_ASSERTS_USWAudioEncounterSubsystem;

// Class SpicewoodAudioRuntime.SWAudioSubsystem
// 0x0038 (0x0068 - 0x0030)
class USWAudioSubsystem final : public UGameInstanceSubsystem
{
public:
	TArray<struct FGameplayMessageListenerHandle> ListenerHandles;                                   // 0x0030(0x0010)(ZeroConstructor, Transient, NativeAccessSpecifierPrivate)
	uint8                                         Pad_40[0x10];                                      // 0x0040(0x0010)(Fixing Size After Last Property [ Dumper-7 ])
	bool                                          SWAudioSettingsLoaded;                             // 0x0050(0x0001)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<TWeakObjectPtr<class UAkAudioType>>    GamePersistentReferences;                          // 0x0058(0x0010)(ZeroConstructor, Transient, UObjectWrapper, NativeAccessSpecifierPrivate)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SWAudioSubsystem")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SWAudioSubsystem")
	}
	static class USWAudioSubsystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<USWAudioSubsystem>();
	}
};
DUMPER7_ASSERTS_USWAudioSubsystem;

// Class SpicewoodAudioRuntime.SWAudioMediaWorldSubsystem
// 0x0050 (0x0080 - 0x0030)
class USWAudioMediaWorldSubsystem final : public UWorldSubsystem
{
public:
	TMap<EBlockMaterial, TWeakObjectPtr<class UObject>> PersistentBlockMaterialReferences;           // 0x0030(0x0050)(Transient, UObjectWrapper, NativeAccessSpecifierPrivate)

public:
	void OnAssetsLoaded(const TMap<EBlockMaterial, struct FSoftObjectPath>& AssetPaths);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SWAudioMediaWorldSubsystem")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SWAudioMediaWorldSubsystem")
	}
	static class USWAudioMediaWorldSubsystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<USWAudioMediaWorldSubsystem>();
	}
};
DUMPER7_ASSERTS_USWAudioMediaWorldSubsystem;

// Class SpicewoodAudioRuntime.SWAudioSettings
// 0x03B8 (0x03F0 - 0x0038)
class USWAudioSettings final : public UDeveloperSettings
{
public:
	TArray<TSoftObjectPtr<class UAkAudioDeviceShareSet>> AudioOutputs;                               // 0x0038(0x0010)(Edit, ZeroConstructor, Config, DisableEditOnInstance, UObjectWrapper, NativeAccessSpecifierPublic)
	TSoftObjectPtr<class UAkRtpc>                 NumPlayersRTPC;                                    // 0x0048(0x0028)(Edit, Config, DisableEditOnInstance, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<TSoftObjectPtr<class UAkSwitchValue>>  LocalPlayerIndexSwitches;                          // 0x0070(0x0010)(Edit, ZeroConstructor, Config, DisableEditOnInstance, UObjectWrapper, NativeAccessSpecifierPublic)
	TMap<EBlockMaterial, TSoftObjectPtr<class UAkSwitchValue>> BlockMaterialSwitches;                // 0x0080(0x0050)(Edit, Config, DisableEditOnInstance, UObjectWrapper, NativeAccessSpecifierPublic)
	TSoftObjectPtr<class UAkStateValue>           DefaultCutsceneState;                              // 0x00D0(0x0028)(Edit, Config, DisableEditOnInstance, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSoftObjectPtr<class UAkRtpc>                 CombatIntensityRTPC;                               // 0x00F8(0x0028)(Edit, Config, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSoftObjectPtr<class UAkRtpc>                 ArenaProgressRTPC;                                 // 0x0120(0x0028)(Edit, Config, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMap<EAudioEncounterType, TSoftObjectPtr<class UAkStateValue>> EncounterTypeStates;              // 0x0148(0x0050)(Edit, Config, DisableEditOnInstance, UObjectWrapper, NativeAccessSpecifierPublic)
	TMap<EAudioEncounterEventState, TSoftObjectPtr<class UAkTrigger>> EncounterTriggers;             // 0x0198(0x0050)(Edit, Config, DisableEditOnInstance, UObjectWrapper, NativeAccessSpecifierPublic)
	TMap<EAudioSoulImbalanceType, TSoftObjectPtr<class UAkStateValue>> SoulImbalanceStates;          // 0x01E8(0x0050)(Edit, Config, DisableEditOnInstance, UObjectWrapper, NativeAccessSpecifierPublic)
	TSoftObjectPtr<class UAkStateValue>           DefaultArenaState;                                 // 0x0238(0x0028)(Edit, Config, DisableEditOnInstance, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MobMaxDistance;                                    // 0x0260(0x0004)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         StorminatorMaxDistance;                            // 0x0264(0x0004)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSoftObjectPtr<class UAkRtpc>                 ClosestQuestTaskDistanceRTPC;                      // 0x0268(0x0028)(Edit, Config, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSet<struct FSoftClassPath>                   EncounterTypeStatesAllowList;                      // 0x0290(0x0050)(Edit, Config, NativeAccessSpecifierPublic)
	TMap<EAudioPlayerType, TSoftObjectPtr<class UAkSwitchValue>> PlayerTypeSwitches;                 // 0x02E0(0x0050)(Edit, Config, DisableEditOnInstance, UObjectWrapper, NativeAccessSpecifierPublic)
	TSoftObjectPtr<class UAkRtpc>                 SoulstormTimeDuration;                             // 0x0330(0x0028)(Edit, Config, DisableEditOnInstance, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSoftObjectPtr<class UAkRtpc>                 ClosestStorminatorDistance;                        // 0x0358(0x0028)(Edit, Config, DisableEditOnInstance, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<TSoftObjectPtr<class UAkStateValue>>   GSComponentStatesAllowList;                        // 0x0380(0x0010)(Edit, ZeroConstructor, Config, DisableEditOnInstance, UObjectWrapper, NativeAccessSpecifierPublic)
	TSet<int32>                                   ControllersUsingMotion;                            // 0x0390(0x0050)(Transient, NativeAccessSpecifierPublic)
	TArray<TWeakObjectPtr<class UAkAudioType>>    GamePersistentReferences;                          // 0x03E0(0x0010)(ZeroConstructor, Transient, UObjectWrapper, NativeAccessSpecifierPrivate)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SWAudioSettings")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SWAudioSettings")
	}
	static class USWAudioSettings* GetDefaultObj()
	{
		return GetDefaultObjImpl<USWAudioSettings>();
	}
};
DUMPER7_ASSERTS_USWAudioSettings;

// Class SpicewoodAudioRuntime.SplineAudioBase
// 0x00B0 (0x00D8 - 0x0028)
class USplineAudioBase : public UObject
{
public:
	TSoftObjectPtr<class AActor>                  SplineSourceActor;                                 // 0x0028(0x0028)(Edit, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           AudioCategory;                                     // 0x0050(0x0008)(Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAkAudioEvent*                          AkAudioLoopEvent;                                  // 0x0058(0x0008)(Edit, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, TObjectPtr)
	class UAkAudioEvent*                          AkAudioDeactivationEvent;                          // 0x0060(0x0008)(Edit, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, TObjectPtr)
	bool                                          ActivateOnBeginPlay;                               // 0x0068(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_69[0x3];                                       // 0x0069(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         MaxDistance;                                       // 0x006C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ShowDebug;                                         // 0x0070(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_71[0x7];                                       // 0x0071(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USplineComponent*                       Spline;                                            // 0x0078(0x0008)(ExportObject, ZeroConstructor, Transient, InstancedReference, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, TObjectPtr)
	class UMSAudioComponent*                      AudioLoopComponent;                                // 0x0080(0x0008)(ExportObject, ZeroConstructor, Transient, InstancedReference, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, TObjectPtr)
	uint8                                         Pad_88[0x50];                                      // 0x0088(0x0050)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	bool Activate(const class AActor* Parent);
	bool Deactivate(const class AActor* Parent, bool PlayDeactivationSound);
	float GetAudioSourceDistanceAlongSpline(const class UWorld* World, const float DeltaTime);
	bool Update(const class AActor* Parent, const float DeltaTime);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SplineAudioBase")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SplineAudioBase")
	}
	static class USplineAudioBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<USplineAudioBase>();
	}
};
DUMPER7_ASSERTS_USplineAudioBase;

// Class SpicewoodAudioRuntime.FollowPlayerAlongSplineObject
// 0x0028 (0x0100 - 0x00D8)
class UFollowPlayerAlongSplineObject final : public USplineAudioBase
{
public:
	float                                         OffsetAudioAlongSpline;                            // 0x00D8(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_DC[0x4];                                       // 0x00DC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FRtpcWithRange>                 PerpendicularDistanceRTPCs;                        // 0x00E0(0x0010)(Edit, ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<struct FRtpcWithRange>                 ParallelProgressionRTPCs;                          // 0x00F0(0x0010)(Edit, ZeroConstructor, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("FollowPlayerAlongSplineObject")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FollowPlayerAlongSplineObject")
	}
	static class UFollowPlayerAlongSplineObject* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFollowPlayerAlongSplineObject>();
	}
};
DUMPER7_ASSERTS_UFollowPlayerAlongSplineObject;

// Class SpicewoodAudioRuntime.FollowSplineWithSpeed
// 0x0010 (0x00E8 - 0x00D8)
class UFollowSplineWithSpeed final : public USplineAudioBase
{
public:
	float                                         Speed;                                             // 0x00D8(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_DC[0x4];                                       // 0x00DC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UAkAudioEvent*                          ReachSplineEndAudioEvent;                          // 0x00E0(0x0008)(Edit, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, TObjectPtr)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("FollowSplineWithSpeed")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FollowSplineWithSpeed")
	}
	static class UFollowSplineWithSpeed* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFollowSplineWithSpeed>();
	}
};
DUMPER7_ASSERTS_UFollowSplineWithSpeed;

// Class SpicewoodAudioRuntime.SWAudioSplineComponent
// 0x0050 (0x0290 - 0x0240)
class USWAudioSplineComponent final : public USceneComponent
{
public:
	TMap<class FString, class USplineAudioBase*>  SplineAudioObjects;                                // 0x0240(0x0050)(Edit, BlueprintVisible, ExportObject, ContainsInstancedReference, UObjectWrapper, NativeAccessSpecifierPublic, TObjectPtr)

public:
	void ActivateAllAudioSplineObjects();
	void ActivateAudioSplineObject(const class FString& ID);
	void AddAudioSplineObject(const class FString& ID, class USplineAudioBase* SplineAudio);
	void DeactivateAllAudioSplineObjects(bool PlayDeactivationSound);
	void DeactivateAudioSplineObject(const class FString& ID, bool PlayDeactivationSound);
	void RemoveAudioSplineObject(const class FString& ID, class USplineAudioBase* SplineAudio);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SWAudioSplineComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SWAudioSplineComponent")
	}
	static class USWAudioSplineComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<USWAudioSplineComponent>();
	}
};
DUMPER7_ASSERTS_USWAudioSplineComponent;

// Class SpicewoodAudioRuntime.SWAudioStatics
// 0x0000 (0x0028 - 0x0028)
class USWAudioStatics final : public UBlueprintFunctionLibrary
{
public:
	static class UAkSwitchValue* GetSwitchValue(const class UObject* WorldContextObject, EBlockMaterial Material);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SWAudioStatics")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SWAudioStatics")
	}
	static class USWAudioStatics* GetDefaultObj()
	{
		return GetDefaultObjImpl<USWAudioStatics>();
	}
};
DUMPER7_ASSERTS_USWAudioStatics;

// Class SpicewoodAudioRuntime.SWAudioVolumeSpawnerSubsystem
// 0x0108 (0x0148 - 0x0040)
class USWAudioVolumeSpawnerSubsystem final : public UTickableWorldSubsystem
{
public:
	uint8                                         Pad_40[0x10];                                      // 0x0040(0x0010)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<uint32, struct FPendingVolumeSpawn>      PendingVolumes;                                    // 0x0050(0x0050)(Transient, NativeAccessSpecifierPrivate)
	TMap<uint32, class ATriggerBox*>              ActiveVolumes;                                     // 0x00A0(0x0050)(Transient, UObjectWrapper, NativeAccessSpecifierPrivate, TObjectPtr)
	uint8                                         Pad_F0[0x50];                                      // 0x00F0(0x0050)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         VolumesSpawned;                                    // 0x0140(0x0004)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	int32                                         VolumesDestroyed;                                  // 0x0144(0x0004)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SWAudioVolumeSpawnerSubsystem")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SWAudioVolumeSpawnerSubsystem")
	}
	static class USWAudioVolumeSpawnerSubsystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<USWAudioVolumeSpawnerSubsystem>();
	}
};
DUMPER7_ASSERTS_USWAudioVolumeSpawnerSubsystem;

// Class SpicewoodAudioRuntime.SWAudioWorldSubsystem
// 0x0048 (0x0088 - 0x0040)
class USWAudioWorldSubsystem final : public UTickableWorldSubsystem
{
public:
	TArray<struct FGameplayMessageListenerHandle> ListenerHandles;                                   // 0x0040(0x0010)(ZeroConstructor, Transient, NativeAccessSpecifierPrivate)
	float                                         DefaultCameraDistanceSq;                           // 0x0050(0x0004)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         CurrentCameraDistanceSq;                           // 0x0054(0x0004)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	int32                                         CameraDistanceUpdateTick;                          // 0x0058(0x0004)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	int32                                         CurrentPlayerCount;                                // 0x005C(0x0004)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	EWorldState                                   CurrentWorldState;                                 // 0x0060(0x0001)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_61[0x3];                                       // 0x0061(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TWeakObjectPtr<class USWLevelSequencePlayer>  ActiveSequencePlayer;                              // 0x0064(0x0008)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	TWeakObjectPtr<class UMovieSceneAkAudioEventSection> ActiveAudioSection;                         // 0x006C(0x0008)(ExportObject, ZeroConstructor, Transient, InstancedReference, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_74[0x4];                                       // 0x0074(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        AudioSectionStartTime;                             // 0x0078(0x0008)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	double                                        MusicWaitSyncTime;                                 // 0x0080(0x0008)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)

public:
	void OnWorldStateEntered(const EWorldState NewState);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SWAudioWorldSubsystem")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SWAudioWorldSubsystem")
	}
	static class USWAudioWorldSubsystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<USWAudioWorldSubsystem>();
	}
};
DUMPER7_ASSERTS_USWAudioWorldSubsystem;

SDK_NAMESPACE_END
