#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SpicewoodGuidanceProcedural

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// Class SpicewoodGuidanceProcedural.SWGuidanceProceduralGenerationSubsystem
// 0x0060 (0x0090 - 0x0030)
class USWGuidanceProceduralGenerationSubsystem final : public UWorldSubsystem
{
public:
	uint8                                         Pad_30[0x60];                                      // 0x0030(0x0060)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void OnRegisterDoorsToGuidanceSystem(const class ULevel* Level);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SWGuidanceProceduralGenerationSubsystem")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SWGuidanceProceduralGenerationSubsystem")
	}
	static class USWGuidanceProceduralGenerationSubsystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<USWGuidanceProceduralGenerationSubsystem>();
	}
};
DUMPER7_ASSERTS_USWGuidanceProceduralGenerationSubsystem;

// Class SpicewoodGuidanceProcedural.SWGuidanceProceduralLoadingSubsystem
// 0x0080 (0x00B0 - 0x0030)
class USWGuidanceProceduralLoadingSubsystem final : public UWorldSubsystem
{
public:
	uint8                                         Pad_30[0x80];                                      // 0x0030(0x0080)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SWGuidanceProceduralLoadingSubsystem")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SWGuidanceProceduralLoadingSubsystem")
	}
	static class USWGuidanceProceduralLoadingSubsystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<USWGuidanceProceduralLoadingSubsystem>();
	}
};
DUMPER7_ASSERTS_USWGuidanceProceduralLoadingSubsystem;

SDK_NAMESPACE_END
