#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SpicewoodAudioRuntime

#include "Basic.hpp"

#include "SpicewoodAudioRuntime_classes.hpp"
#include "SpicewoodAudioRuntime_parameters.hpp"


SDK_NAMESPACE_START

// Function SpicewoodAudioRuntime.SWAudioEncounterSubsystem.OnQuestTaskStateChanged
// (Final, Native, Private)
// Parameters:
// class UQuestTask*                       Task                                                   (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void USWAudioEncounterSubsystem::OnQuestTaskStateChanged(class UQuestTask* Task)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SWAudioEncounterSubsystem", "OnQuestTaskStateChanged");

	Params::SWAudioEncounterSubsystem_OnQuestTaskStateChanged Parms{};

	Parms.Task = Task;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function SpicewoodAudioRuntime.SWAudioEncounterSubsystem.OnSoulImbalanceStateChange
// (Final, Native, Public, HasOutParams)
// Parameters:
// const struct FGameplayTag&              EventTag                                               (ConstParm, Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FSWTagData&                Payload                                                (ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)

void USWAudioEncounterSubsystem::OnSoulImbalanceStateChange(const struct FGameplayTag& EventTag, const struct FSWTagData& Payload)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SWAudioEncounterSubsystem", "OnSoulImbalanceStateChange");

	Params::SWAudioEncounterSubsystem_OnSoulImbalanceStateChange Parms{};

	Parms.EventTag = std::move(EventTag);
	Parms.Payload = std::move(Payload);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function SpicewoodAudioRuntime.SWAudioEncounterSubsystem.OnSoulStormDurationUpdate
// (Final, Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// const struct FGameplayTag&              EventTag                                               (ConstParm, Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FSoulstormDurationAudioUpdateEvent&Payload                                                (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)

void USWAudioEncounterSubsystem::OnSoulStormDurationUpdate(const struct FGameplayTag& EventTag, const struct FSoulstormDurationAudioUpdateEvent& Payload)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SWAudioEncounterSubsystem", "OnSoulStormDurationUpdate");

	Params::SWAudioEncounterSubsystem_OnSoulStormDurationUpdate Parms{};

	Parms.EventTag = std::move(EventTag);
	Parms.Payload = std::move(Payload);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function SpicewoodAudioRuntime.SWAudioMediaWorldSubsystem.OnAssetsLoaded
// (Final, Native, Private)
// Parameters:
// const TMap<EBlockMaterial, struct FSoftObjectPath>&AssetPaths                                             (ConstParm, Parm, NativeAccessSpecifierPublic)

void USWAudioMediaWorldSubsystem::OnAssetsLoaded(const TMap<EBlockMaterial, struct FSoftObjectPath>& AssetPaths)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SWAudioMediaWorldSubsystem", "OnAssetsLoaded");

	Params::SWAudioMediaWorldSubsystem_OnAssetsLoaded Parms{};

	Parms.AssetPaths = std::move(AssetPaths);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function SpicewoodAudioRuntime.SplineAudioBase.Activate
// (Native, Public, BlueprintCallable)
// Parameters:
// const class AActor*                     Parent                                                 (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool USplineAudioBase::Activate(const class AActor* Parent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SplineAudioBase", "Activate");

	Params::SplineAudioBase_Activate Parms{};

	Parms.Parent = Parent;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SpicewoodAudioRuntime.SplineAudioBase.Deactivate
// (Native, Public, BlueprintCallable)
// Parameters:
// const class AActor*                     Parent                                                 (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    PlayDeactivationSound                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool USplineAudioBase::Deactivate(const class AActor* Parent, bool PlayDeactivationSound)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SplineAudioBase", "Deactivate");

	Params::SplineAudioBase_Deactivate Parms{};

	Parms.Parent = Parent;
	Parms.PlayDeactivationSound = PlayDeactivationSound;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SpicewoodAudioRuntime.SplineAudioBase.GetAudioSourceDistanceAlongSpline
// (Native, Public, BlueprintCallable)
// Parameters:
// const class UWorld*                     World                                                  (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const float                             DeltaTime                                              (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

float USplineAudioBase::GetAudioSourceDistanceAlongSpline(const class UWorld* World, const float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SplineAudioBase", "GetAudioSourceDistanceAlongSpline");

	Params::SplineAudioBase_GetAudioSourceDistanceAlongSpline Parms{};

	Parms.World = World;
	Parms.DeltaTime = DeltaTime;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SpicewoodAudioRuntime.SplineAudioBase.Update
// (Native, Public, BlueprintCallable)
// Parameters:
// const class AActor*                     Parent                                                 (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const float                             DeltaTime                                              (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool USplineAudioBase::Update(const class AActor* Parent, const float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SplineAudioBase", "Update");

	Params::SplineAudioBase_Update Parms{};

	Parms.Parent = Parent;
	Parms.DeltaTime = DeltaTime;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SpicewoodAudioRuntime.SWAudioSplineComponent.ActivateAllAudioSplineObjects
// (Final, Native, Public, BlueprintCallable)

void USWAudioSplineComponent::ActivateAllAudioSplineObjects()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SWAudioSplineComponent", "ActivateAllAudioSplineObjects");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function SpicewoodAudioRuntime.SWAudioSplineComponent.ActivateAudioSplineObject
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class FString&                    ID                                                     (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void USWAudioSplineComponent::ActivateAudioSplineObject(const class FString& ID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SWAudioSplineComponent", "ActivateAudioSplineObject");

	Params::SWAudioSplineComponent_ActivateAudioSplineObject Parms{};

	Parms.ID = std::move(ID);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function SpicewoodAudioRuntime.SWAudioSplineComponent.AddAudioSplineObject
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class FString&                    ID                                                     (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class USplineAudioBase*                 SplineAudio                                            (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void USWAudioSplineComponent::AddAudioSplineObject(const class FString& ID, class USplineAudioBase* SplineAudio)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SWAudioSplineComponent", "AddAudioSplineObject");

	Params::SWAudioSplineComponent_AddAudioSplineObject Parms{};

	Parms.ID = std::move(ID);
	Parms.SplineAudio = SplineAudio;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function SpicewoodAudioRuntime.SWAudioSplineComponent.DeactivateAllAudioSplineObjects
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    PlayDeactivationSound                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void USWAudioSplineComponent::DeactivateAllAudioSplineObjects(bool PlayDeactivationSound)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SWAudioSplineComponent", "DeactivateAllAudioSplineObjects");

	Params::SWAudioSplineComponent_DeactivateAllAudioSplineObjects Parms{};

	Parms.PlayDeactivationSound = PlayDeactivationSound;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function SpicewoodAudioRuntime.SWAudioSplineComponent.DeactivateAudioSplineObject
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class FString&                    ID                                                     (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    PlayDeactivationSound                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void USWAudioSplineComponent::DeactivateAudioSplineObject(const class FString& ID, bool PlayDeactivationSound)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SWAudioSplineComponent", "DeactivateAudioSplineObject");

	Params::SWAudioSplineComponent_DeactivateAudioSplineObject Parms{};

	Parms.ID = std::move(ID);
	Parms.PlayDeactivationSound = PlayDeactivationSound;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function SpicewoodAudioRuntime.SWAudioSplineComponent.RemoveAudioSplineObject
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class FString&                    ID                                                     (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class USplineAudioBase*                 SplineAudio                                            (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void USWAudioSplineComponent::RemoveAudioSplineObject(const class FString& ID, class USplineAudioBase* SplineAudio)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SWAudioSplineComponent", "RemoveAudioSplineObject");

	Params::SWAudioSplineComponent_RemoveAudioSplineObject Parms{};

	Parms.ID = std::move(ID);
	Parms.SplineAudio = SplineAudio;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function SpicewoodAudioRuntime.SWAudioStatics.GetSwitchValue
// (Final, BlueprintCosmetic, Native, Static, Public, BlueprintCallable)
// Parameters:
// const class UObject*                    WorldContextObject                                     (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// EBlockMaterial                          Material                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UAkSwitchValue*                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UAkSwitchValue* USWAudioStatics::GetSwitchValue(const class UObject* WorldContextObject, EBlockMaterial Material)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("SWAudioStatics", "GetSwitchValue");

	Params::SWAudioStatics_GetSwitchValue Parms{};

	Parms.WorldContextObject = WorldContextObject;
	Parms.Material = Material;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SpicewoodAudioRuntime.SWAudioWorldSubsystem.OnWorldStateEntered
// (Final, Native, Private)
// Parameters:
// const EWorldState                       NewState                                               (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void USWAudioWorldSubsystem::OnWorldStateEntered(const EWorldState NewState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SWAudioWorldSubsystem", "OnWorldStateEntered");

	Params::SWAudioWorldSubsystem_OnWorldStateEntered Parms{};

	Parms.NewState = NewState;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


SDK_NAMESPACE_END
