#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SpicewoodPlayerPing

#include "Basic.hpp"

#include "SWCorePayloads_structs.hpp"
#include "GameplayTags_structs.hpp"


SDK_NAMESPACE_START

// ScriptStruct SpicewoodPlayerPing.PingPerformedPayload
// 0x0028 (0x0028 - 0x0000)
struct FPingPerformedPayload final
{
public:
	struct FUIPlayerIDHandle                      PlayerIDHandle;                                    // 0x0000(0x0010)(Edit, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           EmoteTag;                                          // 0x0010(0x0008)(Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	double                                        Time;                                              // 0x0018(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         TimestampID;                                       // 0x0020(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FPingPerformedPayload;

// ScriptStruct SpicewoodPlayerPing.PingMarkerMetaData
// 0x0018 (0x0018 - 0x0000)
struct FPingMarkerMetaData final
{
public:
	struct FUIPlayerIDHandle                      PlayerIDHandle;                                    // 0x0000(0x0010)(Edit, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           EmoteTag;                                          // 0x0010(0x0008)(Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FPingMarkerMetaData;

SDK_NAMESPACE_END
