#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: StyleVar_Tags_Colossal

#include "Basic.hpp"

#include "SpicewoodUI_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass StyleVar_Tags_Colossal.StyleVar_Tags_Colossal_C
// 0x0000 (0x01A0 - 0x01A0)
class UStyleVar_Tags_Colossal_C final : public USpicewoodTextStyle
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("StyleVar_Tags_Colossal_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"StyleVar_Tags_Colossal_C")
	}
	static class UStyleVar_Tags_Colossal_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UStyleVar_Tags_Colossal_C>();
	}
};
DUMPER7_ASSERTS_UStyleVar_Tags_Colossal_C;

SDK_NAMESPACE_END
