#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SWCoreBlockQuery

#include "Basic.hpp"

#include "SWCoreBlockQuery_classes.hpp"
#include "SWCoreBlockQuery_parameters.hpp"


SDK_NAMESPACE_START

// Function SWCoreBlockQuery.BlockQuerySubsystem.AddWorldTerrainDataSourceComponent
// (Final, Native, Public)
// Parameters:
// class UTerrainDataContainerComponent*   InComponent                                            (Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UBlockQuerySubsystem::AddWorldTerrainDataSourceComponent(class UTerrainDataContainerComponent* InComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BlockQuerySubsystem", "AddWorldTerrainDataSourceComponent");

	Params::BlockQuerySubsystem_AddWorldTerrainDataSourceComponent Parms{};

	Parms.InComponent = InComponent;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function SWCoreBlockQuery.BlockQuerySubsystem.RemoveWorldTerrainDataSourceComponent
// (Final, Native, Public)
// Parameters:
// class UTerrainDataContainerComponent*   InComponent                                            (Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UBlockQuerySubsystem::RemoveWorldTerrainDataSourceComponent(class UTerrainDataContainerComponent* InComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BlockQuerySubsystem", "RemoveWorldTerrainDataSourceComponent");

	Params::BlockQuerySubsystem_RemoveWorldTerrainDataSourceComponent Parms{};

	Parms.InComponent = InComponent;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function SWCoreBlockQuery.BlockQuerySubsystem.GetMaterialAt
// (Final, Native, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// const struct FVector&                   Location                                               (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// EBlockMaterial                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

EBlockMaterial UBlockQuerySubsystem::GetMaterialAt(const struct FVector& Location) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BlockQuerySubsystem", "GetMaterialAt");

	Params::BlockQuerySubsystem_GetMaterialAt Parms{};

	Parms.Location = std::move(Location);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
