#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UITextStyleTokens

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function UITextStyleTokens.TextStyleTokenSubsystem.GetTextStyle
// 0x0010 (0x0010 - 0x0000)
struct TextStyleTokenSubsystem_GetTextStyle final
{
public:
	struct FGameplayTag                           TokenTag;                                          // 0x0000(0x0008)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UCommonTextStyle*                       ReturnValue;                                       // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_TextStyleTokenSubsystem_GetTextStyle;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
