#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_PlayerBanner

#include "Basic.hpp"

#include "Angelscript_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass W_PlayerBanner.W_PlayerBanner_C
// 0x0020 (0x0580 - 0x0560)
class UW_PlayerBanner_C final : public UAS_PlayerBanner
{
public:
	class UW_Divider_C*                           W_Divider;                                         // 0x0560(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UAS_SpicewoodLazyImage*                 PowerIcon;                                         // 0x0568(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UAS_SpicewoodLazyImage*                 DialogBG;                                          // 0x0570(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_PlayerBanner_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_PlayerBanner_C")
	}
	static class UW_PlayerBanner_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_PlayerBanner_C>();
	}
};
DUMPER7_ASSERTS_UW_PlayerBanner_C;

SDK_NAMESPACE_END
