#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WorldLightRig

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WorldLightRig.WorldLightRigHandler2Subsystem.SetMapRenderLightingPreset
// 0x0008 (0x0008 - 0x0000)
struct WorldLightRigHandler2Subsystem_SetMapRenderLightingPreset final
{
public:
	struct FGameplayTag                           LightingTag;                                       // 0x0000(0x0008)(Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_WorldLightRigHandler2Subsystem_SetMapRenderLightingPreset;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
