#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AnimNS_Slash

#include "Basic.hpp"

#include "AnimNS_Slash_classes.hpp"
#include "AnimNS_Slash_parameters.hpp"


SDK_NAMESPACE_START

// Function AnimNS_Slash.AnimNS_Slash_C.Received_Notify
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class USkeletalMeshComponent*           MeshComp_Received_Notify                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class UAnimSequenceBase*                Animation_Received_Notify                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FAnimNotifyEventReference& EventReference_Received_Notify                         (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// bool                                    ReturnValue_Received_Notify                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UAnimNS_Slash_C::Received_Notify(class USkeletalMeshComponent* MeshComp_Received_Notify, class UAnimSequenceBase* Animation_Received_Notify, const struct FAnimNotifyEventReference& EventReference_Received_Notify) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimNS_Slash_C", "Received_Notify");

	Params::AnimNS_Slash_C_Received_Notify Parms{};

	Parms.MeshComp_Received_Notify = MeshComp_Received_Notify;
	Parms.Animation_Received_Notify = Animation_Received_Notify;
	Parms.EventReference_Received_Notify = std::move(EventReference_Received_Notify);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
