#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BFL_FindAppropriateFoliageAkEvent

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BFL_FindAppropriateFoliageAkEvent.BFL_FindAppropriateFoliageAkEvent_C
// 0x0000 (0x0028 - 0x0028)
class UBFL_FindAppropriateFoliageAkEvent_C final : public UBlueprintFunctionLibrary
{
public:
	static void Find_Appropriate_Foliage_Ak_Audio_Event(class UMaterialInterface* Material_Instance, class UBP_FoliageMICategoryData_C* Foliage_Categories_Data_Asset, class UObject* __WorldContext, class UAkAudioEvent** Ak_Audio_Event);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BFL_FindAppropriateFoliageAkEvent_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BFL_FindAppropriateFoliageAkEvent_C")
	}
	static class UBFL_FindAppropriateFoliageAkEvent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBFL_FindAppropriateFoliageAkEvent_C>();
	}
};
DUMPER7_ASSERTS_UBFL_FindAppropriateFoliageAkEvent_C;

SDK_NAMESPACE_END
