#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AudioParameterSplineMapActorBase

#include "Basic.hpp"

#include "BP_AudioParameterSplineMapActorBase_classes.hpp"
#include "BP_AudioParameterSplineMapActorBase_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_AudioParameterSplineMapActorBase.BP_AudioParameterSplineMapActorBase_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_AudioParameterSplineMapActorBase_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AudioParameterSplineMapActorBase_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AudioParameterSplineMapActorBase.BP_AudioParameterSplineMapActorBase_C.SetPathPoints
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_AudioParameterSplineMapActorBase_C::SetPathPoints()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AudioParameterSplineMapActorBase_C", "SetPathPoints");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AudioParameterSplineMapActorBase.BP_AudioParameterSplineMapActorBase_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_AudioParameterSplineMapActorBase_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AudioParameterSplineMapActorBase_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AudioParameterSplineMapActorBase.BP_AudioParameterSplineMapActorBase_C.ExecuteUbergraph_BP_AudioParameterSplineMapActorBase
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_AudioParameterSplineMapActorBase_C::ExecuteUbergraph_BP_AudioParameterSplineMapActorBase(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AudioParameterSplineMapActorBase_C", "ExecuteUbergraph_BP_AudioParameterSplineMapActorBase");

	Params::BP_AudioParameterSplineMapActorBase_C_ExecuteUbergraph_BP_AudioParameterSplineMapActorBase Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
