#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BabyPig

#include "Basic.hpp"

#include "BP_MobCharacter_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_BabyPig.BP_BabyPig_C
// 0x0000 (0x0B20 - 0x0B20)
class ABP_BabyPig_C final : public ABP_MobCharacter_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_BabyPig_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_BabyPig_C")
	}
	static class ABP_BabyPig_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_BabyPig_C>();
	}
};
DUMPER7_ASSERTS_ABP_BabyPig_C;

SDK_NAMESPACE_END
