#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CaveCrawlerChest_Unique

#include "Basic.hpp"

#include "SWCoreGameplay_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_CaveCrawlerChest_Unique.BP_CaveCrawlerChest_Unique_C
// 0x0020 (0x02F8 - 0x02D8)
class ABP_CaveCrawlerChest_Unique_C final : public AGearActor
{
public:
	class UInstancedStaticMeshComponent*          Chest_Storable;                                    // 0x02D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   R_ShoulderPad_DarkArmor;                           // 0x02E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   L_ShoulderPad_DarkArmor;                           // 0x02E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   DarkArmor_DarkArmor;                               // 0x02F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_CaveCrawlerChest_Unique_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CaveCrawlerChest_Unique_C")
	}
	static class ABP_CaveCrawlerChest_Unique_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_CaveCrawlerChest_Unique_C>();
	}
};
DUMPER7_ASSERTS_ABP_CaveCrawlerChest_Unique_C;

SDK_NAMESPACE_END
