#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MerchantPocketStage

#include "Basic.hpp"

#include "Angelscript_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_MerchantPocketStage.BP_MerchantPocketStage_C
// 0x0000 (0x03E8 - 0x03E8)
class ABP_MerchantPocketStage_C final : public AAS_MerchantPocketStage
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_MerchantPocketStage_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_MerchantPocketStage_C")
	}
	static class ABP_MerchantPocketStage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_MerchantPocketStage_C>();
	}
};
DUMPER7_ASSERTS_ABP_MerchantPocketStage_C;

SDK_NAMESPACE_END
