#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PlayerHUD

#include "Basic.hpp"

#include "Angelscript_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_PlayerHUD.BP_PlayerHUD_C
// 0x0008 (0x03A0 - 0x0398)
class ABP_PlayerHUD_C final : public AAS_SpicewoodHUD
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0398(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PlayerHUD_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PlayerHUD_C")
	}
	static class ABP_PlayerHUD_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PlayerHUD_C>();
	}
};
DUMPER7_ASSERTS_ABP_PlayerHUD_C;

SDK_NAMESPACE_END
