#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SpicewoodTeleportDoor_VisualAsset_RiftMaster

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_SpicewoodTeleportDoor_VisualAsset_RiftMaster.BP_SpicewoodTeleportDoor_VisualAsset_RiftMaster_C.SetDoorIsOpen
// 0x0002 (0x0002 - 0x0000)
struct BP_SpicewoodTeleportDoor_VisualAsset_RiftMaster_C_SetDoorIsOpen final
{
public:
	bool                                          bIsOpen;                                           // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsInstantTransition;                              // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_SpicewoodTeleportDoor_VisualAsset_RiftMaster_C_SetDoorIsOpen;

// Function BP_SpicewoodTeleportDoor_VisualAsset_RiftMaster.BP_SpicewoodTeleportDoor_VisualAsset_RiftMaster_C.ExecuteUbergraph_BP_SpicewoodTeleportDoor_VisualAsset_RiftMaster
// 0x0008 (0x0008 - 0x0000)
struct BP_SpicewoodTeleportDoor_VisualAsset_RiftMaster_C_ExecuteUbergraph_BP_SpicewoodTeleportDoor_VisualAsset_RiftMaster final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bIsOpen;                              // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bIsInstantTransition;                 // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_SpicewoodTeleportDoor_VisualAsset_RiftMaster_C_ExecuteUbergraph_BP_SpicewoodTeleportDoor_VisualAsset_RiftMaster;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
