#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_StoneSecretDoorActorStateGimmick

#include "Basic.hpp"

#include "BP_SecretBlockerActorStateGimmick_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_StoneSecretDoorActorStateGimmick.BP_StoneSecretDoorActorStateGimmick_C
// 0x0008 (0x0498 - 0x0490)
class ABP_StoneSecretDoorActorStateGimmick_C final : public ABP_SecretBlockerActorStateGimmick_C
{
public:
	class UNiagaraComponent*                      NS_PusherDustTrail;                                // 0x0490(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_StoneSecretDoorActorStateGimmick_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_StoneSecretDoorActorStateGimmick_C")
	}
	static class ABP_StoneSecretDoorActorStateGimmick_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_StoneSecretDoorActorStateGimmick_C>();
	}
};
DUMPER7_ASSERTS_ABP_StoneSecretDoorActorStateGimmick_C;

SDK_NAMESPACE_END
