#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SpicewoodRichTextBlockInputActionDecorator

#include "Basic.hpp"

#include "SpicewoodUI_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_SpicewoodRichTextBlockInputActionDecorator.BP_SpicewoodRichTextBlockInputActionDecorator_C
// 0x0000 (0x0048 - 0x0048)
class UBP_SpicewoodRichTextBlockInputActionDecorator_C final : public USpicewoodRichTextBlockInputActionDecorator
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SpicewoodRichTextBlockInputActionDecorator_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SpicewoodRichTextBlockInputActionDecorator_C")
	}
	static class UBP_SpicewoodRichTextBlockInputActionDecorator_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_SpicewoodRichTextBlockInputActionDecorator_C>();
	}
};
DUMPER7_ASSERTS_UBP_SpicewoodRichTextBlockInputActionDecorator_C;

SDK_NAMESPACE_END
