#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SpicewoodTeleportDoor_VisualAsset_DungeonEntrance

#include "Basic.hpp"

#include "BP_SpicewoodTeleportDoor_VisualAsset_DungeonEntrance_classes.hpp"
#include "BP_SpicewoodTeleportDoor_VisualAsset_DungeonEntrance_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_SpicewoodTeleportDoor_VisualAsset_DungeonEntrance.BP_SpicewoodTeleportDoor_VisualAsset_DungeonEntrance_C.SetDoorIsOpen
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    bIsOpen                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsInstantTransition                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SpicewoodTeleportDoor_VisualAsset_DungeonEntrance_C::SetDoorIsOpen(bool bIsOpen, bool bIsInstantTransition)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SpicewoodTeleportDoor_VisualAsset_DungeonEntrance_C", "SetDoorIsOpen");

	Params::BP_SpicewoodTeleportDoor_VisualAsset_DungeonEntrance_C_SetDoorIsOpen Parms{};

	Parms.bIsOpen = bIsOpen;
	Parms.bIsInstantTransition = bIsInstantTransition;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SpicewoodTeleportDoor_VisualAsset_DungeonEntrance.BP_SpicewoodTeleportDoor_VisualAsset_DungeonEntrance_C.ExecuteUbergraph_BP_SpicewoodTeleportDoor_VisualAsset_DungeonEntrance
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SpicewoodTeleportDoor_VisualAsset_DungeonEntrance_C::ExecuteUbergraph_BP_SpicewoodTeleportDoor_VisualAsset_DungeonEntrance(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SpicewoodTeleportDoor_VisualAsset_DungeonEntrance_C", "ExecuteUbergraph_BP_SpicewoodTeleportDoor_VisualAsset_DungeonEntrance");

	Params::BP_SpicewoodTeleportDoor_VisualAsset_DungeonEntrance_C_ExecuteUbergraph_BP_SpicewoodTeleportDoor_VisualAsset_DungeonEntrance Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
