#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TeleportDoor

#include "Basic.hpp"

#include "SWCoreGameplay_structs.hpp"
#include "MSAudioRuntime_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_TeleportDoor.BP_TeleportDoor_C.PostTeleporterInteractionAudio
// 0x0008 (0x0008 - 0x0000)
struct BP_TeleportDoor_C_PostTeleporterInteractionAudio final
{
public:
	const class AActor*                           InstigatingActor;                                  // 0x0000(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_TeleportDoor_C_PostTeleporterInteractionAudio;

// Function BP_TeleportDoor.BP_TeleportDoor_C.ExecuteUbergraph_BP_TeleportDoor
// 0x0060 (0x0060 - 0x0000)
struct BP_TeleportDoor_C_ExecuteUbergraph_BP_TeleportDoor final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(int32 PlayingID, EMSAudioCallbackType CallbackType)> Temp_delegate_Variable;      // 0x0004(0x0010)(ConstParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FActorHighlightMessage                 K2Node_ComponentBoundEvent_Message;                // 0x0018(0x0020)(ConstParm, NoDestructor)
	const class AActor*                           K2Node_Event_InstigatingActor;                     // 0x0038(0x0008)(ConstParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(int32 PlayingID, EMSAudioCallbackType CallbackType)> Temp_delegate_Variable_1;    // 0x0040(0x0010)(ConstParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_51[0x3];                                       // 0x0051(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_PostEvent_ReturnValue;                    // 0x0054(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_PostEvent_ReturnValue_1;                  // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_TeleportDoor_C_ExecuteUbergraph_BP_TeleportDoor;

// Function BP_TeleportDoor.BP_TeleportDoor_C.BndEvt__BP_TeleportDoor_AbilitySystemComponent_K2Node_ComponentBoundEvent_0_OnActorHighlightStatusChanged__DelegateSignature
// 0x0020 (0x0020 - 0x0000)
struct BP_TeleportDoor_C_BndEvt__BP_TeleportDoor_AbilitySystemComponent_K2Node_ComponentBoundEvent_0_OnActorHighlightStatusChanged__DelegateSignature final
{
public:
	struct FActorHighlightMessage                 Message;                                           // 0x0000(0x0020)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
};
DUMPER7_ASSERTS_BP_TeleportDoor_C_BndEvt__BP_TeleportDoor_AbilitySystemComponent_K2Node_ComponentBoundEvent_0_OnActorHighlightStatusChanged__DelegateSignature;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
