#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_WoodLantern_Lit2

#include "Basic.hpp"

#include "BP_WoodLantern_Lit2_classes.hpp"
#include "BP_WoodLantern_Lit2_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_WoodLantern_Lit2.BP_WoodLantern_Lit2_C.ExecuteUbergraph_BP_WoodLantern_Lit2
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_WoodLantern_Lit2_C::ExecuteUbergraph_BP_WoodLantern_Lit2(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_WoodLantern_Lit2_C", "ExecuteUbergraph_BP_WoodLantern_Lit2");

	Params::BP_WoodLantern_Lit2_C_ExecuteUbergraph_BP_WoodLantern_Lit2 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_WoodLantern_Lit2.BP_WoodLantern_Lit2_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_WoodLantern_Lit2_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_WoodLantern_Lit2_C", "ReceiveTick");

	Params::BP_WoodLantern_Lit2_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_WoodLantern_Lit2.BP_WoodLantern_Lit2_C.Start  Random Timer
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_WoodLantern_Lit2_C::Start__Random_Timer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_WoodLantern_Lit2_C", "Start  Random Timer");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
