#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FeatureToggle

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"
#include "FeatureToggle_structs.hpp"
#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// Class FeatureToggle.FeatureToggle
// 0x0018 (0x0040 - 0x0028)
class UFeatureToggle final : public UObject
{
public:
	class UOnlineDataTables*                      OnlineDataTables;                                  // 0x0028(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate, TObjectPtr)
	uint8                                         Pad_30[0x10];                                      // 0x0030(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static bool IsActive(EFeature Feature);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("FeatureToggle")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FeatureToggle")
	}
	static class UFeatureToggle* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFeatureToggle>();
	}
};
DUMPER7_ASSERTS_UFeatureToggle;

// Class FeatureToggle.FeatureToggleSubsystem
// 0x0008 (0x0038 - 0x0030)
class UFeatureToggleSubsystem final : public UEngineSubsystem
{
public:
	class UFeatureToggle*                         FeatureToggle;                                     // 0x0030(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate, TObjectPtr)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("FeatureToggleSubsystem")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FeatureToggleSubsystem")
	}
	static class UFeatureToggleSubsystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFeatureToggleSubsystem>();
	}
};
DUMPER7_ASSERTS_UFeatureToggleSubsystem;

// Class FeatureToggle.ReleaseToggleSetupSubsystem
// 0x0000 (0x0030 - 0x0030)
class UReleaseToggleSetupSubsystem final : public UWorldSubsystem
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ReleaseToggleSetupSubsystem")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ReleaseToggleSetupSubsystem")
	}
	static class UReleaseToggleSetupSubsystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<UReleaseToggleSetupSubsystem>();
	}
};
DUMPER7_ASSERTS_UReleaseToggleSetupSubsystem;

// Class FeatureToggle.ReleaseToggleUtils
// 0x0000 (0x0028 - 0x0028)
class UReleaseToggleUtils final : public UBlueprintFunctionLibrary
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ReleaseToggleUtils")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ReleaseToggleUtils")
	}
	static class UReleaseToggleUtils* GetDefaultObj()
	{
		return GetDefaultObjImpl<UReleaseToggleUtils>();
	}
};
DUMPER7_ASSERTS_UReleaseToggleUtils;

SDK_NAMESPACE_END
