#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GlobalSave

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "CoreUObject_classes.hpp"


SDK_NAMESPACE_START

// Class GlobalSave.GlobalSaveFunctionLibrary
// 0x0000 (0x0028 - 0x0028)
class UGlobalSaveFunctionLibrary final : public UBlueprintFunctionLibrary
{
public:
	static bool GetHasConfirmedDeluxeEditionDialog(const class ULocalPlayer* LocalPlayer, bool* bOutHasConfirmed);
	static bool GetHasConfirmedPreOrderDialog(const class ULocalPlayer* LocalPlayer, bool* bOutHasConfirmed);
	static bool GetHasConfirmedReturningHeroDialog(const class ULocalPlayer* LocalPlayer, bool* bOutHasConfirmed);
	static void SetHasConfirmedDeluxeEditionDialog(const class ULocalPlayer* LocalPlayer, bool bInHasConfirmed);
	static void SetHasConfirmedPreOrderDialog(const class ULocalPlayer* LocalPlayer, bool bInHasConfirmed);
	static void SetHasConfirmedReturningHeroDialog(const class ULocalPlayer* LocalPlayer, bool bInHasConfirmed);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("GlobalSaveFunctionLibrary")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GlobalSaveFunctionLibrary")
	}
	static class UGlobalSaveFunctionLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGlobalSaveFunctionLibrary>();
	}
};
DUMPER7_ASSERTS_UGlobalSaveFunctionLibrary;

// Class GlobalSave.GlobalSaveGameContainer
// 0x0378 (0x03A0 - 0x0028)
class UGlobalSaveGameContainer final : public UObject
{
public:
	uint8                                         Pad_28[0x378];                                     // 0x0028(0x0378)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("GlobalSaveGameContainer")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GlobalSaveGameContainer")
	}
	static class UGlobalSaveGameContainer* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGlobalSaveGameContainer>();
	}
};
DUMPER7_ASSERTS_UGlobalSaveGameContainer;

// Class GlobalSave.PlayerGlobalSaveInterface
// 0x0060 (0x0088 - 0x0028)
class UPlayerGlobalSaveInterface final : public UObject
{
public:
	uint8                                         Pad_28[0x60];                                      // 0x0028(0x0060)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PlayerGlobalSaveInterface")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PlayerGlobalSaveInterface")
	}
	static class UPlayerGlobalSaveInterface* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPlayerGlobalSaveInterface>();
	}
};
DUMPER7_ASSERTS_UPlayerGlobalSaveInterface;

// Class GlobalSave.PlayerGlobalSaveInterfaceSubsystem
// 0x0008 (0x0038 - 0x0030)
class UPlayerGlobalSaveInterfaceSubsystem final : public UGameInstanceSubsystem
{
public:
	class UPlayerGlobalSaveInterface*             PlayerGlobalSaveInterface;                         // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PlayerGlobalSaveInterfaceSubsystem")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PlayerGlobalSaveInterfaceSubsystem")
	}
	static class UPlayerGlobalSaveInterfaceSubsystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPlayerGlobalSaveInterfaceSubsystem>();
	}
};
DUMPER7_ASSERTS_UPlayerGlobalSaveInterfaceSubsystem;

SDK_NAMESPACE_END
