#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OnlineDataTables

#include "Basic.hpp"

#include "OnlineDataTables_structs.hpp"
#include "CoreUObject_classes.hpp"
#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// Class OnlineDataTables.OnlineDataTables
// 0x00C0 (0x00E8 - 0x0028)
class UOnlineDataTables : public UObject
{
public:
	uint8                                         Pad_28[0x28];                                      // 0x0028(0x0028)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FOnlineData>                    OnlineDataTables;                                  // 0x0050(0x0010)(ZeroConstructor, NativeAccessSpecifierPrivate)
	TArray<struct FOnlineData>                    BundledDataTables;                                 // 0x0060(0x0010)(ZeroConstructor, NativeAccessSpecifierPrivate)
	TArray<class UObject*>                        ODTPackageManifestRefs;                            // 0x0070(0x0010)(ZeroConstructor, UObjectWrapper, NativeAccessSpecifierPrivate, TObjectPtr)
	uint8                                         Pad_80[0x68];                                      // 0x0080(0x0068)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void SetTableSource(EOnlineDataTableSource Source);

	class FText GetStatusResult() const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OnlineDataTables")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OnlineDataTables")
	}
	static class UOnlineDataTables* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOnlineDataTables>();
	}
};
DUMPER7_ASSERTS_UOnlineDataTables;

// Class OnlineDataTables.TestOnlineDataTables
// 0x0000 (0x00E8 - 0x00E8)
class UTestOnlineDataTables final : public UOnlineDataTables
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("TestOnlineDataTables")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TestOnlineDataTables")
	}
	static class UTestOnlineDataTables* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTestOnlineDataTables>();
	}
};
DUMPER7_ASSERTS_UTestOnlineDataTables;

// Class OnlineDataTables.OnlineDataTablesSaveGame
// 0x0020 (0x0048 - 0x0028)
class UOnlineDataTablesSaveGame final : public USaveGame
{
public:
	class FString                                 ClientVersion;                                     // 0x0028(0x0010)(ZeroConstructor, SaveGame, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FOnlineDataTableSave>           Tables;                                            // 0x0038(0x0010)(ZeroConstructor, SaveGame, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OnlineDataTablesSaveGame")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OnlineDataTablesSaveGame")
	}
	static class UOnlineDataTablesSaveGame* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOnlineDataTablesSaveGame>();
	}
};
DUMPER7_ASSERTS_UOnlineDataTablesSaveGame;

// Class OnlineDataTables.SWODTDataParent
// 0x0020 (0x0048 - 0x0028)
class USWODTDataParent final : public UObject
{
public:
	TArray<class UDataTable*>                     ODTs;                                              // 0x0028(0x0010)(ZeroConstructor, Protected, UObjectWrapper, NativeAccessSpecifierProtected, TObjectPtr)
	uint8                                         Pad_38[0x10];                                      // 0x0038(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	bool ClusterTick(float Val);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SWODTDataParent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SWODTDataParent")
	}
	static class USWODTDataParent* GetDefaultObj()
	{
		return GetDefaultObjImpl<USWODTDataParent>();
	}
};
DUMPER7_ASSERTS_USWODTDataParent;

// Class OnlineDataTables.SWODTDataTable
// 0x0000 (0x00B0 - 0x00B0)
class USWODTDataTable : public UDataTable
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SWODTDataTable")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SWODTDataTable")
	}
	static class USWODTDataTable* GetDefaultObj()
	{
		return GetDefaultObjImpl<USWODTDataTable>();
	}
};
DUMPER7_ASSERTS_USWODTDataTable;

// Class OnlineDataTables.DeserialisedODTDataTable
// 0x0000 (0x00B0 - 0x00B0)
class UDeserialisedODTDataTable final : public USWODTDataTable
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("DeserialisedODTDataTable")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DeserialisedODTDataTable")
	}
	static class UDeserialisedODTDataTable* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDeserialisedODTDataTable>();
	}
};
DUMPER7_ASSERTS_UDeserialisedODTDataTable;

// Class OnlineDataTables.OnlineDataTablesEngineSubsystem
// 0x0008 (0x0038 - 0x0030)
class UOnlineDataTablesEngineSubsystem final : public UEngineSubsystem
{
public:
	class UOnlineDataTables*                      OnlineDataTables;                                  // 0x0030(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate, TObjectPtr)

public:
	class UOnlineDataTables* Get() const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OnlineDataTablesEngineSubsystem")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OnlineDataTablesEngineSubsystem")
	}
	static class UOnlineDataTablesEngineSubsystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOnlineDataTablesEngineSubsystem>();
	}
};
DUMPER7_ASSERTS_UOnlineDataTablesEngineSubsystem;

// Class OnlineDataTables.OnlineDataTablesPlayer
// 0x0070 (0x0098 - 0x0028)
class UOnlineDataTablesPlayer final : public UObject
{
public:
	uint8                                         Pad_28[0x10];                                      // 0x0028(0x0010)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void()>              OnRefreshOnlineTables;                             // 0x0038(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	uint8                                         Pad_48[0x28];                                      // 0x0048(0x0028)(Fixing Size After Last Property [ Dumper-7 ])
	class UOnlineDataTables*                      OnlineDataTables;                                  // 0x0070(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate, TObjectPtr)
	uint8                                         Pad_78[0x20];                                      // 0x0078(0x0020)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void RefreshOnlineTables();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OnlineDataTablesPlayer")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OnlineDataTablesPlayer")
	}
	static class UOnlineDataTablesPlayer* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOnlineDataTablesPlayer>();
	}
};
DUMPER7_ASSERTS_UOnlineDataTablesPlayer;

// Class OnlineDataTables.OnlineDataTablesLocalPlayer
// 0x0008 (0x0038 - 0x0030)
class UOnlineDataTablesLocalPlayer final : public ULocalPlayerSubsystem
{
public:
	class UOnlineDataTablesPlayer*                OnlineDataTables;                                  // 0x0030(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate, TObjectPtr)

public:
	class UOnlineDataTablesPlayer* Get() const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OnlineDataTablesLocalPlayer")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OnlineDataTablesLocalPlayer")
	}
	static class UOnlineDataTablesLocalPlayer* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOnlineDataTablesLocalPlayer>();
	}
};
DUMPER7_ASSERTS_UOnlineDataTablesLocalPlayer;

// Class OnlineDataTables.ServerOnlineDataTables
// 0x0058 (0x0080 - 0x0028)
class UServerOnlineDataTables final : public UObject
{
public:
	uint8                                         Pad_28[0x30];                                      // 0x0028(0x0030)(Fixing Size After Last Property [ Dumper-7 ])
	class UOnlineDataTables*                      OnlineDataTables;                                  // 0x0058(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate, TObjectPtr)
	uint8                                         Pad_60[0x20];                                      // 0x0060(0x0020)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ServerOnlineDataTables")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ServerOnlineDataTables")
	}
	static class UServerOnlineDataTables* GetDefaultObj()
	{
		return GetDefaultObjImpl<UServerOnlineDataTables>();
	}
};
DUMPER7_ASSERTS_UServerOnlineDataTables;

// Class OnlineDataTables.ServerOnlineDataTablesSubsystem
// 0x0008 (0x0038 - 0x0030)
class UServerOnlineDataTablesSubsystem final : public UGameInstanceSubsystem
{
public:
	class UServerOnlineDataTables*                ServerOnlineDataTables;                            // 0x0030(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate, TObjectPtr)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ServerOnlineDataTablesSubsystem")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ServerOnlineDataTablesSubsystem")
	}
	static class UServerOnlineDataTablesSubsystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<UServerOnlineDataTablesSubsystem>();
	}
};
DUMPER7_ASSERTS_UServerOnlineDataTablesSubsystem;

SDK_NAMESPACE_END
