#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PocketWorlds

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function PocketWorlds.PocketCaptureSubsystem.DestroyThumbnailRenderer
// 0x0008 (0x0008 - 0x0000)
struct PocketCaptureSubsystem_DestroyThumbnailRenderer final
{
public:
	class UPocketCapture*                         ThumbnailRenderer;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_PocketCaptureSubsystem_DestroyThumbnailRenderer;

// Function PocketWorlds.PocketCaptureSubsystem.GetOrCreateThumbnailRenderer
// 0x0010 (0x0010 - 0x0000)
struct PocketCaptureSubsystem_GetOrCreateThumbnailRenderer final
{
public:
	TSubclassOf<class UPocketCapture>             PocketCaptureClass;                                // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UPocketCapture*                         ReturnValue;                                       // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_PocketCaptureSubsystem_GetOrCreateThumbnailRenderer;

// Function PocketWorlds.PocketCapture.AddCapture
// 0x0010 (0x0010 - 0x0000)
struct PocketCapture_AddCapture final
{
public:
	const class UObject*                          Widget;                                            // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_PocketCapture_AddCapture;

// Function PocketWorlds.PocketCapture.GetOrCreateAlphaMaskRenderTarget
// 0x0008 (0x0008 - 0x0000)
struct PocketCapture_GetOrCreateAlphaMaskRenderTarget final
{
public:
	class UTextureRenderTarget2D*                 ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_PocketCapture_GetOrCreateAlphaMaskRenderTarget;

// Function PocketWorlds.PocketCapture.GetOrCreateDiffuseRenderTarget
// 0x0008 (0x0008 - 0x0000)
struct PocketCapture_GetOrCreateDiffuseRenderTarget final
{
public:
	class UTextureRenderTarget2D*                 ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_PocketCapture_GetOrCreateDiffuseRenderTarget;

// Function PocketWorlds.PocketCapture.GetOrCreateEffectsRenderTarget
// 0x0008 (0x0008 - 0x0000)
struct PocketCapture_GetOrCreateEffectsRenderTarget final
{
public:
	class UTextureRenderTarget2D*                 ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_PocketCapture_GetOrCreateEffectsRenderTarget;

// Function PocketWorlds.PocketCapture.RemoveCapture
// 0x0010 (0x0010 - 0x0000)
struct PocketCapture_RemoveCapture final
{
public:
	const class UObject*                          Widget;                                            // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_PocketCapture_RemoveCapture;

// Function PocketWorlds.PocketCapture.SetAlphaMaskedActors
// 0x0010 (0x0010 - 0x0000)
struct PocketCapture_SetAlphaMaskedActors final
{
public:
	TArray<class AActor*>                         InCaptureTarget;                                   // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_PocketCapture_SetAlphaMaskedActors;

// Function PocketWorlds.PocketCapture.SetCaptureTarget
// 0x0008 (0x0008 - 0x0000)
struct PocketCapture_SetCaptureTarget final
{
public:
	class AActor*                                 InCaptureTarget;                                   // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_PocketCapture_SetCaptureTarget;

// Function PocketWorlds.PocketCapture.SetRenderTargetSize
// 0x0008 (0x0008 - 0x0000)
struct PocketCapture_SetRenderTargetSize final
{
public:
	int32                                         Width;                                             // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Height;                                            // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_PocketCapture_SetRenderTargetSize;

// Function PocketWorlds.PocketCapture.GetHasRenderedThisFrame
// 0x0001 (0x0001 - 0x0000)
struct PocketCapture_GetHasRenderedThisFrame final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_PocketCapture_GetHasRenderedThisFrame;

// Function PocketWorlds.PocketCapture.GetRendererIndex
// 0x0004 (0x0004 - 0x0000)
struct PocketCapture_GetRendererIndex final
{
public:
	int32                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_PocketCapture_GetRendererIndex;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
