#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: QualityLevelSwitch

#include "Basic.hpp"

#include "QualityLevelSwitch_classes.hpp"
#include "QualityLevelSwitch_parameters.hpp"


SDK_NAMESPACE_START

// Function QualityLevelSwitch.QualityLevelSwitch_C.ReceiveBeginPlay
// (Event, Public, BlueprintEvent)

void UQualityLevelSwitch_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("QualityLevelSwitch_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function QualityLevelSwitch.QualityLevelSwitch_C.OnMessageReceived_D48A620D4263937347A7BD86B522FE1C
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAsyncAction_ListenForGameplayMessage*ProxyObject                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayTag&              ActualChannel                                          (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UQualityLevelSwitch_C::OnMessageReceived_D48A620D4263937347A7BD86B522FE1C(class UAsyncAction_ListenForGameplayMessage* ProxyObject, const struct FGameplayTag& ActualChannel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("QualityLevelSwitch_C", "OnMessageReceived_D48A620D4263937347A7BD86B522FE1C");

	Params::QualityLevelSwitch_C_OnMessageReceived_D48A620D4263937347A7BD86B522FE1C Parms{};

	Parms.ProxyObject = ProxyObject;
	Parms.ActualChannel = std::move(ActualChannel);

	UObject::ProcessEvent(Func, &Parms);
}


// Function QualityLevelSwitch.QualityLevelSwitch_C.ExecuteUbergraph_QualityLevelSwitch
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UQualityLevelSwitch_C::ExecuteUbergraph_QualityLevelSwitch(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("QualityLevelSwitch_C", "ExecuteUbergraph_QualityLevelSwitch");

	Params::QualityLevelSwitch_C_ExecuteUbergraph_QualityLevelSwitch Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
