#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: QuestsFeature

#include "Basic.hpp"

#include "QuestsFeature_structs.hpp"
#include "QuestTypes_structs.hpp"
#include "SWCorePayloads_structs.hpp"
#include "SWCoreGameplay_structs.hpp"
#include "UIStateContainer_structs.hpp"
#include "GameplayTags_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function QuestsFeature.BaseTask.ProcessTrigger
// 0x0060 (0x0060 - 0x0000)
struct BaseTask_ProcessTrigger final
{
public:
	struct FQuestEventParams                      eventParams;                                       // 0x0000(0x0048)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	TArray<class FString>                         resultTags;                                        // 0x0048(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0058(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_59[0x7];                                       // 0x0059(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_BaseTask_ProcessTrigger;

// Function QuestsFeature.BaseTask.GetGoalName
// 0x0008 (0x0008 - 0x0000)
struct BaseTask_GetGoalName final
{
public:
	class FName                                   ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BaseTask_GetGoalName;

// Function QuestsFeature.BaseTask.GetQuestParent
// 0x0008 (0x0008 - 0x0000)
struct BaseTask_GetQuestParent final
{
public:
	class ULiveQuest*                             ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BaseTask_GetQuestParent;

// Function QuestsFeature.BaseTask.GetState
// 0x0001 (0x0001 - 0x0000)
struct BaseTask_GetState final
{
public:
	EQuestTaskState                               ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BaseTask_GetState;

// Function QuestsFeature.BaseTask.GetUiInfo
// 0x0020 (0x0020 - 0x0000)
struct BaseTask_GetUiInfo final
{
public:
	struct FQuestTaskUiInfo                       ReturnValue;                                       // 0x0000(0x0020)(Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BaseTask_GetUiInfo;

// Function QuestsFeature.BaseTask.GetUILabel
// 0x0010 (0x0010 - 0x0000)
struct BaseTask_GetUILabel final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0010)(ConstParm, Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BaseTask_GetUILabel;

// Function QuestsFeature.LiveQuest.GetQuestTask
// 0x0010 (0x0010 - 0x0000)
struct LiveQuest_GetQuestTask final
{
public:
	class FName                                   Name_0;                                            // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UQuestTask*                             ReturnValue;                                       // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_LiveQuest_GetQuestTask;

// Function QuestsFeature.LiveQuest.GetQuestTaskHierarchy
// 0x0018 (0x0018 - 0x0000)
struct LiveQuest_GetQuestTaskHierarchy final
{
public:
	class FName                                   TaskID;                                            // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class UQuestTask*>                     ReturnValue;                                       // 0x0008(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_LiveQuest_GetQuestTaskHierarchy;

// Function QuestsFeature.LiveQuest.GetState
// 0x0001 (0x0001 - 0x0000)
struct LiveQuest_GetState final
{
public:
	EQuestState                                   ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_LiveQuest_GetState;

// Function QuestsFeature.LiveQuest.GetTasksWithState
// 0x0018 (0x0018 - 0x0000)
struct LiveQuest_GetTasksWithState final
{
public:
	EQuestTaskState                               State_0;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UQuestTask*>                     ReturnValue;                                       // 0x0008(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_LiveQuest_GetTasksWithState;

// Function QuestsFeature.LiveQuest.GetUILabel
// 0x0010 (0x0010 - 0x0000)
struct LiveQuest_GetUILabel final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0010)(ConstParm, Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_LiveQuest_GetUILabel;

// Function QuestsFeature.DialogueActionLibrary.ContinueDialogue
// 0x0068 (0x0068 - 0x0000)
struct DialogueActionLibrary_ContinueDialogue final
{
public:
	const class ULocalPlayer*                     LocalPlayer;                                       // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FDialogueSegmentData                   dialogueSegment;                                   // 0x0008(0x0040)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	bool                                          IsFinishingSegment;                                // 0x0048(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          isQuestCompleteSegment;                            // 0x0049(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4A[0x6];                                       // 0x004A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAction                                ReturnValue;                                       // 0x0050(0x0018)(Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_DialogueActionLibrary_ContinueDialogue;

// Function QuestsFeature.DialogueActionLibrary.EndDialogue
// 0x0020 (0x0020 - 0x0000)
struct DialogueActionLibrary_EndDialogue final
{
public:
	const class ULocalPlayer*                     LocalPlayer;                                       // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FAction                                ReturnValue;                                       // 0x0008(0x0018)(Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_DialogueActionLibrary_EndDialogue;

// Function QuestsFeature.DialogueActionLibrary.SkipDialogue
// 0x0020 (0x0020 - 0x0000)
struct DialogueActionLibrary_SkipDialogue final
{
public:
	const class ULocalPlayer*                     LocalPlayer;                                       // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FAction                                ReturnValue;                                       // 0x0008(0x0018)(Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_DialogueActionLibrary_SkipDialogue;

// Function QuestsFeature.DialogueActionLibrary.StartDialogue
// 0x0068 (0x0068 - 0x0000)
struct DialogueActionLibrary_StartDialogue final
{
public:
	const class ULocalPlayer*                     LocalPlayer;                                       // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FDialogueSegmentData                   dialogueSegment;                                   // 0x0008(0x0040)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	bool                                          IsFinishingSegment;                                // 0x0048(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          isQuestCompleteSegment;                            // 0x0049(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4A[0x6];                                       // 0x004A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAction                                ReturnValue;                                       // 0x0050(0x0018)(Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_DialogueActionLibrary_StartDialogue;

// Function QuestsFeature.EmotionUtil.PlayEmotionOnCharacter
// 0x0010 (0x0010 - 0x0000)
struct EmotionUtil_PlayEmotionOnCharacter final
{
public:
	const class ACharacter*                       Character;                                         // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           emotion;                                           // 0x0008(0x0008)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_EmotionUtil_PlayEmotionOnCharacter;

// Function QuestsFeature.QuestActionLibrary.PlayerTrackedQuestUpdated
// 0x0038 (0x0038 - 0x0000)
struct QuestActionLibrary_PlayerTrackedQuestUpdated final
{
public:
	class FString                                 questId;                                           // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FUIPlayerIDHandle                      PlayerIDHandle;                                    // 0x0010(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FAction                                ReturnValue;                                       // 0x0020(0x0018)(Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_QuestActionLibrary_PlayerTrackedQuestUpdated;

// Function QuestsFeature.QuestActionLibrary.QuestNewContentUnlockedAction
// 0x0020 (0x0020 - 0x0000)
struct QuestActionLibrary_QuestNewContentUnlockedAction final
{
public:
	struct FQuestUnlockBannerData                 unlockBannerData;                                  // 0x0000(0x0004)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAction                                ReturnValue;                                       // 0x0008(0x0018)(Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_QuestActionLibrary_QuestNewContentUnlockedAction;

// Function QuestsFeature.QuestActionLibrary.QuestToastPushAction
// 0x0070 (0x0070 - 0x0000)
struct QuestActionLibrary_QuestToastPushAction final
{
public:
	class FString                                 questId;                                           // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FText                                   questLabel;                                        // 0x0010(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	EQuestType                                    QuestType;                                         // 0x0020(0x0001)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FQuestTaskUiInfo                       Task;                                              // 0x0028(0x0020)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	class FString                                 TaskID;                                            // 0x0048(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FAction                                ReturnValue;                                       // 0x0058(0x0018)(Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_QuestActionLibrary_QuestToastPushAction;

// Function QuestsFeature.QuestActionLibrary.QueueEndGameOnboarding
// 0x0018 (0x0018 - 0x0000)
struct QuestActionLibrary_QueueEndGameOnboarding final
{
public:
	struct FAction                                ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_QuestActionLibrary_QueueEndGameOnboarding;

// Function QuestsFeature.QuestActionLibrary.ShowQuestBanner
// 0x0020 (0x0020 - 0x0000)
struct QuestActionLibrary_ShowQuestBanner final
{
public:
	const class ULiveQuest*                       quest;                                             // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FAction                                ReturnValue;                                       // 0x0008(0x0018)(Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_QuestActionLibrary_ShowQuestBanner;

// Function QuestsFeature.QuestActionLibrary.ShowQuestPanel
// 0x0028 (0x0028 - 0x0000)
struct QuestActionLibrary_ShowQuestPanel final
{
public:
	struct FUIPlayerIDHandle                      PlayerIDHandle;                                    // 0x0000(0x0010)(ConstParm, Parm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FAction                                ReturnValue;                                       // 0x0010(0x0018)(Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_QuestActionLibrary_ShowQuestPanel;

// Function QuestsFeature.QuestActionLibrary.TrackQuest
// 0x0018 (0x0018 - 0x0000)
struct QuestActionLibrary_TrackQuest final
{
public:
	struct FAction                                ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_QuestActionLibrary_TrackQuest;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
