#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: QuestMapMarkers

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function QuestMapMarkers.QuestMapMarkersSubsystem.OnQuestFocusChanged
// 0x0008 (0x0008 - 0x0000)
struct QuestMapMarkersSubsystem_OnQuestFocusChanged final
{
public:
	class ULiveQuest*                             NewFocusQuest;                                     // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_QuestMapMarkersSubsystem_OnQuestFocusChanged;

// Function QuestMapMarkers.QuestMapMarkersSubsystem.OnQuestStateChanged
// 0x0008 (0x0008 - 0x0000)
struct QuestMapMarkersSubsystem_OnQuestStateChanged final
{
public:
	class ULiveQuest*                             quest;                                             // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_QuestMapMarkersSubsystem_OnQuestStateChanged;

// Function QuestMapMarkers.QuestMapMarkersSubsystem.OnTaskStateChanged
// 0x0008 (0x0008 - 0x0000)
struct QuestMapMarkersSubsystem_OnTaskStateChanged final
{
public:
	class UQuestTask*                             Task;                                              // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_QuestMapMarkersSubsystem_OnTaskStateChanged;

// Function QuestMapMarkers.QuestMapMarkersSubsystem.GetQuestId
// 0x0020 (0x0020 - 0x0000)
struct QuestMapMarkersSubsystem_GetQuestId final
{
public:
	class FName                                   MarkerId;                                          // 0x0000(0x0008)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 OutQuestId;                                        // 0x0008(0x0010)(Parm, OutParm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0018(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_QuestMapMarkersSubsystem_GetQuestId;

// Function QuestMapMarkers.QuestMapMarkersSubsystem.GetQuestObjectiveMarkers
// 0x0028 (0x0028 - 0x0000)
struct QuestMapMarkersSubsystem_GetQuestObjectiveMarkers final
{
public:
	class FString                                 questId;                                           // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class FName>                           OutMarkerIds;                                      // 0x0010(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0020(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_QuestMapMarkersSubsystem_GetQuestObjectiveMarkers;

// Function QuestMapMarkers.QuestMapMarkersSubsystem.GetQuestTaskId
// 0x0014 (0x0014 - 0x0000)
struct QuestMapMarkersSubsystem_GetQuestTaskId final
{
public:
	class FName                                   MarkerId;                                          // 0x0000(0x0008)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   OutTaskId;                                         // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x3];                                       // 0x0011(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_QuestMapMarkersSubsystem_GetQuestTaskId;

// Function QuestMapMarkers.QuestMapMarkersSubsystem.IsAreaMarkerId
// 0x0010 (0x0010 - 0x0000)
struct QuestMapMarkersSubsystem_IsAreaMarkerId final
{
public:
	class FName                                   MarkerId;                                          // 0x0000(0x0008)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         OutAreaRadius;                                     // 0x0008(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x000C(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_QuestMapMarkersSubsystem_IsAreaMarkerId;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
