#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ServerDatadogIntegration

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// Class ServerDatadogIntegration.DatadogNamespaceInjector
// 0x0000 (0x0030 - 0x0030)
class UDatadogNamespaceInjector final : public UGameInstanceSubsystem
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("DatadogNamespaceInjector")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DatadogNamespaceInjector")
	}
	static class UDatadogNamespaceInjector* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDatadogNamespaceInjector>();
	}
};
DUMPER7_ASSERTS_UDatadogNamespaceInjector;

SDK_NAMESPACE_END
