#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SessionInvites

#include "Basic.hpp"

#include "SessionInvites_classes.hpp"
#include "SessionInvites_parameters.hpp"


SDK_NAMESPACE_START

// Function SessionInvites.IncomingSessionInvites.AcceptInvite
// (Final, Native, Public)
// Parameters:
// const struct FPlatformUserId&           PlatformUserId                                         (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class FString&                    InviteId                                               (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UIncomingSessionInvites::AcceptInvite(const struct FPlatformUserId& PlatformUserId, const class FString& InviteId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("IncomingSessionInvites", "AcceptInvite");

	Params::IncomingSessionInvites_AcceptInvite Parms{};

	Parms.PlatformUserId = std::move(PlatformUserId);
	Parms.InviteId = std::move(InviteId);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SessionInvites.IncomingSessionInvites.DeclineInvite
// (Final, Native, Public)
// Parameters:
// const struct FPlatformUserId&           PlatformUserId                                         (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class FString&                    InviteId                                               (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UIncomingSessionInvites::DeclineInvite(const struct FPlatformUserId& PlatformUserId, const class FString& InviteId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("IncomingSessionInvites", "DeclineInvite");

	Params::IncomingSessionInvites_DeclineInvite Parms{};

	Parms.PlatformUserId = std::move(PlatformUserId);
	Parms.InviteId = std::move(InviteId);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SessionInvites.IncomingSessionInvites.GetAll
// (Final, Native, Public, Const)
// Parameters:
// TArray<struct FSessionInvite>           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)

TArray<struct FSessionInvite> UIncomingSessionInvites::GetAll() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("IncomingSessionInvites", "GetAll");

	Params::IncomingSessionInvites_GetAll Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SessionInvites.IncomingInviteSubsystem.Get
// (Final, Native, Static, Public)
// Parameters:
// const class UGameInstance*              GameInstance                                           (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UIncomingInviteSubsystem*         ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UIncomingInviteSubsystem* UIncomingInviteSubsystem::Get(const class UGameInstance* GameInstance)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("IncomingInviteSubsystem", "Get");

	Params::IncomingInviteSubsystem_Get Parms{};

	Parms.GameInstance = GameInstance;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SessionInvites.IncomingInviteSubsystem.GetSessionInvites
// (Final, Native, Public, Const)
// Parameters:
// class UIncomingSessionInvites*          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UIncomingSessionInvites* UIncomingInviteSubsystem::GetSessionInvites() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("IncomingInviteSubsystem", "GetSessionInvites");

	Params::IncomingInviteSubsystem_GetSessionInvites Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SessionInvites.OutgoingInviteSubsystem.Get
// (Final, Native, Static, Public)
// Parameters:
// const class ULocalPlayer*               LocalPlayer                                            (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UOutgoingInviteSubsystem*         ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UOutgoingInviteSubsystem* UOutgoingInviteSubsystem::Get(const class ULocalPlayer* LocalPlayer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OutgoingInviteSubsystem", "Get");

	Params::OutgoingInviteSubsystem_Get Parms{};

	Parms.LocalPlayer = LocalPlayer;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SessionInvites.OutgoingInviteSubsystem.CreateInviteRequest
// (Final, Native, Public, HasOutParams)
// Parameters:
// class ULocalPlayer*                     LocalPlayer                                            (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FNetId&                    FriendId                                               (ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)

void UOutgoingInviteSubsystem::CreateInviteRequest(class ULocalPlayer* LocalPlayer, const struct FNetId& FriendId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OutgoingInviteSubsystem", "CreateInviteRequest");

	Params::OutgoingInviteSubsystem_CreateInviteRequest Parms{};

	Parms.LocalPlayer = LocalPlayer;
	Parms.FriendId = std::move(FriendId);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function SessionInvites.OutgoingInviteSubsystem.InviteCallbackHandle
// (Final, Native, Private)
// Parameters:
// const struct FPlatformUserId&           PlatformUserId                                         (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class FString&                    FriendId                                               (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    Result                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UOutgoingInviteSubsystem::InviteCallbackHandle(const struct FPlatformUserId& PlatformUserId, const class FString& FriendId, bool Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OutgoingInviteSubsystem", "InviteCallbackHandle");

	Params::OutgoingInviteSubsystem_InviteCallbackHandle Parms{};

	Parms.PlatformUserId = std::move(PlatformUserId);
	Parms.FriendId = std::move(FriendId);
	Parms.Result = Result;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


SDK_NAMESPACE_END
