#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ST_ProceduralTrees

#include "Basic.hpp"

#include "E_ProceduralTrees_Type_structs.hpp"
#include "E_ProceduralTrees_Size_structs.hpp"


SDK_NAMESPACE_START

// UserDefinedStruct ST_ProceduralTrees.ST_ProceduralTrees
// 0x0018 (0x0018 - 0x0000)
struct FST_ProceduralTrees final
{
public:
	class UStaticMesh*                            TreeMesh_2_2C158F5F4260079676327383E640432C;       // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	E_ProceduralTrees_Type                        Type_15_C4A2FACE47F1C486DE41279A0788F3A5;          // 0x0008(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	E_ProceduralTrees_Size                        Size_10_4398FB184D9769A68D9E36B89B07E0C8;          // 0x0009(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A[0x6];                                        // 0x000A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstance*                      MaterialInstance_13_A55E1ED84759A16DD1C6A180FDD07075; // 0x0010(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FST_ProceduralTrees;

SDK_NAMESPACE_END
