#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UITextStyleTokens

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"
#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// Class UITextStyleTokens.ODT_TextStyleTable
// 0x0000 (0x0028 - 0x0028)
class UODT_TextStyleTable final : public UObject
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ODT_TextStyleTable")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ODT_TextStyleTable")
	}
	static class UODT_TextStyleTable* GetDefaultObj()
	{
		return GetDefaultObjImpl<UODT_TextStyleTable>();
	}
};
DUMPER7_ASSERTS_UODT_TextStyleTable;

// Class UITextStyleTokens.TextStyleTokenSubsystem
// 0x0000 (0x0030 - 0x0030)
class UTextStyleTokenSubsystem final : public UGameInstanceSubsystem
{
public:
	static class UCommonTextStyle* GetTextStyle(const struct FGameplayTag& TokenTag);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("TextStyleTokenSubsystem")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TextStyleTokenSubsystem")
	}
	static class UTextStyleTokenSubsystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTextStyleTokenSubsystem>();
	}
};
DUMPER7_ASSERTS_UTextStyleTokenSubsystem;

SDK_NAMESPACE_END
