#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_HotbarPlayerHealthBar

#include "Basic.hpp"

#include "Angelscript_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass W_HotbarPlayerHealthBar.W_HotbarPlayerHealthBar_C
// 0x0000 (0x05D0 - 0x05D0)
class UW_HotbarPlayerHealthBar_C final : public UAS_HotbarHealthMeter
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_HotbarPlayerHealthBar_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_HotbarPlayerHealthBar_C")
	}
	static class UW_HotbarPlayerHealthBar_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_HotbarPlayerHealthBar_C>();
	}
};
DUMPER7_ASSERTS_UW_HotbarPlayerHealthBar_C;

SDK_NAMESPACE_END
