#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_HotbarContainer

#include "Basic.hpp"

#include "Angelscript_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass W_HotbarContainer.W_HotbarContainer_C
// 0x0040 (0x0580 - 0x0540)
class UW_HotbarContainer_C final : public UAS_HotbarContainer
{
public:
	class UW_Snackbar_C*                          W_Snackbar;                                        // 0x0540(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_TalismanHotbarNotification_C*        TalismanNotification;                              // 0x0548(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_StatusEffectContainer_C*             StatusEffectContainer;                             // 0x0550(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_HealthNotificationHotbar_C*          LowHealth;                                         // 0x0558(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_PlayerLevelUpHotbarNotification_C*   LevelUpHotbarNotification;                         // 0x0560(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_CompanionCooldownContainer_C*        CompanionCooldownContainer;                        // 0x0568(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UAS_SpicewoodSafeZone*                  AS_SpicewoodSafeZone_77;                           // 0x0570(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_HotbarContainer_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_HotbarContainer_C")
	}
	static class UW_HotbarContainer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_HotbarContainer_C>();
	}
};
DUMPER7_ASSERTS_UW_HotbarContainer_C;

SDK_NAMESPACE_END
