#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_MiniInventoryCategorySelector

#include "Basic.hpp"

#include "Angelscript_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass W_MiniInventoryCategorySelector.W_MiniInventoryCategorySelector_C
// 0x0000 (0x0480 - 0x0480)
class UW_MiniInventoryCategorySelector_C final : public UAS_MiniCategorySelector
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_MiniInventoryCategorySelector_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_MiniInventoryCategorySelector_C")
	}
	static class UW_MiniInventoryCategorySelector_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_MiniInventoryCategorySelector_C>();
	}
};
DUMPER7_ASSERTS_UW_MiniInventoryCategorySelector_C;

SDK_NAMESPACE_END
